export const AppRoute = {
  Dashboard: '/dashboard',
  WorkflowBuilder: {
    New: '/workflow-builder/new',
    Edit: '/workflow-builder/:workflowId',
  },
  Workflows: {
    Root: '/workflows',
  },
  Executions: {
    Root: '/executions',
    Execution: '/executions/:executionId',
  },
  Approvals: {
    Root: '/approvals',
  },
  Configuration: {
    Overview: '/configuration',
    Integrations: {
      Root: '/configuration/integrations',
      Configure: '/configuration/integrations/configure',
      Detail: '/configuration/integrations/:integrationId',
      DetailTab: '/configuration/integrations/:integrationId/:tab',
      Edit: '/configuration/integrations/:integrationId/edit',
    },
    Credentials: {
      Root: '/configuration/credentials',
      Detail: '/configuration/credentials/:credentialId',
      DetailTab: '/configuration/credentials/:credentialId/:tab',
    },
  },
  SystemAdministration: {
    Root: '/system-administration',
    Settings: '/system-administration/settings',
    SettingsCategory: '/system-administration/settings/:category',
    Authentication: {
      Root: '/system-administration/authentication',
      AddIdentityProvider: '/system-administration/authentication/identity-providers/add',
      IdentityProviderDetail: '/system-administration/authentication/identity-providers/:providerId',
      IdentityProviderDetailTab: '/system-administration/authentication/identity-providers/:providerId/:tab',
      EditIdentityProvider: '/system-administration/authentication/identity-providers/:providerId/edit',
      EditGroupMapping: '/system-administration/authentication/identity-providers/:providerId/group-mapping/edit',
    },
  },
  AccessManagement: {
    Root: '/system-administration/access-management',
    Users: '/system-administration/access-management/users',
    CreateUser: '/system-administration/access-management/users/create',
    UserDetail: '/system-administration/access-management/users/:userId',
    UserDetailTab: '/system-administration/access-management/users/:userId/:tab',
    EditUser: '/system-administration/access-management/users/:userId/edit',
    TransferIdentity: '/system-administration/access-management/users/:userId/transfer-identity',
    Groups: '/system-administration/access-management/groups',
    GroupDetail: '/system-administration/access-management/groups/:groupId',
    GroupDetailTab: '/system-administration/access-management/groups/:groupId/:tab',
    Policies: '/system-administration/access-management/policies',
    Roles: '/system-administration/access-management/roles',
    Projects: '/system-administration/access-management/projects',
    ProjectDetail: '/system-administration/access-management/projects/:projectId',
    ProjectDetailTab: '/system-administration/access-management/projects/:projectId/:tab',
    ServiceAccounts: '/system-administration/access-management/service-accounts',
    ServiceAccountDetail: '/system-administration/access-management/service-accounts/:serviceAccountId',
    ServiceAccountDetailTab: '/system-administration/access-management/service-accounts/:serviceAccountId/:tab',
    Assignments: '/system-administration/access-management/assignments',
    CheckAccess: '/system-administration/access-management/check-access',
    TokenRevocation: '/system-administration/access-management/token-revocation',
  },
  Auth: {
    TestSignInCallback: '/auth/test-signin-callback',
  },
  MyProfile: {
    Root: '/my-profile',
    Tab: '/my-profile/:tab',
  },
  Support: {
    Root: '/support/glossary',
    Documentation: '/support/documentation',
    FAQ: '/support/faq',
    Glossary: '/support/glossary',
  },
}
