# Generated By: Claude Code (Claude Opus 4.6)
"""Analyze document link depths from entry points to all repo content files."""

import argparse
import re
import subprocess
import sys
from collections import deque
from pathlib import Path

# --- Repo-specific configuration ---

# Entry points for reachability analysis.
ENTRY_POINTS = ["CLAUDE.md"]

# The entry point that enforces max-depth. Must directly or transitively
# link every content file within the depth limit.
DIRECT_LINK_ENTRY = "CLAUDE.md"

# Scope: only files matching these criteria are checked for reachability.
# Use inclusion when only a subset of repo files are documentation.
STANDARDS_PREFIX = "docs/standards/"
ADDITIONAL_STANDARDS = {
    "docs/decision-records.md",
    "docs/error-handling-strategy.md",
}

# --- End repo-specific configuration ---


def find_tracked_files(repo_root: str) -> list[str]:
    """Find all tracked files using git ls-files (respects .gitignore)."""
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],  # noqa: S607
        capture_output=True,
        text=True,
        cwd=repo_root,
        check=False,
    )
    return sorted(line for line in result.stdout.strip().splitlines() if line)


def extract_links(filepath: str, repo_root: str) -> list[str]:
    """Extract relative file links from a markdown file."""
    rel_path = Path(filepath).relative_to(repo_root)
    file_dir = str(rel_path.parent)

    try:
        content = Path(filepath).read_text(encoding="utf-8")
    except (UnicodeDecodeError, FileNotFoundError):
        return []

    pattern = r"\[[^\]]*\]\(([^)]+)\)"
    links = []
    for match in re.finditer(pattern, content):
        target = match.group(1)
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        if target.startswith("#"):
            continue
        target = target.split("#")[0]
        if not target:
            continue
        raw = target.lstrip("/") if target.startswith("/") else str(Path(file_dir, target))
        links.append(str(Path(raw)))

    return links


def build_link_graph(repo_root: str, all_files: list[str]) -> dict[str, list[str]]:
    """Build a directed graph of file -> files it links to."""
    graph: dict[str, list[str]] = {}
    all_files_set = set(all_files)

    for f in all_files:
        if not f.endswith(".md"):
            continue
        full = str(Path(repo_root) / f)
        raw_links = extract_links(full, repo_root)
        resolved = []
        for link in raw_links:
            if link in all_files_set:
                resolved.append(link)
            elif link + "/README.md" in all_files_set:
                resolved.append(link + "/README.md")
            elif link.endswith("/"):
                candidate = link + "README.md"
                if candidate in all_files_set:
                    resolved.append(candidate)
                dir_path = link.rstrip("/") + "/"
                resolved.extend(af for af in all_files if af.startswith(dir_path))
        graph[f] = list(dict.fromkeys(resolved))

    return graph


def bfs_depths(graph: dict[str, list[str]], start: str) -> dict[str, int]:
    """BFS from start node, return depth to each reachable node."""
    depths: dict[str, int] = {start: 1}
    queue = deque([(start, 1)])

    while queue:
        node, depth = queue.popleft()
        for neighbor in graph.get(node, []):
            if neighbor not in depths:
                depths[neighbor] = depth + 1
                queue.append((neighbor, depth + 1))

    return depths


def is_content_file(filepath: str) -> bool:
    """Check if a file is content that must be reachable from entry points."""
    if filepath.startswith(STANDARDS_PREFIX):
        return True
    return filepath in ADDITIONAL_STANDARDS


def build_depth_table(
    all_files: list[str],
    depths_by_entry: dict[str, dict[str, int]],
    entry_set: set[str],
) -> tuple[list[str], list[tuple[str, str]]]:
    """Build a markdown depth table and collect unreachable files."""
    lines = [
        "# Document Depth Analysis",
        "",
        "Depth = shortest link-chain from entry point to file.",
        "Entry points have depth 1. Depth x = no path exists.",
        "",
        "| File | " + " | ".join(depths_by_entry.keys()) + " |",
        "|------" + "|-----------|" * len(depths_by_entry),
    ]

    unreachable = []
    for f in all_files:
        cols = [str(depths.get(f, "x")) for _entry, depths in depths_by_entry.items()]
        lines.append(f"| `{f}` | " + " | ".join(cols) + " |")
        if is_content_file(f) and f not in entry_set:
            for entry, depths in depths_by_entry.items():
                if f not in depths:
                    unreachable.append((f, entry))

    return lines, unreachable


def find_failures(
    content_files: list[str],
    depths_by_entry: dict[str, dict[str, int]],
    max_depth: int,
    unreachable: list[tuple[str, str]],
) -> list[tuple[str, str]]:
    """Find content files that are unreachable or exceed max depth."""
    direct_depths = depths_by_entry.get(DIRECT_LINK_ENTRY, {})
    too_deep = [
        (f, direct_depths.get(f)) for f in content_files if direct_depths.get(f) is None or direct_depths[f] > max_depth
    ]

    return unreachable + [(f, f"{DIRECT_LINK_ENTRY} (depth {d}, max {max_depth})") for f, d in too_deep]


def main() -> None:
    """Run reachability check."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any content file is unreachable or exceeds max depth",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=3,
        help="Maximum allowed depth from direct-link entry (default: 3)",
    )
    args = parser.parse_args()

    repo_root = str(Path(__file__).resolve().parent.parent)
    all_files = find_tracked_files(repo_root)
    graph = build_link_graph(repo_root, all_files)

    entry_set = set(ENTRY_POINTS)
    depths_by_entry = {entry: bfs_depths(graph, entry) for entry in ENTRY_POINTS if entry in set(all_files)}

    content_files = [f for f in all_files if is_content_file(f) and f not in entry_set]
    lines, unreachable = build_depth_table(all_files, depths_by_entry, entry_set)

    if not args.check:
        output_path = str(Path(repo_root) / "ANALYSIS.md")
        with Path(output_path).open("w") as out:
            out.write("\n".join(lines) + "\n")
        print(
            f"Wrote {output_path} ({len(content_files)} content files, {len(all_files) - len(content_files)} excluded)"
        )

    for entry, depths in depths_by_entry.items():
        reachable = sum(1 for f in content_files if f in depths)
        print(f"Reachable from {entry}: {reachable}/{len(content_files)} content files")

    failures = find_failures(content_files, depths_by_entry, args.max_depth, unreachable)
    if args.check and failures:
        print(f"\nERROR: {len(failures)} issue(s):")
        for filepath, detail in failures:
            if isinstance(detail, str) and detail.startswith(DIRECT_LINK_ENTRY):
                print(f"  {filepath} — {detail}")
            else:
                print(f"  {filepath} — not reachable from {detail}")
        sys.exit(1)


if __name__ == "__main__":
    main()
