"""add_prompt_to_approval_requests

Revision ID: 4157061b9959
Revises: 4ca3cbf8652a
Create Date: 2026-08-24 17:25:45.934191

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4157061b9959"
down_revision: str | Sequence[str] | None = "4ca3cbf8652a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("approval_requests", sa.Column("prompt", sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("approval_requests", "prompt")
    # ### end Alembic commands ###
