"""Make form_prompts.temporal_activity_id non-nullable

Revision ID: 8e219d0fad36
Revises: 2a78b3c49c72
Create Date: 2026-09-21 12:53:45.500382

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e219d0fad36"
down_revision: str | Sequence[str] | None = "2a78b3c49c72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_prompts", "temporal_activity_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_prompts", "temporal_activity_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
