"""execution launcher workflow id

Add ``executions.launcher_temporal_workflow_id`` so workflow deletion can cancel
a scheduled run's parent launcher rather than its child orchestrator workflow.

A scheduled run is started by ScheduledWorkflowLauncher, which commits the
execution row in a setup activity and only then starts the orchestrator as a
child. During that gap ``temporal_workflow_id`` names a child that does not
exist yet, so cancelling it is a silent no-op and the launcher proceeds to start
it anyway. Cancelling the launcher closes that window: its ParentClosePolicy is
REQUEST_CANCEL, which stops a started child or prevents an unstarted one.

NULL for every non-scheduled execution, and for scheduled executions created
before this migration.

TODO(AAP-87750): two defects in the predecessor revision 7367ba3d8ccb
(PR #35, "workflow hard deletes") were found while reviewing this change and are
deliberately NOT fixed here — that migration belongs to an unmerged PR and editing
it from this branch would conflict on rebase.  Fix them in PR #35 before it merges,
or immediately after:

1. ``upgrade()`` NULLs ``executions.workflow_id`` / ``workflow_version_id`` before
   altering those columns to nullable.  In the predecessor schema both are NOT NULL,
   so any execution referencing a soft-deleted workflow or version aborts the
   migration — precisely the historical data the cleanup exists to handle.  The
   ALTERs must run before the UPDATEs.
2. ``downgrade()`` restores NOT NULL on both columns.  After normal operation the
   feature deliberately leaves executions with NULL workflow references, so the
   rollback fails as soon as the feature has been used.  Either define an explicit
   downgrade data strategy (e.g. delete detached executions) or mark the revision
   irreversible.

Revision ID: 9c1f4a2be7d3
Revises: 7367ba3d8ccb
Create Date: 2026-08-20 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c1f4a2be7d3"
down_revision: str | Sequence[str] | None = "7367ba3d8ccb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the nullable launcher_temporal_workflow_id column and its index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "executions",
        sa.Column("launcher_temporal_workflow_id", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_executions_launcher_temporal_workflow_id"),
        "executions",
        ["launcher_temporal_workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the launcher_temporal_workflow_id column and its index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_executions_launcher_temporal_workflow_id"), table_name="executions")
    op.drop_column("executions", "launcher_temporal_workflow_id")
    # ### end Alembic commands ###
