"""add replayed flag to activity_execution

Revision ID: 9cc9738e0778
Revises: d4f2d830274a
Create Date: 2026-09-17 15:06:33.876290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9cc9738e0778"
down_revision: Union[str, Sequence[str], None] = "d4f2d830274a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also emits unrelated drift (approval_requests,
    # groups/users hard-delete leftovers, invocations, token tables) from
    # un-migrated model changes elsewhere on devel. Those belong to their own
    # revisions and are intentionally left out here.
    op.add_column("activity_execution", sa.Column("replayed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: unrelated drift stripped here as in upgrade() — see above.
    op.drop_column("activity_execution", "replayed")
    # ### end Alembic commands ###
