"""node-kind permissions: published_by, denied_nodes, denied activity status

Revision ID: a1750b0c9d01
Revises: d5b8c2f04e71
Create Date: 2026-09-22 00:00:00.000000

Node-kind level permissions (ANSTRAT-1750) need three schema additions:

- ``workflow_versions.published_by``: the principal that last published the
  version. Scheduled, webhook and EDA runs evaluate node permissions as this
  principal (the invoker is used for manual and test runs). Nullable so that
  versions published before this migration keep working; callers fall back to
  ``created_by`` when it is null.
- ``executions.denied_nodes``: JSONB list of ``{node_id, kind, denied_by}``
  for nodes the run principal was not allowed to execute. Null when nothing
  was denied.
- ``activitystatus`` enum gains the terminal value ``denied`` for a node that
  was never started because its kind was denied for the run principal.
- ``nodetype`` enum gains the new node kind ``mcp_tool``; activity rows are
  written with this enum, so an execution containing that kind fails without it.

Custom SQL is required for the enum values: PostgreSQL enum values cannot be
added through the SQLAlchemy operations and cannot be removed, so the
downgrade leaves the values in place (harmless: nothing writes them after the
downgrade).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1750b0c9d01"
down_revision: str | Sequence[str] | None = "d5b8c2f04e71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add published_by, denied_nodes and the denied activity status."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_versions", sa.Column("published_by", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_workflow_versions_published_by",
        "workflow_versions",
        ["published_by"],
        unique=False,
    )
    op.create_foreign_key(
        "workflow_versions_published_by_fkey",
        "workflow_versions",
        "principals",
        ["published_by"],
        ["id"],
    )
    op.add_column(
        "executions",
        sa.Column("denied_nodes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###

    # CUSTOM: PostgreSQL enum values can only be added with ALTER TYPE.
    op.execute("ALTER TYPE activitystatus ADD VALUE IF NOT EXISTS 'denied'")
    op.execute("ALTER TYPE nodetype ADD VALUE IF NOT EXISTS 'mcp_tool'")
    # END CUSTOM


def downgrade() -> None:
    """Drop published_by and denied_nodes (the enum value cannot be removed)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("executions", "denied_nodes")
    op.drop_constraint(
        "workflow_versions_published_by_fkey",
        "workflow_versions",
        type_="foreignkey",
    )
    op.drop_index("ix_workflow_versions_published_by", table_name="workflow_versions")
    op.drop_column("workflow_versions", "published_by")
    # ### end Alembic commands ###
