"""Add composite index for stall detection scanner.

Revision ID: a8b4c6d2e1f3
Revises: e3a1f5b7d924
Create Date: 2026-10-01 12:00:00.000000

Adds a composite index to support efficient scanning for stalled activities
(AAP-92825). The scanner query filters by:

- status = 'running'
- stall_alert_at IS NULL
- started_at IS NOT NULL
- started_at + expected_duration < now()

The (status, stall_alert_at, started_at) index enables efficient evaluation
of this predicate without a table scan.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8b4c6d2e1f3"
down_revision: str | Sequence[str] | None = "e3a1f5b7d924"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_activity_execution_stall_scan",
        "activity_execution",
        ["status", "stall_alert_at", "started_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_execution_stall_scan", table_name="activity_execution")
    # ### end Alembic commands ###
