"""Add notes field to form_prompts

Revision ID: b54f2f21e6e2
Revises: 2a78b3c49c72
Create Date: 2026-09-22 12:14:45.571644

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b54f2f21e6e2"
down_revision: str | Sequence[str] | None = "2a78b3c49c72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_prompts", sa.Column("notes", sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_prompts", "notes")
    # ### end Alembic commands ###
