"""add agent_execution_id to invocations

Revision ID: d5b8c2f04e71
Revises: c4a7e1f93d21
Create Date: 2026-09-11 00:00:00.000000

Invocations gain an explicit, indexed FK to the builtin "Agent Execution"
workflow execution running them, replacing an unindexed expression scan over
``executions.input_data->>'invocation_id'``.

Custom SQL backfills the new column from that JSONB link for invocations
created before this migration. The backfill is restricted to the builtin
workflow in the builtin project, matched on the ``is_builtin`` flags as well
as the names: ``input_data`` was caller-writable, so without the restriction
any execution could claim an ``invocation_id``. This migration is now the only
place that decision is made, and it is persisted rather than re-evaluated on
every cancel.

``ondelete="SET NULL"`` is required, not cosmetic: ``executions_workflow_id_fkey``
is ON DELETE CASCADE (migration 7367ba3d8ccb), so a workflow hard-delete purges
executions; a NO ACTION default would turn that into an IntegrityError.

Downgrade is lossless — ``executions.input_data`` is never modified.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b8c2f04e71"
down_revision: str | Sequence[str] | None = "c4a7e1f93d21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# CUSTOM: backfill the new FK from the legacy executions.input_data JSONB link.
#
# Guards, each load-bearing:
#   - the uuid regex runs before the ::uuid cast, so a malformed historical
#     value cannot abort the whole migration;
#   - DISTINCT ON with non-terminal-then-newest ordering picks deterministically
#     when retries left several executions claiming one invocation;
#   - is_builtin on both workflow and project mirrors the runtime guard this
#     replaces, so a caller-forged input_data cannot claim an invocation;
#   - created_at >= blocks a forged id pointing at an older invocation.
#
# Workflow/project names are hard-coded rather than imported from
# syntara.workflows.constants: migrations must not depend on app constants
# that can drift from what was true when the migration ran.
_BACKFILL_SQL = """
UPDATE invocations AS i
SET agent_execution_id = picked.execution_id
FROM (
    SELECT DISTINCT ON (((e.input_data ->> 'invocation_id')::uuid))
           (e.input_data ->> 'invocation_id')::uuid AS invocation_id,
           e.id                                     AS execution_id
    FROM executions AS e
    JOIN workflows  AS w ON w.id = e.workflow_id
    JOIN projects   AS p ON p.id = w.project_id
    WHERE w.name = 'Agent Execution' AND w.is_builtin IS TRUE
      AND p.name = 'built-in'        AND p.is_builtin IS TRUE
      AND e.input_data ->> 'invocation_id' ~*
          '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    ORDER BY ((e.input_data ->> 'invocation_id')::uuid),
             (e.status::text IN ('completed','completed_with_errors','failed','cancelled')) ASC,
             e.created_at DESC
) AS picked
WHERE i.id = picked.invocation_id
  AND i.agent_execution_id IS NULL
  AND EXISTS (SELECT 1 FROM executions e2
              WHERE e2.id = picked.execution_id AND e2.created_at >= i.created_at);
"""
# END CUSTOM


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invocations", sa.Column("agent_execution_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "invocations_agent_execution_id_fkey",
        "invocations",
        "executions",
        ["agent_execution_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # CUSTOM: backfill before the index exists so the one-off scan does not also
    # pay for index maintenance; see _BACKFILL_SQL for why each guard is there.
    op.execute(sa.text(_BACKFILL_SQL))
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_invocations_agent_execution_id"),
        "invocations",
        ["agent_execution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invocations_agent_execution_id"), table_name="invocations")
    op.drop_constraint("invocations_agent_execution_id_fkey", "invocations", type_="foreignkey")
    op.drop_column("invocations", "agent_execution_id")
    # ### end Alembic commands ###
