"""File-upload test helpers for integration tests.

Extracted from the migrated performance tests to resolve stale
``tests.performance.files.conftest`` import paths.
"""

from __future__ import annotations

import io
import time
from typing import TYPE_CHECKING, Any
from uuid import UUID

from tests.integration.helpers.perf import generate_pdf_content, generate_text_content

if TYPE_CHECKING:
    from syntara_api_client.api import SyntaraApiRegistry

    from syntara.files.models import FileMetadata

_TEST_PROJECT_ID = UUID("00000000-0000-0000-0000-000000000001")

FILE_TYPE_PDF = "pdf"
FILE_TYPE_TEXT = "txt"
MIME_TEXT = "text/plain"
MIME_PDF = "application/pdf"

UPLOAD_COUNT = 50

FILE_MIX: list[dict[str, Any]] = [
    {"ext": FILE_TYPE_PDF, "mime": MIME_PDF, "size_kb": 128},
    {
        "ext": "docx",
        "mime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size_kb": 64,
    },
    {"ext": FILE_TYPE_TEXT, "mime": MIME_TEXT, "size_kb": 32},
]


def build_file_sequence(count: int = UPLOAD_COUNT) -> list[dict[str, Any]]:
    """Return a list of *count* file descriptors cycling through FILE_MIX."""
    return [FILE_MIX[i % len(FILE_MIX)] for i in range(count)]


def make_file_metadata(content: bytes, suffix: str = ".txt") -> FileMetadata:
    """Create a FileMetadata instance for direct converter testing (no disk I/O)."""
    from syntara.files.models import FileMetadata, FileStatus

    mime_map = {
        ".txt": MIME_TEXT,
        ".pdf": MIME_PDF,
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    }
    mime = mime_map.get(suffix, "application/octet-stream")
    return FileMetadata(
        filename=f"perf_test{suffix}",
        file_path=f"/tmp/perf_test{suffix}",  # noqa: S108
        mime_type=mime,
        size_bytes=len(content),
        status=FileStatus.PENDING_CONVERSION,
    )


def _make_file_payload(descriptor: dict[str, Any], index: int) -> tuple[str, io.BytesIO, str]:
    ext = descriptor["ext"]
    mime = descriptor["mime"]
    size_kb: int = descriptor["size_kb"]
    data = generate_pdf_content(size_kb) if ext == FILE_TYPE_PDF else generate_text_content(size_kb)
    return f"perf_test_{index:03d}.{ext}", io.BytesIO(data), mime


def upload_single_file(
    syntara_api: SyntaraApiRegistry,
    descriptor: dict[str, Any],
    index: int,
) -> tuple[float, bool, int]:
    """Upload a single file via POST /api/v1/files; return (elapsed_ms, success, status_code)."""
    from syntara_api_client.models.upload_files_body import UploadFilesBody
    from syntara_api_client.types import File

    filename, payload, mime_type = _make_file_payload(descriptor, index)
    body = UploadFilesBody(
        files=[File(payload=payload, file_name=filename, mime_type=mime_type)],
        project_id=_TEST_PROJECT_ID,
    )
    start = time.monotonic()
    try:
        r = syntara_api.files.upload(body=body)
        elapsed_ms = (time.monotonic() - start) * 1000
        return elapsed_ms, r.is_success, r.status_code
    except Exception:
        elapsed_ms = (time.monotonic() - start) * 1000
        return elapsed_ms, False, 0


def upload_large_file(
    syntara_api: SyntaraApiRegistry,
    filename: str,
    data: bytes,
    mime_type: str,
) -> tuple[float, bool, int]:
    """Upload pre-generated bytes via POST /api/v1/files; return (elapsed_ms, success, status_code)."""
    from syntara_api_client.models.upload_files_body import UploadFilesBody
    from syntara_api_client.types import File

    body = UploadFilesBody(
        files=[File(payload=io.BytesIO(data), file_name=filename, mime_type=mime_type)],
        project_id=_TEST_PROJECT_ID,
    )
    start = time.monotonic()
    try:
        r = syntara_api.files.upload(body=body)
        elapsed_ms = (time.monotonic() - start) * 1000
        return elapsed_ms, r.is_success, r.status_code
    except Exception:
        elapsed_ms = (time.monotonic() - start) * 1000
        return elapsed_ms, False, 0
