import type { ExecutionsAPI } from '@syntara/contracts'

import { mockDate } from './mockDates'

type ActivityExecution = ExecutionsAPI.components['schemas']['ActivityExecution']

/**
 * Sample activity execution data for mock API.
 * Keyed by execution ID, values are arrays of ActivityExecution for that execution.
 *
 * These match the workflow node IDs from the example YAML files:
 * - exec-1 and exec-2 map to workflow '2' (hello-world): nodes say_hello, say_goodbye
 * - exec-3 maps to workflow '1' (conditional-demo): node check_temperature (failed)
 * - exec-4 maps to workflow '1' (conditional-demo): node check_temperature (running)
 * - exec-5 maps to workflow '1' (conditional-demo): nodes check_temperature, temperature_routing, hot_weather
 * - exec-6 maps to workflow '2' (hello-world): node say_hello (paused)
 * - exec-8 maps to workflow '3' (loop-demo): node task_iteration (cancelled)
 * - exec-9 maps to workflow '4' (parallel-demo): nodes task1, task2, task3, summary
 * - exec-10 maps to workflow '4' (parallel-demo): pending (no activities started yet)
 * - exec-approval maps to workflow '52' (deployment-approval): staging_tests (completed), approval_gate (waiting)
 */
export const activityExecutions: Record<string, ActivityExecution[]> = {
  'exec-1': [
    {
      id: 'act-1-1',
      created_at: mockDate.daysAgo2,
      updated_at: mockDate.daysAgo2Plus2500ms,
      execution_id: 'exec-1',
      activity_name: 'say_hello',
      status: 'completed',
      started_at: mockDate.daysAgo2Plus1s,
      completed_at: mockDate.daysAgo2Plus2500ms,
      input_data: {
        GREETING: 'Hello',
        WORLD_NAME: 'World',
      } as Record<string, unknown>,
      output_data: {
        stdout: 'Hello, World!\nCurrent time: 2025-04-08T10:00:01Z',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-1-2',
      created_at: mockDate.daysAgo2Plus2500ms,
      updated_at: mockDate.daysAgo2Plus4s,
      execution_id: 'exec-1',
      activity_name: 'say_goodbye',
      status: 'completed',
      started_at: mockDate.daysAgo2Plus2500ms,
      completed_at: mockDate.daysAgo2Plus4s,
      input_data: {
        FAREWELL: 'Goodbye',
      } as Record<string, unknown>,
      output_data: {
        stdout: 'Goodbye, World!',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-2': [
    {
      id: 'act-2-1',
      created_at: mockDate.daysAgo1,
      updated_at: mockDate.daysAgo1Plus1500ms,
      execution_id: 'exec-2',
      activity_name: 'say_hello',
      status: 'completed',
      started_at: mockDate.daysAgo1Plus1s,
      completed_at: mockDate.daysAgo1Plus1500ms,
      input_data: {
        GREETING: 'Hello',
        WORLD_NAME: 'World',
      } as Record<string, unknown>,
      output_data: {
        stdout: 'Hello, World!\nCurrent time: 2025-04-09T14:30:00Z',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-2-2',
      created_at: mockDate.daysAgo1Plus1500ms,
      updated_at: mockDate.daysAgo1Plus2500ms,
      execution_id: 'exec-2',
      activity_name: 'say_goodbye',
      status: 'completed',
      started_at: mockDate.daysAgo1Plus1500ms,
      completed_at: mockDate.daysAgo1Plus2500ms,
      input_data: {
        FAREWELL: 'Goodbye',
      } as Record<string, unknown>,
      output_data: {
        stdout: 'Goodbye, World!',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-3': [
    {
      id: 'act-3-1',
      created_at: mockDate.hoursAgo6Plus1s,
      updated_at: mockDate.hoursAgo6Plus2s,
      execution_id: 'exec-3',
      activity_name: 'check_temperature',
      status: 'failed',
      started_at: mockDate.hoursAgo6Plus1s,
      completed_at: mockDate.hoursAgo6Plus2s,
      input_data: {
        temp: 35,
      } as Record<string, unknown>,
      output_data: null,
      error_details: 'Task execution failed: Connection timeout',
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-4': [
    {
      id: 'act-4-1',
      created_at: mockDate.hoursAgo2Plus1s,
      updated_at: mockDate.minutesAgo30,
      execution_id: 'exec-4',
      activity_name: 'check_temperature',
      status: 'running',
      started_at: mockDate.hoursAgo2Plus1s,
      completed_at: null,
      input_data: {
        temp: 25,
      } as Record<string, unknown>,
      output_data: null,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-5': [
    {
      id: 'act-5-1',
      created_at: mockDate.daysAgo3,
      updated_at: mockDate.daysAgo3Plus2s,
      execution_id: 'exec-5',
      activity_name: 'check_temperature',
      status: 'completed',
      started_at: mockDate.daysAgo3Plus1s,
      completed_at: mockDate.daysAgo3Plus2s,
      input_data: {
        temp: 42,
      } as Record<string, unknown>,
      output_data: {
        temp_value: '42',
        stdout: 'Current temperature: 42°C\nChecked at: 2025-04-07T08:00:00Z',
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-5-2',
      created_at: mockDate.daysAgo3Plus2s,
      updated_at: mockDate.daysAgo3Plus2500ms,
      execution_id: 'exec-5',
      activity_name: 'temperature_routing',
      status: 'completed',
      started_at: mockDate.daysAgo3Plus2s,
      completed_at: mockDate.daysAgo3Plus2500ms,
      input_data: {
        temperature: 42,
      } as Record<string, unknown>,
      output_data: {
        branch: 'true',
        condition_result: true,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-5-3',
      created_at: mockDate.daysAgo3Plus2500ms,
      updated_at: mockDate.daysAgo3Plus4s,
      execution_id: 'exec-5',
      activity_name: 'hot_weather',
      status: 'completed',
      started_at: mockDate.daysAgo3Plus2500ms,
      completed_at: mockDate.daysAgo3Plus4s,
      input_data: {
        temperature: 42,
      } as Record<string, unknown>,
      output_data: {
        stdout: 'It is hot! Stay hydrated.',
        recommendation: 'Stay indoors and drink water',
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-9': [
    {
      id: 'act-9-1',
      created_at: mockDate.daysAgo4Plus1s,
      updated_at: mockDate.daysAgo4Plus12s,
      execution_id: 'exec-9',
      activity_name: 'task1',
      status: 'completed',
      started_at: mockDate.daysAgo4Plus1s,
      completed_at: mockDate.daysAgo4Plus12s,
      input_data: {} as Record<string, unknown>,
      output_data: {
        stdout: 'Task 1 starting...\nTask 1 complete!',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-9-2',
      created_at: mockDate.daysAgo4Plus1s,
      updated_at: mockDate.daysAgo4Plus12s,
      execution_id: 'exec-9',
      activity_name: 'task2',
      status: 'completed',
      started_at: mockDate.daysAgo4Plus1s,
      completed_at: mockDate.daysAgo4Plus12s,
      input_data: {} as Record<string, unknown>,
      output_data: {
        stdout: 'Task 2 starting...\nTask 2 complete!',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-9-3',
      created_at: mockDate.daysAgo4Plus1s,
      updated_at: mockDate.daysAgo4Plus12s,
      execution_id: 'exec-9',
      activity_name: 'task3',
      status: 'completed',
      started_at: mockDate.daysAgo4Plus1s,
      completed_at: mockDate.daysAgo4Plus12s,
      input_data: {} as Record<string, unknown>,
      output_data: {
        stdout: 'Task 3 starting...\nTask 3 complete!',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-9-4',
      created_at: mockDate.daysAgo4Plus12s,
      updated_at: mockDate.daysAgo4Plus12s,
      execution_id: 'exec-9',
      activity_name: 'summary',
      status: 'completed',
      started_at: mockDate.daysAgo4Plus12s,
      completed_at: mockDate.daysAgo4Plus12s,
      input_data: {} as Record<string, unknown>,
      output_data: {
        stdout: 'All parallel tasks completed!',
        exit_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-6': [
    {
      id: 'act-6-1',
      created_at: mockDate.hoursAgo12Plus1s,
      updated_at: mockDate.hoursAgo12Plus1s,
      execution_id: 'exec-6',
      activity_name: 'say_hello',
      status: 'paused',
      started_at: mockDate.hoursAgo12Plus1s,
      completed_at: null,
      input_data: {
        GREETING: 'Hello',
        WORLD_NAME: 'World',
      } as Record<string, unknown>,
      output_data: null,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-8': [
    {
      id: 'act-8-1',
      created_at: mockDate.hoursAgo1Plus1s,
      updated_at: mockDate.minutesAgo45,
      execution_id: 'exec-8',
      activity_name: 'task_iteration',
      status: 'cancelled',
      started_at: mockDate.hoursAgo1Plus1s,
      completed_at: mockDate.minutesAgo45,
      input_data: {
        iteration: 1,
      } as Record<string, unknown>,
      output_data: {
        stdout: 'Processing iteration 1...',
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: 1,
    },
  ],
  'exec-approval': [
    {
      id: 'act-appr-1',
      created_at: mockDate.minutesAgo10,
      updated_at: mockDate.minutesAgo10,
      execution_id: 'exec-approval',
      activity_name: 'staging_tests',
      status: 'completed',
      started_at: mockDate.minutesAgo10,
      completed_at: mockDate.minutesAgo10,
      input_data: { version: '3.2.0' } as Record<string, unknown>,
      output_data: {
        tests_passed: 42,
        tests_failed: 0,
        coverage: 94.5,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-appr-2',
      created_at: mockDate.minutesAgo10,
      updated_at: mockDate.minutesAgo10,
      execution_id: 'exec-approval',
      activity_name: 'approval_gate',
      status: 'waiting',
      started_at: mockDate.minutesAgo10,
      completed_at: null,
      input_data: {} as Record<string, unknown>,
      output_data: null,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
  'exec-42': [
    {
      id: 'act-42-1',
      created_at: mockDate.hoursAgo3,
      updated_at: mockDate.hoursAgo3,
      execution_id: 'exec-42',
      activity_name: 'staging_tests',
      status: 'completed',
      started_at: mockDate.hoursAgo3,
      completed_at: mockDate.hoursAgo3,
      input_data: { version: '3.2.0' } as Record<string, unknown>,
      output_data: {
        tests_passed: 42,
        tests_failed: 0,
        coverage: 94.5,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-42-2',
      created_at: mockDate.hoursAgo3,
      updated_at: mockDate.hoursAgo2Plus1s,
      execution_id: 'exec-42',
      activity_name: 'approval_gate',
      status: 'completed',
      started_at: mockDate.hoursAgo3,
      completed_at: mockDate.hoursAgo2Plus1s,
      input_data: {
        prompt: 'Review the staging test results and approve deployment of v3.2.0 to production.',
        approvers: ['ops-team@example.com'],
        decision_window: 86400,
      } as Record<string, unknown>,
      output_data: {
        status: 'completed',
        decision: 'approved',
        decided_by: 'jsmith',
        decided_at: '2026-06-15T08:00:01.000Z',
        decision_notes: 'Verified staging tests pass. Approved for production.',
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
    {
      id: 'act-42-3',
      created_at: mockDate.hoursAgo2Plus1s,
      updated_at: mockDate.hoursAgo2Plus1s,
      execution_id: 'exec-42',
      activity_name: 'deploy_to_prod',
      status: 'completed',
      started_at: mockDate.hoursAgo2Plus1s,
      completed_at: mockDate.hoursAgo2Plus1s,
      input_data: {} as Record<string, unknown>,
      output_data: {
        status: 'completed',
        stdout: 'Deploying v3.2.0 to production\nDeployment successful!',
        return_code: 0,
      } as Record<string, unknown>,
      error_details: null,
      retry_count: 0,
      iteration: null,
    },
  ],
}
