import type * as IntegrationsAPI from '@syntara/contracts/src/integrations-api.js'
import { IntegrationStatusEnum, IntegrationTypeEnum } from '@syntara/contracts'

import { mockDate } from './mockDates'

type IntegrationRead = IntegrationsAPI.components['schemas']['IntegrationRead']

const MOCK_USER_1_REF = { id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', name: 'user-1' }

export const integrations: IntegrationRead[] = [
  {
    id: '1',
    name: 'GitHub Copilot',
    description: 'GitHub Copilot MCP integration',
    integration_type: IntegrationTypeEnum.MCP_SERVER,
    enabled: true,
    validation_status: IntegrationStatusEnum.AVAILABLE,
    scope: 'global',
    configuration: {
      integration_type: IntegrationTypeEnum.MCP_SERVER,
      base_url: 'https://mcp.github.example.com',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: 'cred-001',
    last_validated_at: '2024-01-15T10:00:00Z',
    validation_error: null,
    refresh_status: IntegrationStatusEnum.AVAILABLE,
    last_refreshed_at: '2024-01-15T10:00:00Z',
    refresh_error: null,
    total_tool_count: 5,
    enabled_tool_count: 5,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '2',
    name: 'Slack Bot',
    description: 'Slack messaging integration',
    integration_type: IntegrationTypeEnum.MCP_SERVER,
    enabled: true,
    validation_status: IntegrationStatusEnum.AVAILABLE,
    scope: 'global',
    configuration: {
      integration_type: IntegrationTypeEnum.MCP_SERVER,
      base_url: 'https://mcp.slack.example.com',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: null,
    last_validated_at: '2024-01-16T11:00:00Z',
    validation_error: null,
    refresh_status: IntegrationStatusEnum.AVAILABLE,
    last_refreshed_at: '2024-01-16T11:00:00Z',
    refresh_error: null,
    total_tool_count: 3,
    enabled_tool_count: 3,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-16T11:00:00Z',
    updated_at: '2024-01-16T11:00:00Z',
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '3',
    name: 'Jira Integration',
    description: 'Jira project tracking',
    integration_type: IntegrationTypeEnum.MCP_SERVER,
    enabled: true,
    validation_status: IntegrationStatusEnum.ERROR,
    scope: 'project',
    project_ids: ['p-001', 'p-002'],
    configuration: {
      integration_type: IntegrationTypeEnum.MCP_SERVER,
      base_url: 'https://mcp.atlassian.example.com',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: 'cred-003',
    last_validated_at: '2024-01-17T12:00:00Z',
    validation_error: 'Connection refused',
    refresh_status: IntegrationStatusEnum.ERROR,
    last_refreshed_at: '2024-01-17T12:00:00Z',
    refresh_error: 'Unable to connect to service',
    total_tool_count: 3,
    enabled_tool_count: 2,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-17T12:00:00Z',
    updated_at: '2024-01-17T12:00:00Z',
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '4',
    name: 'ServiceNow',
    description: 'ServiceNow ITSM integration',
    integration_type: IntegrationTypeEnum.MCP_SERVER,
    enabled: true,
    validation_status: IntegrationStatusEnum.UNKNOWN,
    scope: 'global',
    configuration: {
      integration_type: IntegrationTypeEnum.MCP_SERVER,
      base_url: 'https://mcp.servicenow.example.com',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: null,
    last_validated_at: null,
    validation_error: null,
    refresh_status: null,
    last_refreshed_at: null,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-18T13:00:00Z',
    updated_at: '2024-01-18T13:00:00Z',
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '5',
    name: 'PagerDuty',
    description: 'PagerDuty incident management',
    integration_type: IntegrationTypeEnum.MCP_SERVER,
    enabled: false,
    validation_status: IntegrationStatusEnum.AVAILABLE,
    scope: 'global',
    configuration: {
      integration_type: IntegrationTypeEnum.MCP_SERVER,
      base_url: 'https://mcp.pagerduty.example.com',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: null,
    last_validated_at: '2024-01-19T14:00:00Z',
    validation_error: null,
    refresh_status: IntegrationStatusEnum.AVAILABLE,
    last_refreshed_at: '2024-01-19T14:00:00Z',
    refresh_error: null,
    total_tool_count: 1,
    enabled_tool_count: 1,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-19T14:00:00Z',
    updated_at: '2024-01-19T14:00:00Z',
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '10',
    name: 'Red Hat AI',
    description: 'Red Hat AI LLM provider for Granite models',
    integration_type: 'llm_provider',
    enabled: true,
    validation_status: IntegrationStatusEnum.AVAILABLE,
    scope: 'global',
    configuration: {
      integration_type: 'llm_provider',
      provider_hint: 'red_hat_ai',
      base_url: 'https://api.redhat-ai.example.com/v1',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: 'cred-004',
    last_validated_at: mockDate.daysAgo3,
    validation_error: null,
    refresh_status: IntegrationStatusEnum.AVAILABLE,
    last_refreshed_at: mockDate.daysAgo1,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 5,
    enabled_model_count: 3,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo1,
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '11',
    name: 'OpenAI Production',
    description: 'OpenAI API for production workloads',
    integration_type: 'llm_provider',
    enabled: true,
    validation_status: IntegrationStatusEnum.AVAILABLE,
    scope: 'global',
    configuration: {
      integration_type: 'llm_provider',
      provider_hint: 'openai',
      base_url: 'https://api.openai.com/v1',
      allow_http: false,
      insecure_skip_tls_verify: false,
      ca_certificate: null,
    },
    management_credential_id: null,
    last_validated_at: mockDate.daysAgo2,
    validation_error: null,
    refresh_status: IntegrationStatusEnum.AVAILABLE,
    last_refreshed_at: mockDate.daysAgo1,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 8,
    enabled_model_count: 4,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo1,
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
  {
    id: '12',
    name: 'Production AAP',
    description: 'Ansible Automation Platform production instance',
    integration_type: 'ansible_automation_platform',
    enabled: true,
    validation_status: IntegrationStatusEnum.AVAILABLE,
    scope: 'global',
    configuration: {
      integration_type: 'ansible_automation_platform',
      base_url: 'https://aap.prod.example.com',
      allow_http: false,
      insecure_skip_tls_verify: true,
      ca_certificate: null,
    },
    management_credential_id: 'cred-001',
    last_validated_at: mockDate.daysAgo1,
    validation_error: null,
    refresh_status: IntegrationStatusEnum.AVAILABLE,
    last_refreshed_at: mockDate.daysAgo1,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: mockDate.daysAgo3,
    updated_at: mockDate.daysAgo1,
    created_by: MOCK_USER_1_REF,
    labels: {},
  },
]
