# Generated By: Claude Code (Claude Opus 4.6)
"""Check for Python modules that are not imported by any other module.

Finds modules in src/syntara/ with no direct import from any other module in
the codebase. Compares against a pattern-based allowlist in
tools/ci/known_orphan_modules.json. Exits non-zero if new orphans are found.

Usage:
    uv run python tools/ci/check_orphan_modules.py
"""

from __future__ import annotations

import fnmatch
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = ROOT / "src"
SYNTARA_DIR = SRC_DIR / "syntara"
ALLOWLIST_PATH = Path(__file__).parent / "known_orphan_modules.json"

RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RESET = "\033[0m"

SKIP_DIRS = {"__pycache__", ".mypy_cache", ".pytest_cache"}


def get_source_files() -> list[Path]:
    """Get all .py files in src/syntara/ excluding __init__.py and tests."""
    files: list[Path] = []
    for py_file in sorted(SYNTARA_DIR.rglob("*.py")):
        if any(d in py_file.parts for d in SKIP_DIRS):
            continue
        if py_file.name == "__init__.py":
            continue
        rel = str(py_file.relative_to(SRC_DIR))
        if "test" in rel.lower():
            continue
        files.append(py_file)
    return files


def file_to_module(py_file: Path) -> str:
    """Convert file path to dotted module name relative to src/."""
    return ".".join(py_file.relative_to(SRC_DIR).with_suffix("").parts)


def scan_imports() -> dict[str, set[str]]:
    """Scan all .py files in src/ for import statements. Returns module -> set of importing files."""
    imports: dict[str, set[str]] = {}

    for py_file in sorted(SRC_DIR.rglob("*.py")):
        if any(d in py_file.parts for d in SKIP_DIRS):
            continue
        if "test" in str(py_file.relative_to(SRC_DIR)).lower():
            continue

        file_module = file_to_module(py_file)
        file_pkg_parts = file_module.rsplit(".", 1)[0].split(".") if "." in file_module else []

        try:
            content = py_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        # Absolute imports: from syntara.X.Y import ... or import syntara.X.Y
        for match in re.finditer(r"from\s+(syntara\.[a-z_][a-z0-9_.]*)\s+import", content):
            module = match.group(1)
            imports.setdefault(module, set()).add(str(py_file))

        for match in re.finditer(r"import\s+(syntara\.[a-z_][a-z0-9_.]*)", content):
            module = match.group(1)
            imports.setdefault(module, set()).add(str(py_file))

        # Relative imports: from .X import ...
        if file_pkg_parts:
            for match in re.finditer(r"from\s+\.([a-z_][a-z0-9_.]*)\s+import", content):
                resolved = ".".join(file_pkg_parts) + "." + match.group(1)
                imports.setdefault(resolved, set()).add(str(py_file))

    return imports


def load_allowlist() -> list[str]:
    """Load glob patterns from allowlist JSON.

    Supports both list format (["pattern", ...]) and dict format
    ({"pattern": "reason", ...}) for the "patterns" key.
    """
    if not ALLOWLIST_PATH.exists():
        print(f"{YELLOW}Warning: no allowlist at {ALLOWLIST_PATH}, all orphans will be reported{RESET}")
        return []

    with ALLOWLIST_PATH.open() as f:
        data = json.load(f)
    patterns = data.get("patterns", [])
    if isinstance(patterns, dict):
        return list(patterns.keys())
    return patterns


def is_allowed(module_path: str, patterns: list[str]) -> bool:
    """Check if a module path (relative to src/) matches any allowlist pattern."""
    return any(fnmatch.fnmatch(module_path, pattern) for pattern in patterns)


def main() -> int:
    """Check for orphan modules not covered by the allowlist."""
    source_files = get_source_files()
    all_imports = scan_imports()
    patterns = load_allowlist()

    orphans: list[tuple[str, str]] = []
    allowed_orphans: list[tuple[str, str]] = []

    for py_file in source_files:
        module = file_to_module(py_file)
        if module in all_imports:
            continue

        rel_path = str(py_file.relative_to(SRC_DIR))
        if is_allowed(rel_path, patterns):
            allowed_orphans.append((rel_path, module))
        else:
            orphans.append((rel_path, module))

    total_orphans = len(orphans) + len(allowed_orphans)
    allowed_count = len(allowed_orphans)
    new_count = len(orphans)
    print(
        f"Scanned {len(source_files)} modules, found {total_orphans} orphans ({allowed_count} allowed, {new_count} new)"
    )

    if orphans:
        print(f"\n{RED}Found {len(orphans)} NEW orphan module(s) not in allowlist:{RESET}")
        for rel_path, module in sorted(orphans):
            print(f"  {RED}{rel_path}{RESET}  ({module})")
        print(f"\nTo resolve: import the module, remove it, or add a pattern to {ALLOWLIST_PATH}")
        return 1

    print(f"{GREEN}All orphan modules match known allowlist patterns.{RESET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
