# Generated By: Claude Code (Claude Opus 4.6)
"""Check for new import cycles by comparing pyan3 output against a known baseline.

Reads pyan3 --cycles output from stdin, deduplicates cycle permutations into
unique edges (frozensets of adjacent module pairs), then compares against the
known baseline in tools/ci/known_import_cycles.json. Exits non-zero if any
new cycle edges are found.

Usage:
    uv run pyan3 --module-level --cycles ... 2>/dev/null | uv run python tools/ci/check_import_cycles.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

BASELINE_PATH = Path(__file__).parent / "known_import_cycles.json"

RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RESET = "\033[0m"

# Matches pyan3 cycle lines like: ('syntara.aap.error_handlers', 'syntara.aap.exceptions', ...)
CYCLE_PATTERN = re.compile(r"\(\s*'([^']+)'(?:\s*,\s*'([^']+)')*\s*\)")


def parse_cycles(stdin_text: str) -> list[tuple[str, ...]]:
    """Parse pyan3 --cycles output into list of cycle tuples."""
    min_cycle_length = 2
    cycles: list[tuple[str, ...]] = []
    for raw_line in stdin_text.splitlines():
        stripped = raw_line.strip()
        if not stripped.startswith("("):
            continue
        modules = re.findall(r"'([^']+)'", stripped)
        if len(modules) >= min_cycle_length:
            cycles.append(tuple(modules))
    return cycles


def extract_edges(cycles: list[tuple[str, ...]]) -> set[frozenset[str]]:
    """Extract unique undirected edges from cycle tuples.

    Each cycle (A, B, C, A) contains edges A-B, B-C, C-A. We store them as
    frozensets so direction doesn't matter and duplicates collapse naturally.
    """
    edges: set[frozenset[str]] = set()
    for cycle in cycles:
        members = cycle[:-1] if len(cycle) > 1 and cycle[0] == cycle[-1] else cycle
        for i in range(len(members)):
            edge = frozenset({members[i], members[(i + 1) % len(members)]})
            edges.add(edge)
    return edges


def load_baseline() -> set[frozenset[str]]:
    """Load known cycle edges from baseline JSON."""
    if not BASELINE_PATH.exists():
        print(f"{YELLOW}Warning: no baseline file at {BASELINE_PATH}, treating all cycles as new{RESET}")
        return set()

    with BASELINE_PATH.open() as f:
        data = json.load(f)

    known: set[frozenset[str]] = set()
    for entry in data.get("known_edges", []):
        known.add(frozenset(entry))
    return known


def main() -> int:
    """Check for new import cycles not in the known baseline."""
    stdin_text = sys.stdin.read()

    if not stdin_text.strip() or "no import cycles" in stdin_text.lower():
        print(f"{GREEN}No import cycles detected.{RESET}")
        return 0

    cycles = parse_cycles(stdin_text)
    if not cycles:
        print(f"{GREEN}No import cycles detected.{RESET}")
        return 0

    detected_edges = extract_edges(cycles)
    known_edges = load_baseline()
    new_edges = detected_edges - known_edges

    print(f"Detected {len(detected_edges)} unique cycle edges ({len(cycles)} raw cycle permutations)")
    print(f"Known baseline: {len(known_edges)} edges")

    if new_edges:
        print(f"\n{RED}Found {len(new_edges)} NEW import cycle edge(s) not in baseline:{RESET}")
        for edge in sorted(new_edges, key=lambda e: sorted(e)):
            modules = sorted(edge)
            print(f"  {RED}{modules[0]} <-> {modules[1]}{RESET}")
        print(f"\nTo resolve: fix the circular import, or add to {BASELINE_PATH}")
        return 1

    print(f"{GREEN}All detected cycles match known baseline.{RESET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
