---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{source_url}}?rev={{revision}}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "pull_request" && target_branch == "devel" &&
      (files.all.exists(x, x.startsWith("frontend/") && !x.endsWith(".md") && x != "LICENSE") ||
      ".tekton/ansible-automation-orchestrator-ui-devel-pull-request.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ansible-automation-orchestrator-devel
    appstudio.openshift.io/component: ansible-automation-orchestrator-ui-devel
    pipelines.appstudio.openshift.io/type: build
  name: ansible-automation-orchestrator-ui-devel-on-pull-request
  namespace: nexus-tenant
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-ui-rhel9:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: frontend/packages/syntara-ui/Containerfile.konflux
    - name: path-context
      value: frontend
    - name: build-args
      value:
        - DESCRIPTION_LABEL=Syntara UI
        - REDHAT_COMPONENT=ansible-automation-orchestrator-ui-container
        - IMAGE_NAME=ansible-automation-platform/ansible-automation-orchestrator-ui-rhel9
        - MAINTAINER=Ansible Automation Platform Productization Team
        - DOWNSTREAM_OVERRIDE=quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-downstream-override@sha256:2c388549b6eb79f56a83468f60f821319ed48602fbd5b609f3af1508cb7e918c
        - BRANDING=true
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
    - name: hermetic
      value: 'true'
    - name: prefetch-input
      value: '{"type": "npm", "path": "frontend"}'
  pipelineRef:
    params:
      - name: name
        value: container
      - name: bundle
        value: quay.io/aap-ci/tekton-catalog/pipeline/build/container:0.2@sha256:401c54b0f4afcdb48e423de491a96a5d2155f4a781f8d7922097542b4ee7d6a7
      - name: kind
        value: pipeline
      - name: secret
        value: quay-aap-ci-viewer
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-ansible-automation-orchestrator-ui-devel
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
