---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{source_url}}?rev={{revision}}'
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "pull_request" && target_branch == "devel" &&
      (files.all.exists(x, x.startsWith("backend/")) ||
      ".tekton/ansible-automation-orchestrator-backend-devel-pull-request.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ansible-automation-orchestrator-devel
    appstudio.openshift.io/component: ansible-automation-orchestrator-backend-devel
    pipelines.appstudio.openshift.io/type: build
  name: ansible-automation-orchestrator-backend-devel-on-pull-request
  namespace: nexus-tenant
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-backend-rhel9:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: backend/containers/syntara/Containerfile
    - name: path-context
      value: backend
    - name: build-args
      value:
        - CONTAINER_IMAGE_VERSION={{revision}}
        - DOWNSTREAM_OVERRIDE=quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-downstream-override@sha256:2c388549b6eb79f56a83468f60f821319ed48602fbd5b609f3af1508cb7e918c
        - BRANDING=true
        - BUILDER_IMAGE=registry.redhat.io/ansible-automation-platform/uv-builder-rhel9:latest@sha256:bdd64fcb4597cfb665c15c4b4841ded098baa26dce1f544b4dbd17a575b8984a
    - name: build-platforms
      value:
        - linux-c8xlarge/amd64
        - linux-c8xlarge/arm64
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '[{"type": "pip", "path": "backend"}, {"type": "rpm", "path": "backend"}, {"type": "generic", "path": "backend"}]'
    - name: prefetch-mode
      value: permissive
    - name: additional-secret
      value: nexus-segment-write-keys
  pipelineRef:
    params:
      - name: name
        value: container
      - name: bundle
        value: quay.io/aap-ci/tekton-catalog/pipeline/build/container:0.2@sha256:401c54b0f4afcdb48e423de491a96a5d2155f4a781f8d7922097542b4ee7d6a7
      - name: kind
        value: pipeline
      - name: secret
        value: quay-aap-ci-viewer
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-ansible-automation-orchestrator-backend-devel
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
