---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{source_url}}?rev={{revision}}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "pull_request" && target_branch == "early-access" &&
      (files.all.exists(x, x.startsWith("frontend/")) || files.all.exists(x, x.startsWith("backend/")) ||
      ".tekton/automation-orchestrator-ui-tests-early-access-pull-request.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ansible-automation-orchestrator-early-access
    appstudio.openshift.io/component: ansible-automation-orchestrator-ui-early-access
    pipelines.appstudio.openshift.io/type: test
  name: automation-orchestrator-ui-tests-early-access-pull-request
  namespace: nexus-tenant
spec:
  timeouts:
    pipeline: "10h"
    tasks: "8h"
    finally: "2h"
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: pipeline-github-org
      value: '{{repo_owner}}'
    - name: pipeline-github-repo
      value: '{{repo_name}}'
    - name: pipeline-github-pr-revision
      value: '{{revision}}'
    - name: pipeline-github-pr-number
      value: '{{pull_request_number}}'
  pipelineRef:
    params:
      - name: name
        value: ao-ui-tests
      - name: bundle
        value: quay.io/aap-ci/tekton-catalog/pipeline/test/ao-ui-tests:0.1@sha256:554162895215bc46aed2de97701340a3202b300962e5b7157914f80504f905c4
      - name: kind
        value: pipeline
      - name: secret
        value: quay-aap-ci-viewer
    resolver: bundles

  taskRunTemplate:
    serviceAccountName: konflux-integration-runner

  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
