#!/usr/bin/env python3
"""Find user-visible features in a commit range, from structural evidence.

Generated By: Claude Code (claude-opus-5[1m])

A feature is new functionality a user of a *deployed* instance can reach. The
only evidence this script accepts for that is a new surface appearing in shipped
product code:

  API   a new endpoint handler, or a new path/operation in an OpenAPI schema
  UI    a new route, a new tab, a new menu action, or a new dialog

Deliberately NOT evidence:

  * The ``feat`` conventional-commit type. It is author-declared intent, and the
    type list is short enough that ``feat`` absorbs anything that is not clearly
    a fix or a chore. Declared-feat commits with no structural signal are
    reported separately for a human to judge, never counted.
  * A new ``.github/workflows/*.yml``. That is CI. It changes the pipeline, not
    the product.
  * New classes or new source files. Refactors add files constantly.
  * Making an existing-but-inert control actually work. The control was already
    advertised to the user, so that is a bug fix.

Every detector is scoped to shipped project paths and skips tests, stories and
Storybook config -- without that scoping the UI detectors fire on story files and
test fixtures (measured: the ``<Tab eventKey`` detector false-positives on a
Storybook upgrade, and a menu *restyle* looks identical to a new menu *action*
if you match anywhere in the line rather than on the JSX element).

Usage:
    ./find_features.py <rev-range> [--json|--markdown]
    ./find_features.py --selfcheck
"""

import argparse
import json
import re
import subprocess
import sys
from collections import Counter, OrderedDict

# --- message parsing -------------------------------------------------------

SUBJECT_TYPE = re.compile(r"^\s*(?P<type>[a-zA-Z]+)(?:\((?P<scope>[^)]*)\))?!?:")
BULLET_TYPE = re.compile(r"^\s*\*\s*(?P<type>[a-zA-Z]+)(?:\([^)]*\))?!?:")
PR_NUM = re.compile(r"\(#(\d+)\)\s*$")
JIRA_PREFIXES = ("ANSTRAT", "AAP")
JIRA = re.compile(r"\b(" + "|".join(JIRA_PREFIXES) + r")-(\d+)\b", re.IGNORECASE)
TRAILER = re.compile(
    r"^(Co-authored-by|Co-Authored-By|Signed-off-by|Assisted-by|Fixes|Resolves"
    r"|Closes|See|https?:|-{3,}|#)",
    re.IGNORECASE,
)

# --- what counts as shipped project code -----------------------------------

# The backend package a deployment runs (its OpenAPI schemas are the API contract)
# and the UI app it serves. Everything else -- .github, .tekton, backend/scripts,
# backend/tools, the generated api_client and syntara-contracts SDKs, and
# syntara-mock-api (a dev-only fake) -- never reaches an instance.
# Which half of the stack a path belongs to. SHIPPED_PATH is derived from these
# two so "where shipped code lives" has exactly one definition.
BACKEND_PREFIX = r"backend/src/syntara/"
FRONTEND_PREFIX = r"frontend/packages/syntara-ui/src/"
BACKEND_PATH = re.compile("^" + BACKEND_PREFIX)
FRONTEND_PATH = re.compile("^" + FRONTEND_PREFIX)
SHIPPED_PATH = re.compile(f"^({BACKEND_PREFIX}|{FRONTEND_PREFIX})")
NON_RUNTIME = re.compile(
    r"\.(test|spec|stories)\.[jt]sx?$"
    r"|(^|/)(tests?|e2e|__tests__|__mocks__|\.storybook)/"
    r"|(^|/)test_[^/]+\.py$"
)

# --- surface detectors -----------------------------------------------------
#
# Each matches an ADDED line in a shipped project file. Anchored at the start of
# the JSX element or decorator on purpose: matching mid-line turns a restyle into
# a false "new action".

DETECTORS = OrderedDict(
    [
        ("api_endpoint", (re.compile(r"^\+\s*@(?:app|router)\.(get|post|put|patch|delete)\s*\("), "new API endpoint handler")),
        ("api_path", (re.compile(r"^\+  (/[^:\s]*):\s*$"), "new OpenAPI path")),
        ("api_operation", (re.compile(r"^\+    (get|post|put|patch|delete):\s*$"), "new OpenAPI operation on an existing path")),
        ("ui_route", (re.compile(r"^\+.*\bcreateRoute\("), "new UI route")),
        ("ui_tab", (re.compile(r"^\+\s*<\w*Tab\s+eventKey="), "new UI tab")),
        ("ui_menu_action", (re.compile(r"^\+\s*<\w*(MenuItem|DropdownItem)\b"), "new UI menu action")),
        ("ui_dialog", (re.compile(r"^\+\s*<\w*Modal\b"), "new UI dialog")),
    ]
)

API_SIGNALS = {"api_endpoint", "api_path", "api_operation"}

# OpenAPI detectors are only meaningful inside a spec file.
SPEC_FILE = re.compile(r"schemas/.*openapi.*\.(ya?ml|json)$")

# A runtime settings catalog entry is a real new capability but sits below the
# chosen UI floor (it is a form field, not an invocable action), so it flags for
# review rather than counting.
SETTINGS_FILE = re.compile(r"settings/(catalog|definitions|registry)")
SETTING_KEY = re.compile(r"^\+\s*(key|name)\s*=\s*[\"'][a-z0-9_.]+[\"']")

# Buckets for commits with no surface delta, by what they touched. Ordered:
# first exclusive match wins, so a commit confined to tests is TEST_ONLY even
# though tests live under a product path.
CI_PATH = re.compile(r"^(\.github/|\.tekton/|.*Containerfile.*|.*compose\.ya?ml$"
                     r"|Makefile$|renovate\.json$)")

SUPPORT_BUCKETS = [
    ("TEST_ONLY", NON_RUNTIME),
    ("CI_ONLY", CI_PATH),
    ("DEPS_ONLY", re.compile(r"(package(-lock)?\.json|uv\.lock|pyproject\.toml"
                             r"|requirements[^/]*\.txt|\.lock)$")),
    ("DOCS_ONLY", re.compile(r"\.md$|^docs/")),
]

MIGRATION = re.compile(r"(alembic|migrations)/versions/.*\.py$")

AREA_RULES = [
    ("ci", CI_PATH),
    ("backend", re.compile(r"^backend/")),
    ("frontend", re.compile(r"^frontend/")),
    ("docs", re.compile(r"^(docs/|.*\.md$)")),
]


class GitError(RuntimeError):
    """A git invocation failed; carries git's own stderr for the user."""


def sh(args):
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        raise GitError(
            f"git exited {result.returncode}: {' '.join(args)}\n"
            + (result.stderr.strip() or "(no stderr)")
        )
    return result.stdout


def is_shipped(path):
    return bool(SHIPPED_PATH.match(path)) and not NON_RUNTIME.search(path)


def areas(paths):
    hits = Counter()
    for path in paths:
        for name, rx in AREA_RULES:
            if rx.match(path):
                hits[name] += 1
                break
    return [n for n, _ in hits.most_common()]


def first_paragraph(lines):
    """Prose attached to the first squashed sub-commit.

    A squash body is `* <subject>` bullets, each optionally followed by prose.
    Only prose before the SECOND bullet describes the headline change; anything
    later belongs to a follow-up fix in the same PR. Returns "" when the first
    bullet carries no prose -- an empty summary beats a wrong one.
    """
    out = []
    bullets = 0
    for line in lines[1:]:
        stripped = line.strip()
        if BULLET_TYPE.match(line) or stripped.startswith("* "):
            bullets += 1
            if bullets >= 2:
                break
            continue
        if not stripped:
            if out:
                break
            continue
        if TRAILER.match(stripped):
            if out:
                break
            continue
        out.append(stripped)
    return " ".join(out)


def scan_diff(sha):
    """Net new surface per signal, inside shipped project files.

    Counts additions minus removals. Moving existing code into a new file adds
    and removes the same surface, so a pure extraction refactor nets zero --
    without this, extracting a kebab menu into its own module looks exactly like
    adding a dozen new menu actions.
    """
    out = sh(["git", "show", "--pretty=format:", "--unified=0", sha])
    added, removed = Counter(), Counter()
    setting_added = False
    path = None
    old_path = None
    for line in out.splitlines():
        # A file header is a "--- a/<old>" / "+++ b/<new>" pair. A deletion has
        # "+++ /dev/null", so taking the path only from the "+++" side leaves the
        # deleted file's removed lines attributed to whatever file came before it.
        if line.startswith("--- "):
            side = line[4:]
            old_path = None if side == "/dev/null" else side[2:] if side.startswith("a/") else side
            continue
        if line.startswith("+++ "):
            side = line[4:]
            path = old_path if side == "/dev/null" else side[2:] if side.startswith("b/") else side
            continue
        if line.startswith(("diff ", "index ", "@@")):
            continue
        if path is None or not line[:1] in "+-":
            continue
        if not is_shipped(path):
            continue
        # N0: scoped to shipped code, so a fixture under a settings/ path cannot
        # masquerade as a real catalog entry.
        if line[0] == "+" and SETTINGS_FILE.search(path) and SETTING_KEY.match(line):
            setting_added = True
        bucket = added if line[0] == "+" else removed
        probe = line if line[0] == "+" else "+" + line[1:]
        for name, (rx, _) in DETECTORS.items():
            if name in ("api_path", "api_operation") and not SPEC_FILE.search(path):
                continue
            if rx.match(probe):
                bucket[name] += 1
    hits, gone = Counter(), Counter()
    for name in DETECTORS:
        net = added[name] - removed[name]
        if net > 0:
            hits[name] = net
        elif net < 0:
            gone[name] = -net
    return hits, gone, setting_added


def split_parents_and_message(raw_lines):
    """Split `git show -s --pretty=format:%P%n%B` output.

    %P is always exactly one line: space-separated parent shas, empty for a root
    commit, two or more for a merge. Everything after it is the message.
    """
    if not raw_lines:
        return [], []
    return raw_lines[0].split(), raw_lines[1:]


def decide_verdict(*, hits, gone, declared_feat, setting_added, shipped,
                   spec_touched, paths, subject_type):
    """Pick one headline verdict. Rules are tried in PRECEDENCE order.

    Separated from classify() so the ordering can be exercised directly -- it is
    the one piece of logic here where changing a branch silently reshuffles every
    bucket in the report.
    """
    if hits:
        return "FEATURE", [f"{DETECTORS[n][1]} (net +{c})" for n, c in hits.items()]
    if gone:
        return "SURFACE_REMOVED", [
            f"{DETECTORS[n][1].replace('new ', 'removed ')} (net -{c})" for n, c in gone.items()
        ]
    if declared_feat and not shipped:
        return "NOTHING_SHIPPED", ["declared feat, but no shipped project file changed"]
    if declared_feat or setting_added:
        reasons = []
        if declared_feat:
            reasons.append("declared feat, no new API or UI surface found")
        if setting_added:
            reasons.append("adds a runtime settings entry (a capability, but below the UI floor)")
        return "FEATURE_CANDIDATE", reasons
    if shipped and spec_touched:
        return "API_CONTRACT_CHANGE", [
            "OpenAPI schema changed with no operation added or removed: a field, "
            "enum, or description moved"
        ]
    if shipped:
        return "INTERNAL_CHANGE", [
            f"changes shipped code, surface unchanged; declared `{subject_type}`"
        ]
    for name, rx in SUPPORT_BUCKETS:
        if paths and all(rx.search(p) for p in paths):
            return name, [f"every changed path matches {name.split('_')[0].lower()}"]
    return "MIXED_SUPPORT", ["no shipped project file touched"]


def classify(sha):
    # %P is the parent list: one sha for an ordinary or squashed commit, two or
    # more for a merge. Fetched with the message so the claim that a range is all
    # squashes is measured rather than asserted.
    parents, lines = split_parents_and_message(
        sh(["git", "show", "-s", "--pretty=format:%P%n%B", sha]).splitlines()
    )
    message = "\n".join(lines)
    subject = lines[0] if lines else ""

    m = SUBJECT_TYPE.match(subject)
    subject_type = m.group("type").lower() if m else ""
    scope = (m.group("scope") or "") if m else ""

    bullet_types = OrderedDict()
    for line in lines[1:]:
        bm = BULLET_TYPE.match(line)
        if bm:
            bullet_types[bm.group("type").lower()] = True
    declared_feat = subject_type == "feat" or "feat" in bullet_types

    files = []
    for line in sh(["git", "show", "--pretty=format:", "--name-status", "-M", sha]).splitlines():
        if line.strip():
            parts = line.split("\t")
            files.append((parts[0][0], parts[-1]))
    paths = [p for _, p in files]
    shipped = [p for p in paths if is_shipped(p)]

    backend = any(BACKEND_PATH.match(p) for p in shipped)
    frontend = any(FRONTEND_PATH.match(p) for p in shipped)
    layer = ("both" if backend and frontend else
             "backend" if backend else "frontend" if frontend else "none")
    spec_touched = any(SPEC_FILE.search(p) for p in shipped)

    hits, gone, setting_added = scan_diff(sha)
    evidence = [f"{DETECTORS[n][1]} (net +{c})" for n, c in hits.items()]

    verdict, reasons = decide_verdict(
        hits=hits,
        gone=gone,
        declared_feat=declared_feat,
        setting_added=setting_added,
        shipped=bool(shipped),
        spec_touched=spec_touched,
        paths=paths,
        subject_type=subject_type,
    )

    flags = []
    if hits:
        flags.append("surface+")
    if gone:
        flags.append("surface-")
    if spec_touched:
        flags.append("spec")
    if any(MIGRATION.search(p) for p in paths):
        flags.append("db")
    if declared_feat:
        flags.append("feat")

    pr = PR_NUM.search(subject)
    return {
        "flags": flags,
        "parents": len(parents),
        "sha": sha,
        "short": sha[:9],
        "subject": subject,
        "subject_type": subject_type or "(none)",
        "scope": scope,
        "declared_feat": declared_feat,
        "pr": int(pr.group(1)) if pr else None,
        "jira": sorted({f"{k.upper()}-{n}" for k, n in JIRA.findall(message)}),
        "signals": dict(hits),
        "kind": "api" if API_SIGNALS & set(hits) else ("ui" if hits else ""),
        "removed": dict(gone),
        "setting_added": setting_added,
        "migration": any(MIGRATION.search(p) for p in paths),
        "layer": layer,
        "api_spec_touched": spec_touched,
        "shipped_files": len(shipped),
        "files_changed": len(files),
        "areas": areas(paths),
        "summary": first_paragraph(lines),
        "verdict": verdict,
        "reasons": reasons,
    }


# --- output ----------------------------------------------------------------


def fmt_flags(flags):
    return " ".join(f"`{f}`" for f in flags) if flags else "-"


def link_pr(pr, repo_url):
    return f"[#{pr}]({repo_url}/pull/{pr})" if pr else "-"


def link_jira(keys, jira_url):
    return ", ".join(f"[{k}]({jira_url}/{k})" for k in keys) if keys else "-"


# The verdict is a single headline, chosen by the first rule that matches. Most
# commits carry several facts at once (measured: 43 of 125 in the reference range
# hold three or more), so a headline alone is lossy -- FLAG_LABELS below carry the
# rest so nothing is hidden by the ordering.
#
# Order is evidence-first: an observed surface change outranks a claimed one, and
# both outrank "what kind of file did this touch".
PRECEDENCE = [
    ("FEATURE", "a surface was added"),
    ("SURFACE_REMOVED", "a surface was removed"),
    ("NOTHING_SHIPPED", "`feat` claimed, nothing shipped changed"),
    ("FEATURE_CANDIDATE", "`feat` claimed (or a setting added), shipped code changed"),
    ("API_CONTRACT_CHANGE", "OpenAPI schema moved, no operation added or removed"),
    ("INTERNAL_CHANGE", "shipped code changed, surface unchanged"),
    ("TEST_ONLY", "nothing shipped; every path is a test"),
    ("CI_ONLY", "nothing shipped; every path is CI or build config"),
    ("DEPS_ONLY", "nothing shipped; every path is a dependency manifest"),
    ("DOCS_ONLY", "nothing shipped; every path is documentation"),
    ("MIXED_SUPPORT", "nothing shipped; spans several support areas"),
]

# Facts worth showing on every row. Deliberately excludes the high-frequency,
# low-signal ones (touches tests, touches CI, touches docs): those already decide
# the support buckets, and as badges they would fire on nearly every line.
FLAG_LABELS = {
    "surface+": "added an API or UI surface",
    "surface-": "removed one",
    "spec": "moved the OpenAPI schema",
    "db": "carries a database migration",
    "feat": "author declared `feat`",
}

VERDICT_MEANING = {
    "FEATURE": "adds a user-visible API or UI surface",
    "SURFACE_REMOVED": "removes one -- user-visible, but a subtraction",
    "FEATURE_CANDIDATE": "declared `feat` and changed shipped code, but no surface delta found -- human call",
    "NOTHING_SHIPPED": "declared `feat`, but no shipped file changed at all",
    "API_CONTRACT_CHANGE": "OpenAPI schema moved, but no operation added or removed -- a field, enum, or description",
    "INTERNAL_CHANGE": "changes shipped code with the API and UI surface unchanged",
    "TEST_ONLY": "every changed path is a test, spec, story, or fixture",
    "CI_ONLY": "every changed path is CI, pipeline, container, or build config",
    "DEPS_ONLY": "every changed path is a dependency manifest or lockfile",
    "DOCS_ONLY": "every changed path is documentation",
    "MIXED_SUPPORT": "touches no shipped code, but spans more than one support area",
}


def emit_markdown(rows, args):
    features = [r for r in rows if r["verdict"] == "FEATURE"]
    review = [r for r in rows if r["verdict"] == "FEATURE_CANDIDATE"]
    notprod = [r for r in rows if r["verdict"] == "NOTHING_SHIPPED"]
    gone = [r for r in rows if r["verdict"] == "SURFACE_REMOVED"]
    counts = Counter(r["verdict"] for r in rows)
    w = sys.stdout.write

    w(f"# Features added between `{args.rev_range}`\n\n")
    rest = len(rows) - len(features) - len(gone) - len(review) - len(notprod)
    w(f"{len(rows)} commits in range. **{len(features)} add a user-visible surface** and "
      f"are features on the evidence. {len(gone)} remove{'s' if len(gone) == 1 else ''} one. "
      f"{len(review)} declared "
      f"themselves features but show no surface delta and need a human call; {len(notprod)} "
      f"more declared features change no shipped file at all. The remaining {rest} are "
      "classified below by what they touched, so nothing sits in an unexplained pile.\n\n")

    w("## What counts as a feature here\n\n")
    w("A feature is new functionality a user of a **deployed** instance can reach. The\n"
      "only accepted evidence is a new surface appearing in shipped project code:\n\n")
    w("| Surface | Detected as |\n|---|---|\n")
    for name, (_, label) in DETECTORS.items():
        w(f"| {label} | `{name}` |\n")
    w("\n")
    w("Scoped to `backend/src/syntara/` and `frontend/packages/syntara-ui/src/`, skipping\n"
      "tests, stories and Storybook config. That scoping is load-bearing, not tidiness:\n"
      "unscoped, the tab detector fires on a Storybook upgrade, and a menu *restyle* is\n"
      "indistinguishable from a new menu *action*.\n\n")
    w("**Explicitly not evidence:**\n\n")
    w("1. The `feat` commit type -- author-declared intent, and with so few conventional\n"
      "   types to choose from `feat` absorbs whatever is not plainly a fix or a chore.\n"
      "   Declared-feat commits are listed for review, never counted.\n")
    w("2. A new `.github/workflows/*.yml`. That is CI, not the deployed project.\n")
    w("3. New classes or new source files -- refactors add those constantly.\n")
    w("4. Making an existing-but-inert control work. The control was already advertised\n"
      "   to the user, so that is a bug fix.\n\n")
    w("Rerun:\n\n```bash\n")
    w("python3 scripts/explore/find_features.py --selfcheck   # detector asserts\n")
    w(f"python3 scripts/explore/find_features.py {args.rev_range} --markdown\n")
    w("```\n\n")

    w("## How a verdict is chosen\n\n")
    multi = sum(1 for r in rows if len(r["flags"]) > 1)
    w(f"A commit is often several things at once: {multi} of {len(rows)} here carry more\n"
      "than one notable fact. So each gets one **verdict** -- the first rule below that\n"
      "matches -- plus **flags**, which record every notable fact regardless of which rule\n"
      "won. The verdict is for grouping and counting; the flags are so the ordering never\n"
      "hides anything.\n\n")
    w("Rules are tried in this order, evidence before claims:\n\n")
    w("| # | Verdict | Matches when |\n|---|---------|-------------|\n")
    for i, (verdict, when) in enumerate(PRECEDENCE, 1):
        w(f"| {i} | `{verdict}` | {when} |\n")
    w("\nFlags, shown on every row and independent of the verdict:\n\n")
    w("| Flag | Means |\n|------|-------|\n")
    for flag, meaning in FLAG_LABELS.items():
        w(f"| `{flag}` | {meaning} |\n")
    w("\nSo `#232` reads `API_CONTRACT_CHANGE`-adjacent but wins the `FEATURE_CANDIDATE`\n"
      "headline on its `feat` claim, while its `spec` flag still records that the schema\n"
      "moved. Neither fact is lost to the ordering.\n\n")

    w("## Features\n\n")
    if not features:
        w("None.\n\n")
    else:
        w("| # | PR | Jira | Commit | Kind | Subject | Evidence |\n")
        w("|---|----|------|--------|------|---------|----------|\n")
        for i, r in enumerate(features, 1):
            w(f"| {i} | {link_pr(r['pr'], args.repo_url)} | {link_jira(r['jira'], args.jira_url)} "
              f"| `{r['short']}` | {r['kind'].upper()} | {r['subject']} | {'; '.join(r['reasons'])} |\n")
        w("\n### Detail\n\n")
        for i, r in enumerate(features, 1):
            w(f"**{i}. {r['subject']}**\n\n")
            w(f"- PR: {link_pr(r['pr'], args.repo_url)} &middot; Jira: "
              f"{link_jira(r['jira'], args.jira_url)} &middot; commit `{r['short']}` "
              f"&middot; {r['files_changed']} file(s), {r['shipped_files']} shipped\n")
            w(f"- Evidence: {'; '.join(r['reasons'])}\n")
            if r["summary"]:
                w(f"- Commit message says: {r['summary']}\n")
            w("\n")

    if gone:
        w("## Surface removed\n\n")
        w("User-visible, but a subtraction rather than an addition. Worth seeing next to\n"
          "the additions when auditing a release.\n\n")
        w("| PR | Jira | Commit | Subject | Evidence |\n|----|------|--------|---------|----------|\n")
        for r in gone:
            w(f"| {link_pr(r['pr'], args.repo_url)} | {link_jira(r['jira'], args.jira_url)} "
              f"| `{r['short']}` | {r['subject']} | {'; '.join(r['reasons'])} |\n")
        w("\n")

    w("## Feature candidates\n\n")
    w("Each says `feat` (in the subject or a squashed bullet) and changes shipped project\n"
      "code, but adds no new route, tab, menu action, dialog, endpoint, or OpenAPI\n"
      "operation. Most will be polish, refactors, or fixes to already-advertised\n"
      "behaviour; a few may be real features the detectors cannot see. Human call.\n\n"
      "The *API contract moved* column is shown because this verdict is decided before\n"
      "`API_CONTRACT_CHANGE`; without the column, a candidate that also reshaped the\n"
      "OpenAPI schema would hide that fact behind the precedence order.\n\n")
    w("| PR | Jira | Commit | Layer | Shipped files | API contract moved | Subject |\n")
    w("|----|------|--------|-------|---------------|--------------------|--------|\n")
    for r in review:
        w(f"| {link_pr(r['pr'], args.repo_url)} | {link_jira(r['jira'], args.jira_url)} "
          f"| `{r['short']}` | {r['layer']} | {r['shipped_files']} "
          f"| {'yes' if r['api_spec_touched'] else 'no'} | {r['subject']} |\n")
    w("\n")

    w("## Declared a feature, nothing shipped\n\n")
    w("`feat` commits that touch no shipped project file -- CI, build, tooling, or docs\n"
      "only. Not features by any reading; listed so the `feat` label is accounted for.\n\n")
    w("| PR | Jira | Commit | Subject |\n|----|------|--------|---------|\n")
    for r in notprod:
        w(f"| {link_pr(r['pr'], args.repo_url)} | {link_jira(r['jira'], args.jira_url)} "
          f"| `{r['short']}` | {r['subject']} |\n")
    w("\n")

    w("## Everything else, by what it touched\n\n")
    w("No commit is left unclassified. Each verdict below is decided by the paths a commit\n"
      "changed, not by its label.\n\n")
    w("| Verdict | Commits | Means |\n|---------|---------|-------|\n")
    for verdict, n in counts.most_common():
        w(f"| `{verdict}` | {n} | {VERDICT_MEANING.get(verdict, '-')} |\n")
    w("\n")

    contract = [r for r in rows if r["verdict"] == "API_CONTRACT_CHANGE"]
    if contract:
        w(f"### API contract moved without a new operation ({len(contract)})\n\n")
        w("The closest thing to a feature that this run does not count. Each changed an\n"
          "OpenAPI schema without adding or removing a path or operation, so what moved was\n"
          "a field, an enum, or a description. Under the floor applied here that is not a\n"
          "feature; under the repo's own gate a new *field* is additive and would be.\n\n")
        w("| PR | Jira | Layer | Subject |\n|----|------|-------|--------|\n")
        for r in contract:
            w(f"| {link_pr(r['pr'], args.repo_url)} | {link_jira(r['jira'], args.jira_url)} "
              f"| {r['layer']} | {r['subject']} |\n")
        w("\n")

    internal = [r for r in rows if r["verdict"] == "INTERNAL_CHANGE"]
    if internal:
        w(f"### Internal changes ({len(internal)}), by layer and declared type\n\n")
        w("Shipped code changed; the API and UI surface did not. Layer comes from the paths\n"
          "touched. The declared type is the author's label -- descriptive only here, since\n"
          "nothing in this bucket is being counted as evidence either way.\n\n")
        types = [t for t, _ in Counter(r["subject_type"] for r in internal).most_common()]
        layers = [l for l, _ in Counter(r["layer"] for r in internal).most_common()]
        w("| Layer | " + " | ".join(f"`{t}`" for t in types) + " | Total |\n")
        w("|-------|" + "|".join("---" for _ in types) + "|-------|\n")
        for layer in layers:
            in_layer = [r for r in internal if r["layer"] == layer]
            by_type = Counter(r["subject_type"] for r in in_layer)
            w(f"| {layer} | " + " | ".join(str(by_type.get(t, 0)) for t in types)
              + f" | **{len(in_layer)}** |\n")
        totals = Counter(r["subject_type"] for r in internal)
        w("| **Total** | " + " | ".join(f"**{totals.get(t, 0)}**" for t in types)
          + f" | **{len(internal)}** |\n\n")

    with_mig = [r for r in rows if r["migration"]]
    if with_mig:
        w(f"### Database migrations ({len(with_mig)})\n\n")
        w("Cuts across the buckets above. Called out because a schema change is worth\n"
          "seeing when auditing what a release actually does to an instance.\n\n")
        w("| PR | Verdict | Subject |\n|----|---------|--------|\n")
        for r in with_mig:
            w(f"| {link_pr(r['pr'], args.repo_url)} | `{r['verdict']}` | {r['subject']} |\n")
        w("\n")

    jira_all = sorted({k for r in features for k in r["jira"]})
    w("## Jira keys on the features\n\n")
    if features:
        w(f"{len([r for r in features if r['jira']])} of the {len(features)} features carry a "
          f"Jira key.\n\n")
        for k in jira_all:
            w(f"- [{k}]({args.jira_url}/{k}) -- "
              f"{', '.join('#%s' % r['pr'] for r in features if k in r['jira'])}\n")
        nokey = [r for r in features if not r["jira"]]
        if nokey:
            w("\nNo Jira key in the commit message:\n\n")
            for r in nokey:
                w(f"- {link_pr(r['pr'], args.repo_url)} {r['subject']}\n")
        w("\n")

    w("## Appendix: every commit in the range, mapped to its PR\n\n")
    with_pr = [r for r in rows if r["pr"]]
    distinct = len(set(r["pr"] for r in with_pr))
    merges = [r for r in rows if r["parents"] > 1]
    single = len(rows) - len(merges)
    w(f"{len(with_pr)} of {len(rows)} commits carry a trailing `(#N)`, across {distinct} "
      f"distinct PR numbers. {single} are single-parent (squash or plain) and "
      f"{len(merges)} are merge commits.\n\n")
    if len(with_pr) == len(rows) == distinct and not merges:
        w("Every commit maps to its own PR: the correlation is 1:1 with no gaps.\n\n")
    else:
        if len(with_pr) < len(rows):
            w(f"**{len(rows) - len(with_pr)} commit(s) carry no PR suffix** and cannot be "
              "correlated from the message alone.\n\n")
        if distinct < len(with_pr):
            w(f"**{len(with_pr) - distinct} PR number(s) appear on more than one commit** -- "
              "the range is not a clean one-commit-per-PR history.\n\n")
        if merges:
            w(f"**{len(merges)} merge commit(s) present**, so the range is not purely "
              "squashed.\n\n")
    w("Oldest last.\n\n")
    w("| PR | Commit | Verdict | Flags | Jira | Subject |\n"
      "|----|--------|---------|-------|------|--------|\n")
    for r in rows:
        w(f"| {link_pr(r['pr'], args.repo_url)} | `{r['short']}` | {r['verdict']} "
          f"| {fmt_flags(r['flags'])} | {link_jira(r['jira'], args.jira_url)} | {r['subject']} |\n")
    w("\n")

    w("## Limits\n\n")
    keys = sorted({k for r in rows for k in r["jira"]})
    by_prefix = Counter(k.split("-")[0] for k in keys)
    found = ", ".join(f"`{p}` ({n} key(s))" for p, n in sorted(by_prefix.items())) or "none"
    absent = [p for p in JIRA_PREFIXES if p not in by_prefix]
    w(f"- **Jira prefixes searched:** {', '.join('`%s-NNNN`' % p for p in JIRA_PREFIXES)}. "
      f"Present in this range: {found}.")
    w(f" Not present: {', '.join('`%s`' % p for p in absent)}.\n" if absent else "\n")
    w(f"  {len([r for r in rows if r['jira']])} of {len(rows)} commits carry at least one key.\n")
    w("- **PR correlation is read off the commit subject**, the trailing `(#N)`; the\n"
      "  appendix above reports what that yielded for this range. The number is never\n"
      "  confirmed against GitHub -- no network access here -- so a wrong number typed\n"
      "  into a squash subject is reproduced as-is. PR bodies were not read either\n"
      "  (`open-prs.json` carries a `fetch_error` with an empty `prs` list), so a Jira\n"
      "  key living only in a PR description is invisible to this scan.\n")
    w("- **The UI detectors are pattern-based and will miss surfaces expressed another\n"
      "  way.** A new user action rendered as a plain `<Button>` in helper text, for\n"
      "  instance, looks like any other button. That is why the review table exists;\n"
      "  treat the feature count as a floor, not a ceiling.\n")
    w("- **A new API *field* is not counted**, only a new path or operation. An additive\n"
      "  field change would register as a feature under the repo's own OpenAPI gate\n"
      "  (`backend/scripts/openapi/check-breaking-changes.py`: *minor for additive\n"
      "  changes -- new endpoint, field, or enum value*), which is a wider bar than the\n"
      "  one applied here.\n")


def selfcheck():
    """The detectors are where a wrong answer hides. Assert them."""
    assert SUBJECT_TYPE.match("feat(ui): x (#1)").group("type") == "feat"
    assert SUBJECT_TYPE.match('Revert "chore: x"') is None
    assert BULLET_TYPE.match("* feat(workflows): add duplicate action")
    assert PR_NUM.search("feat: x (#493)").group(1) == "493"
    assert PR_NUM.search("feat: mentions (#12) mid-subject") is None
    assert {k.upper() + "-" + n for k, n in JIRA.findall("aap-1 and ANSTRAT-22")} == {"AAP-1", "ANSTRAT-22"}

    assert is_shipped("backend/src/syntara/files/router.py")
    assert is_shipped("frontend/packages/syntara-ui/src/routes/a.tsx")
    assert not is_shipped(".github/workflows/ci.yml")
    assert not is_shipped("backend/scripts/openapi/check-breaking-changes.py")
    assert not is_shipped("backend/src/api_client/x.py")
    assert not is_shipped("frontend/packages/syntara-mock-api/src/x.ts")
    assert not is_shipped("frontend/packages/syntara-ui/src/a.test.tsx")
    assert not is_shipped("frontend/packages/syntara-ui/src/a.stories.tsx")
    assert not is_shipped("backend/src/syntara/tests/test_x.py")
    # This repo keeps Alembic revisions under core/database/migrations/versions/,
    # not the default alembic/versions/.
    assert MIGRATION.search(
        "backend/src/syntara/core/database/migrations/versions/c4a7e1f93d21_x.py"
    )

    hit = lambda name, line: bool(DETECTORS[name][0].match(line))
    assert hit("api_endpoint", "+@router.delete(")
    # FastAPI routes are declared on the app as well as on a router; missing the
    # app form hid the /health removal until it was measured.
    assert hit("api_endpoint", '+@app.get("/health", tags=["Health"])')
    assert hit("api_endpoint", "+    @router.get(")
    assert not hit("api_endpoint", "-@router.get(")
    assert hit("api_path", "+  /files/{file_id}:")
    assert not hit("api_path", "+    delete:")
    assert hit("api_operation", "+    delete:")
    assert hit("ui_tab", '+              <Tab eventKey="workflows" title={<TabTitleText>W</TabTitleText>} />')
    assert hit("ui_menu_action", "+        <DuplicateMenuItem canDuplicate />")
    assert hit("ui_menu_action", "+  <DropdownItem>Delete</DropdownItem>")
    # A restyle mentions a menu item mid-line; only an added JSX element counts.
    assert not hit("ui_menu_action", "+      const label = buildMenuItemLabel(resource)")
    assert not hit("ui_menu_action", "+import { DeleteMenuItem } from './kebabMenuItems'")
    assert hit("ui_route", "+const route = createRoute({")
    assert hit("ui_dialog", "+  <Modal isOpen>")

    ps, msg = split_parents_and_message(["aaa bbb", "Merge x", "", "body"])
    assert len(ps) == 2 and msg == ["Merge x", "", "body"], "merge: two parents"
    ps, msg = split_parents_and_message(["aaa", "feat: x (#1)"])
    assert len(ps) == 1 and msg == ["feat: x (#1)"], "squash/plain: one parent"
    assert split_parents_and_message([""]) == ([], []), "root commit: no parents"
    assert split_parents_and_message([]) == ([], [])

    body = ["feat: headline (#1)", "* feat: headline", "Real summary.", "", "* fix: later", "Later prose."]
    assert first_paragraph(body) == "Real summary."
    assert first_paragraph(["s", "* feat: a", "* fix: b", "Later prose."]) == ""
    assert first_paragraph(["s", "Plain body.", "", "Co-authored-by: x"]) == "Plain body."
    # A move nets zero: same element removed from one file, added in another.
    assert scan_diff.__doc__ and "extraction refactor nets zero" in scan_diff.__doc__
    def verdict_of(**kw):
        base = dict(hits={}, gone={}, declared_feat=False, setting_added=False,
                    shipped=False, spec_touched=False, paths=[], subject_type="fix")
        return decide_verdict(**{**base, **kw})[0]

    assert verdict_of(hits={"ui_tab": 1}) == "FEATURE"
    # A surface addition outranks every claim, even a contradicting one.
    assert verdict_of(hits={"ui_tab": 1}, gone={"ui_dialog": 1}, declared_feat=True) == "FEATURE"
    assert verdict_of(gone={"api_endpoint": 1}) == "SURFACE_REMOVED"
    assert verdict_of(declared_feat=True) == "NOTHING_SHIPPED"
    assert verdict_of(declared_feat=True, shipped=True) == "FEATURE_CANDIDATE"
    assert verdict_of(setting_added=True, shipped=True) == "FEATURE_CANDIDATE"
    # A claim outranks a bare spec move, which is why the candidates table carries
    # an explicit "API contract moved" column.
    assert verdict_of(declared_feat=True, shipped=True, spec_touched=True) == "FEATURE_CANDIDATE"
    assert verdict_of(shipped=True, spec_touched=True) == "API_CONTRACT_CHANGE"
    assert verdict_of(shipped=True) == "INTERNAL_CHANGE"
    assert verdict_of(paths=["backend/tests/test_x.py"]) == "TEST_ONLY"
    assert verdict_of(paths=[".github/workflows/a.yml"]) == "CI_ONLY"
    assert verdict_of(paths=[".github/workflows/a.yml", "README.md"]) == "MIXED_SUPPORT"

    assert [v for v, _ in PRECEDENCE] == sorted(VERDICT_MEANING, key=lambda k:
        [v for v, _ in PRECEDENCE].index(k)), "PRECEDENCE and VERDICT_MEANING must agree"
    assert set(v for v, _ in PRECEDENCE) == set(VERDICT_MEANING), "verdict lists diverged"
    assert areas([".github/workflows/a.yml", "backend/src/x.py", "backend/src/y.py"]) == ["backend", "ci"]
    print("selfcheck ok")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("rev_range", nargs="?", help="e.g. AAAA..BBBB")
    ap.add_argument("--selfcheck", action="store_true", help="run detector asserts and exit")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("--repo-url", default="https://github.com/syntara-orchestration/syntara")
    ap.add_argument("--jira-url", default="https://issues.redhat.com/browse")
    args = ap.parse_args()

    if args.selfcheck:
        selfcheck()
        return
    if not args.rev_range:
        ap.error("rev_range is required unless --selfcheck is given")

    shas = [
        s
        for s in sh(
            ["git", "log", "--pretty=format:%H", "--end-of-options", args.rev_range]
        ).splitlines()
        if s
    ]
    rows = [classify(s) for s in shas]

    if args.json:
        json.dump(rows, sys.stdout, indent=2)
        sys.stdout.write("\n")
    elif args.markdown:
        emit_markdown(rows, args)
    else:
        print("\t".join(["verdict", "short", "pr", "jira", "type", "subject", "evidence"]))
        for r in rows:
            print("\t".join([r["verdict"], r["short"], str(r["pr"] or ""), ",".join(r["jira"]),
                             r["subject_type"], r["subject"], "; ".join(r["reasons"])]))


if __name__ == "__main__":
    try:
        main()
    except GitError as exc:
        # The likeliest first-run failure is a typo'd or unreachable rev-range;
        # show git's own complaint rather than a traceback.
        print(exc, file=sys.stderr)
        sys.exit(2)
