---
name: Build Backend Container Image

on:
  push:
    branches: [devel]
    paths:
      - 'backend/**'
      - '.github/workflows/build-backend-image-devel.yml'
      - '.github/workflows/_build-backend-image.yml'
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/_build-backend-image.yml
    secrets:
      RH_REGISTRY_USER: ${{ secrets.RH_REGISTRY_USER }}
      RH_REGISTRY_TOKEN: ${{ secrets.RH_REGISTRY_TOKEN }}
