/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/proxies/aap/organizations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List organizations
     * @description List Ansible Automation Platform organizations.
     */
    get: operations['list_aap_organizations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/job_templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List job templates
     * @description List Ansible Automation Platform job templates, optionally filtered by organization.
     */
    get: operations['list_aap_job_templates']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/job_templates/{job_template_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get job template
     * @description Get Ansible Automation Platform job template details including prompt-on-launch capabilities.
     */
    get: operations['get_aap_job_template']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/workflow_job_templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List workflow job templates
     * @description List Ansible Automation Platform workflow job templates, optionally filtered by organization.
     */
    get: operations['list_aap_workflow_job_templates']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/workflow_job_templates/{workflow_job_template_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get workflow job template
     * @description Get Ansible Automation Platform workflow job template details including prompt-on-launch capabilities.
     */
    get: operations['get_aap_workflow_job_template']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/inventories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List inventories
     * @description List Ansible Automation Platform inventories, optionally filtered by organization.
     */
    get: operations['list_aap_inventories']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/execution_environments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List execution environments
     * @description List Ansible Automation Platform execution environments, optionally filtered by organization.
     */
    get: operations['list_aap_execution_environments']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/credentials': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List AAP credentials
     * @description List Ansible Automation Platform credentials (not organization-scoped).
     */
    get: operations['list_aap_credentials']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/instance_groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List instance groups
     * @description List Ansible Automation Platform instance groups (not organization-scoped).
     */
    get: operations['list_aap_instance_groups']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/proxies/aap/labels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List labels
     * @description List Ansible Automation Platform labels.
     */
    get: operations['list_aap_labels']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AAPOrganization
     * @description Ansible Automation Platform organization resource.
     */
    AAPOrganization: {
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * AAPJobTemplate
     * @description Ansible Automation Platform job template resource.
     */
    AAPJobTemplate: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * AAPWorkflowJobTemplate
     * @description Ansible Automation Platform workflow job template resource.
     */
    AAPWorkflowJobTemplate: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * AAPSummaryField
     * @description Summary field with id and name from Ansible Automation Platform summary_fields.
     */
    AAPSummaryField: {
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * AAPJobType
     * @description Ansible Automation Platform job type values.
     * @enum {string}
     */
    AAPJobType: 'run' | 'check'
    /**
     * AAPJobTemplateDetail
     * @description Ansible Automation Platform job template with prompt-on-launch capabilities and default values.
     */
    AAPJobTemplateDetail: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Url
       * @description Link to the job template in Ansible Automation Platform Controller UI
       */
      url?: string | null
      /**
       * Ask Job Type On Launch
       * @default false
       */
      ask_job_type_on_launch?: boolean
      /**
       * Ask Inventory On Launch
       * @default false
       */
      ask_inventory_on_launch?: boolean
      /**
       * Ask Credential On Launch
       * @default false
       */
      ask_credential_on_launch?: boolean
      /**
       * Ask Variables On Launch
       * @default false
       */
      ask_variables_on_launch?: boolean
      /**
       * Ask Limit On Launch
       * @default false
       */
      ask_limit_on_launch?: boolean
      /**
       * Ask Tags On Launch
       * @default false
       */
      ask_tags_on_launch?: boolean
      /**
       * Ask Skip Tags On Launch
       * @default false
       */
      ask_skip_tags_on_launch?: boolean
      /**
       * Ask Verbosity On Launch
       * @default false
       */
      ask_verbosity_on_launch?: boolean
      /**
       * Ask Diff Mode On Launch
       * @default false
       */
      ask_diff_mode_on_launch?: boolean
      /**
       * Ask Forks On Launch
       * @default false
       */
      ask_forks_on_launch?: boolean
      /**
       * Ask Job Slice Count On Launch
       * @default false
       */
      ask_job_slice_count_on_launch?: boolean
      /**
       * Ask Execution Environment On Launch
       * @default false
       */
      ask_execution_environment_on_launch?: boolean
      /**
       * Ask Instance Groups On Launch
       * @default false
       */
      ask_instance_groups_on_launch?: boolean
      /**
       * Ask Labels On Launch
       * @default false
       */
      ask_labels_on_launch?: boolean
      /**
       * Ask Timeout On Launch
       * @default false
       */
      ask_timeout_on_launch?: boolean
      /**
       * Ask Scm Branch On Launch
       * @default false
       */
      ask_scm_branch_on_launch?: boolean
      /**
       * Survey Enabled
       * @default false
       */
      survey_enabled?: boolean
      /**
       * Default Inventory
       * @description Default inventory from job template summary_fields
       */
      default_inventory?: components['schemas']['AAPSummaryField'] | null
      /**
       * Default Execution Environment
       * @description Default execution environment from job template summary_fields
       */
      default_execution_environment?: components['schemas']['AAPSummaryField'] | null
      /**
       * Default Credentials
       * @description Default credentials from job template summary_fields
       */
      default_credentials?: components['schemas']['AAPSummaryField'][]
      /**
       * Default Labels
       * @description Default labels from job template summary_fields
       */
      default_labels?: components['schemas']['AAPSummaryField'][]
      /** @description Default job type - "run" or "check" */
      job_type?: components['schemas']['AAPJobType'] | null
      /**
       * Verbosity
       * @description Default verbosity level (0-5)
       */
      verbosity?: number | null
      /**
       * Forks
       * @description Default number of forks (max 10,000)
       */
      forks?: number | null
      /**
       * Limit
       * @description Default limit pattern
       */
      limit?: string | null
      /**
       * Job Tags
       * @description Default job tags
       */
      job_tags?: string | null
      /**
       * Skip Tags
       * @description Default skip tags
       */
      skip_tags?: string | null
      /**
       * Diff Mode
       * @description Default diff mode setting
       */
      diff_mode?: boolean | null
      /**
       * Job Slice Count
       * @description Default job slice count (max 10,000)
       */
      job_slice_count?: number | null
      /**
       * Timeout
       * @description Default timeout in seconds (max 7 days)
       */
      timeout?: number | null
      /**
       * Extra Vars
       * @description Default extra variables (YAML format, max 1MB)
       */
      extra_vars?: string | null
    }
    /**
     * AAPWorkflowJobTemplateDetail
     * @description Ansible Automation Platform workflow job template with prompt-on-launch capabilities and default values.
     */
    AAPWorkflowJobTemplateDetail: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Url
       * @description Link to the workflow template in Ansible Automation Platform Controller UI
       */
      url?: string | null
      /**
       * Ask Inventory On Launch
       * @default false
       */
      ask_inventory_on_launch?: boolean
      /**
       * Ask Credential On Launch
       * @default false
       */
      ask_credential_on_launch?: boolean
      /**
       * Ask Variables On Launch
       * @default false
       */
      ask_variables_on_launch?: boolean
      /**
       * Ask Limit On Launch
       * @default false
       */
      ask_limit_on_launch?: boolean
      /**
       * Ask Scm Branch On Launch
       * @default false
       */
      ask_scm_branch_on_launch?: boolean
      /**
       * Ask Labels On Launch
       * @default false
       */
      ask_labels_on_launch?: boolean
      /**
       * Ask Tags On Launch
       * @default false
       */
      ask_tags_on_launch?: boolean
      /**
       * Ask Skip Tags On Launch
       * @default false
       */
      ask_skip_tags_on_launch?: boolean
      /**
       * Survey Enabled
       * @default false
       */
      survey_enabled?: boolean
      /**
       * Default Inventory
       * @description Default inventory from workflow template summary_fields
       */
      default_inventory?: components['schemas']['AAPSummaryField'] | null
      /**
       * Default Labels
       * @description Default labels from workflow template summary_fields
       */
      default_labels?: components['schemas']['AAPSummaryField'][]
      /**
       * Limit
       * @description Default limit pattern
       */
      limit?: string | null
      /**
       * Scm Branch
       * @description Default SCM branch
       */
      scm_branch?: string | null
      /**
       * Job Tags
       * @description Default job tags
       */
      job_tags?: string | null
      /**
       * Skip Tags
       * @description Default skip tags
       */
      skip_tags?: string | null
      /**
       * Extra Vars
       * @description Default extra variables (YAML format, max 1MB)
       */
      extra_vars?: string | null
    }
    /**
     * AAPInventory
     * @description Ansible Automation Platform inventory resource.
     */
    AAPInventory: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * AAPExecutionEnvironment
     * @description Ansible Automation Platform execution environment resource.
     */
    AAPExecutionEnvironment: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * AAPCredential
     * @description Ansible Automation Platform credential resource.
     *
     *     Only ``id`` and ``name`` are exposed — descriptions are omitted to avoid
     *     leaking infrastructure details (e.g. "prod-aws-root-key") to all users.
     */
    AAPCredential: {
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * AAPInstanceGroup
     * @description Ansible Automation Platform instance group resource.
     */
    AAPInstanceGroup: {
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * AAPLabel
     * @description Ansible Automation Platform label resource.
     */
    AAPLabel: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Organization */
      organization?: number | null
    }
    /** AAPListResponse[AAPOrganization] */
    AAPListResponse_AAPOrganization_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPOrganization'][]
    }
    /** AAPListResponse[AAPJobTemplate] */
    AAPListResponse_AAPJobTemplate_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPJobTemplate'][]
    }
    /** AAPListResponse[AAPWorkflowJobTemplate] */
    AAPListResponse_AAPWorkflowJobTemplate_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPWorkflowJobTemplate'][]
    }
    /** AAPListResponse[AAPInventory] */
    AAPListResponse_AAPInventory_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPInventory'][]
    }
    /** AAPListResponse[AAPExecutionEnvironment] */
    AAPListResponse_AAPExecutionEnvironment_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPExecutionEnvironment'][]
    }
    /** AAPListResponse[AAPCredential] */
    AAPListResponse_AAPCredential_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPCredential'][]
    }
    /** AAPListResponse[AAPInstanceGroup] */
    AAPListResponse_AAPInstanceGroup_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPInstanceGroup'][]
    }
    /** AAPListResponse[AAPLabel] */
    AAPListResponse_AAPLabel_: {
      /** Count */
      count: number
      /** Results */
      results: components['schemas']['AAPLabel'][]
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /**
     * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
     *     If omitted, the selected integration's management credential is used.
     *     Credential must be of type "Ansible Automation Platform".
     */
    credentialId: string | null
    /**
     * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
     *     If omitted, the unique visible enabled AAP integration is used.
     *     Required when more than one AAP integration is visible.
     */
    integrationId: string | null
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_aap_organizations: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPOrganization_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_job_templates: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
        organization?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPJobTemplate_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_aap_job_template: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
      }
      header?: never
      path: {
        job_template_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPJobTemplateDetail']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_workflow_job_templates: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
        organization?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPWorkflowJobTemplate_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_aap_workflow_job_template: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
      }
      header?: never
      path: {
        workflow_job_template_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPWorkflowJobTemplateDetail']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_inventories: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
        organization?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPInventory_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_execution_environments: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
        organization?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPExecutionEnvironment_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_credentials: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPCredential_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_instance_groups: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPInstanceGroup_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_aap_labels: {
    parameters: {
      query?: {
        search?: string | null
        page_size?: number
        /**
         * @description Optional Orchestrator credential ID for Ansible Automation Platform Controller authentication.
         *     If omitted, the selected integration's management credential is used.
         *     Credential must be of type "Ansible Automation Platform".
         */
        credential_id?: components['parameters']['credentialId']
        /**
         * @description Optional Ansible Automation Platform Gateway integration ID for connection URL resolution.
         *     If omitted, the unique visible enabled AAP integration is used.
         *     Required when more than one AAP integration is visible.
         */
        integration_id?: components['parameters']['integrationId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AAPListResponse_AAPLabel_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
