/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/revocation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get global revocation timestamp
     * @description Read the current global revocation timestamp. Returns null fields if no revocation has been performed.
     */
    get: operations['get_global_revocation_timestamp']
    put?: never
    /**
     * Revoke all sessions
     * @description Set the global revocation timestamp to the current time. All tokens issued before this time will be rejected.
     */
    post: operations['revoke_all_sessions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/revocation/users/{username}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Revoke sessions for a user
     * @description Revoke all active sessions for a specific user. The user will need to re-authenticate.
     */
    post: operations['revoke_user_sessions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/revocation/identity_providers/{idp_name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Revoke sessions for an identity provider
     * @description Revoke all active sessions authenticated via a specific identity provider. Users who authenticated via this provider will need to re-authenticate.
     */
    post: operations['revoke_idp_sessions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * GlobalRevocationTimestampRead
     * @description Response schema for reading the global revocation timestamp.
     */
    GlobalRevocationTimestampRead: {
      /** Revoked Before */
      revoked_before?: string | null
      /** Updated At */
      updated_at?: string | null
      /** Updated By */
      updated_by?: string | null
    }
    /**
     * RevocationResponse
     * @description Response schema for revocation operations.
     */
    RevocationResponse: {
      /** Message */
      message: string
      /** Sessions Revoked */
      sessions_revoked?: number | null
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_global_revocation_timestamp: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current global revocation timestamp */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GlobalRevocationTimestampRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  revoke_all_sessions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Revocation result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RevocationResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  revoke_user_sessions: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Username of the user whose sessions should be revoked */
        username: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Revocation result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RevocationResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  revoke_idp_sessions: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Name of the identity provider whose sessions should be revoked */
        idp_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Revocation result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RevocationResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      /** @description Identity provider not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
