/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/authz/can_i': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Check if the current user can perform an action
     * @description Evaluates the current user's effective policies to determine if a specific action is allowed on a resource.
     */
    post: operations['can_i']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/authz/who_can': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * List users who can perform an action
     * @description Iterates all active users, resolves their policies, and checks each against the configured authz evaluator.
     */
    post: operations['who_can']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/authz/what_can_i': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * List all permissions for the current user
     * @description Resolves the current user's effective policies and returns them as a flat list of permission entries. No runtime policy evaluation call is needed.
     */
    post: operations['what_can_i']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/authz/resource_actions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List available resource types and actions
     * @description Returns the catalog of all resource types and the actions that can be performed on each.
     */
    get: operations['get_resource_actions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/authz/validate_name': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Validate name
     * @description Validate a resource name against naming rules.
     *     Returns whether the name is valid and, if not, why.
     *     Intended for real-time UI validation.
     */
    get: operations['validate_name']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Can I Request
     * @description Request body for the Can I? authorization check.
     */
    CanIRequest: {
      /**
       * Action
       * @description The action to check (e.g., "read", "create", "delete")
       */
      action: string
      /**
       * Resource Type
       * @description The type of resource (e.g., "workflow", "project")
       */
      resource_type: string
      /**
       * Resource Id
       * @description Optional specific resource ID
       * @default
       */
      resource_id?: string
      /**
       * Resource Labels
       * @description Labels on the target resource
       * @default {}
       */
      resource_labels?: {
        [key: string]: string
      }
      /**
       * Resource Metadata
       * @description Additional metadata about the target resource
       * @default {}
       */
      resource_metadata?: {
        [key: string]: unknown
      }
      /**
       * Resource Project
       * @description Project scope of the resource (project name or UUID)
       * @default
       */
      resource_project?: string
      /**
       * Check Any Project
       * @description When true, allow if the user has the permission in any project (project-scoped policies match without a concrete resource_project). Mutually exclusive with a non-empty resource_project. Default false preserves strict project matching — empty resource_project alone is never a wildcard.
       * @default false
       */
      check_any_project?: boolean
    }
    /**
     * Can I Response
     * @description Authorization decision result.
     */
    CanIResponse: {
      /**
       * Allowed
       * @description Whether the action is allowed
       */
      allowed: boolean
      /**
       * Denied
       * @description Whether the action is explicitly denied
       */
      denied: boolean
      /**
       * Matched Policy
       * @description Name of the policy that matched
       */
      matched_policy: string
      /**
       * Denial Reason
       * @description Reason for denial (empty if allowed)
       */
      denial_reason: string
      /**
       * Denied By
       * @description Name of the deny policy (empty if allowed)
       */
      denied_by: string
    }
    /**
     * WhoCanRequest
     * @description Request body for the Who can? endpoint.
     */
    WhoCanRequest: {
      /**
       * Limit
       * @description Maximum number of results per page
       * @default 20
       */
      limit?: number
      /**
       * Cursor
       * @description Pagination cursor from previous response
       */
      cursor?: string | null
      /**
       * Sort
       * @description Sort parameter (e.g., 'name', '-created_at')
       */
      sort?: string | null
      /**
       * Include Total
       * @description Include total count in response (expensive)
       * @default false
       */
      include_total?: boolean
      /** Action */
      action: string
      /** Resource Type */
      resource_type: string
      /**
       * Resource Id
       * @default
       */
      resource_id?: string
      /** Resource Labels */
      resource_labels?: {
        [key: string]: string
      }
      /** Resource Metadata */
      resource_metadata?: {
        [key: string]: unknown
      }
      /**
       * Resource Project
       * @description Project scope of the resource (project name or UUID)
       * @default
       */
      resource_project?: string
    }
    /**
     * WhoCanUser
     * @description A user who can perform the requested action.
     */
    WhoCanUser: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Username */
      username: string
    }
    /**
     * WhoCanResponse
     * @description Paginated response body for the Who can? endpoint.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    WhoCanResponse: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['WhoCanUser'][]
    }
    /**
     * PermissionEntry
     * @description A single permission from a policy statement.
     */
    PermissionEntry: {
      /** Policy Name */
      policy_name: string
      /** Effect */
      effect: string
      /** Actions */
      actions: string[]
      /** Scope */
      scope: string
      /**
       * Project
       * @description Project scope (empty for system-level)
       * @default
       */
      project?: string
    }
    /**
     * WhatCanIRequest
     * @description Request body for the What can I? endpoint.
     */
    WhatCanIRequest: {
      /**
       * Limit
       * @description Maximum number of results per page
       * @default 20
       */
      limit?: number
      /**
       * Cursor
       * @description Pagination cursor from previous response
       */
      cursor?: string | null
      /**
       * Sort
       * @description Sort parameter (e.g., 'name', '-created_at')
       */
      sort?: string | null
      /**
       * Include Total
       * @description Include total count in response (expensive)
       * @default false
       */
      include_total?: boolean
    }
    /**
     * WhatCanIResponse
     * @description Paginated response body for the What can I? endpoint.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    WhatCanIResponse: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['PermissionEntry'][]
    }
    /**
     * Resource Actions Response
     * @description Available resource types and their valid actions.
     */
    ResourceActionsResponse: {
      /**
       * Resource Actions
       * @description Map of resource types to their valid actions
       */
      resource_actions: {
        [key: string]: string[]
      }
    }
    /**
     * ValidateNameResponse
     * @description Response body for the validate_name endpoint.
     */
    ValidateNameResponse: {
      /** Valid */
      valid: boolean
      /** Name */
      name: string
      /**
       * Reason
       * @default
       */
      reason?: string
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  can_i: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CanIRequest']
      }
    }
    responses: {
      /** @description Authorization decision */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CanIResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  who_can: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WhoCanRequest']
      }
    }
    responses: {
      /** @description List of authorized users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WhoCanResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  what_can_i: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WhatCanIRequest']
      }
    }
    responses: {
      /** @description Paginated list of permission entries */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WhatCanIResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_resource_actions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Map of resource types to their valid actions */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourceActionsResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  validate_name: {
    parameters: {
      query: {
        /** @description Name to validate */
        name: string
        /** @description Resource type */
        resource_type?: 'project' | 'policy' | 'role'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ValidateNameResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
