/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/credentials': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List credentials
     * @description List Credentials with filtering and pagination. Metadata only, no secrets.
     *
     *     When for_action=use, returns only credentials the user has credential:use
     *     permission on (for workflow builder credential selection).
     */
    get: operations['list_credentials']
    put?: never
    /**
     * Create credential
     * @description Create a new Credential with encrypted inputs.
     */
    post: operations['create_credential']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/credentials/{credential_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get credential
     * @description Get a Credential. Secret fields masked as $encrypted$.
     */
    get: operations['get_credential']
    put?: never
    post?: never
    /**
     * Delete credential
     * @description Delete a Credential.
     */
    delete: operations['delete_credential']
    options?: never
    head?: never
    /**
     * Update credential
     * @description Update a Credential. Fields set to $encrypted$ retain existing values.
     */
    patch: operations['update_credential']
    trace?: never
  }
  '/credentials/{credential_id}/workflows': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get credential workflows
     * @description Get workflows that reference this credential.
     *
     *     Returns workflows with nodes that have credential_id in their executor configs.
     */
    get: operations['get_credential_workflows']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/credential_types': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List credential types
     * @description List all Credential Types including preseeded managed types.
     *
     *     Each type includes a credential_count of credentials using it.
     */
    get: operations['list_credential_types']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/credential_types/{credential_type_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get credential type
     * @description Get a single Credential Type with credential_count.
     */
    get: operations['get_credential_type']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * CredentialListResponse
     * @description Paginated list response for credentials.
     */
    CredentialListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['CredentialRead'][]
    }
    /**
     * CredentialTypeListResponse
     * @description Paginated list response for credential types.
     */
    CredentialTypeListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['CredentialTypeRead'][]
    }
    /**
     * CredentialWorkflowListResponse
     * @description Paginated list response for credential workflow references.
     */
    CredentialWorkflowListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['CredentialWorkflowRef'][]
    }
    /**
     * CredentialCreate
     * @description Schema for creating a new credential.
     */
    CredentialCreate: {
      /**
       * Credential Type Id
       * Format: uuid
       * @description ID of the credential type
       */
      credential_type_id: string
      /**
       * Description
       * @description Optional description
       */
      description?: string | null
      /**
       * Inputs
       * @description Field values validated against type schema
       */
      inputs?: {
        [key: string]: unknown
      }
      /**
       * Labels
       * @description Key-value labels
       */
      labels?: {
        [key: string]: string
      }
      /**
       * Name
       * @description Human-readable credential name
       */
      name: string
      /**
       * Project Id
       * Format: uuid
       * @description Project to assign credential to
       */
      project_id: string
    }
    /**
     * CredentialUpdate
     * @description Schema for partially updating a credential. $encrypted$ preserves existing values.
     */
    CredentialUpdate: {
      /** Description */
      description?: string | null
      /** Enabled */
      enabled?: boolean | null
      /** Inputs */
      inputs?: {
        [key: string]: unknown
      } | null
      /** Labels */
      labels?: {
        [key: string]: string
      } | null
      /** Name */
      name?: string | null
      /**
       * Project Id
       * @description Project ID (immutable after creation; rejected if different from stored value)
       */
      project_id?: string | null
    }
    /** @description Schema for credential API responses. Secret fields masked as $encrypted$. */
    CredentialRead: components['schemas']['NamedResource'] & {
      /**
       * Created By
       * @description User who created the credential
       */
      readonly created_by?: components['schemas']['UserReference'] | null
      /**
       * Updated By
       * @description User who last modified the credential
       */
      readonly updated_by?: components['schemas']['UserReference'] | null
      /**
       * Credential Type Id
       * Format: uuid
       */
      credential_type_id: string
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean
      /** Inputs */
      inputs?: {
        [key: string]: unknown
      }
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string
      /**
       * Workflow Count
       * @description Number of workflows referencing this credential
       * @default 0
       */
      workflow_count?: number
      /**
       * Integration Count
       * @description Number of integrations using this credential
       * @default 0
       */
      integration_count?: number
    }
    /** @description Read schema for credential type API responses. */
    CredentialTypeRead: components['schemas']['BaseResource'] & {
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Credential Count
       * @description Number of credentials using this type
       * @default 0
       */
      credential_count?: number
      /** Injectors */
      injectors?: {
        [key: string]: unknown
      }
      /** Inputs */
      inputs?: {
        [key: string]: unknown
      }
      /**
       * Managed
       * @default false
       */
      managed?: boolean
    }
    /**
     * CredentialWorkflowRef
     * @description Reference to a workflow that uses a credential.
     */
    CredentialWorkflowRef: {
      /**
       * Created By
       * @description Username or UUID of the workflow creator
       */
      created_by?: string | null
      /**
       * Created At
       * @description Timestamp when the workflow was created
       */
      created_at?: string | null
      /** Description */
      description?: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Last Execution At
       * @description Timestamp of the most recent execution
       */
      last_execution_at?: string | null
      /**
       * Last Execution Status
       * @description Status of the most recent execution
       */
      last_execution_status?: string | null
      /** Name */
      name: string
      /**
       * Node Names
       * @description Names of nodes using this credential
       */
      node_names?: string[]
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponseBase: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources?: unknown[]
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    NamedResource: components['schemas']['BaseResource'] & {
      /**
       * Name
       * @description Human-readable name for the resource
       * @example Authentication Service
       */
      name: string
      /**
       * Description
       * @description Detailed description of the resource
       * @example Handles user authentication and authorization workflows
       */
      description?: string | null
    }
    /**
     * UserReference
     * @description Minimal user identification for embedding in other resources.
     *     This model captures user identity at the time of an action, providing
     *     a snapshot that doesn't change even if the user's details are updated later.
     */
    UserReference: {
      /**
       * Format: uuid
       * @description User's unique identifier
       */
      id: string
      /** @description User's display name at time of action */
      name: string
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_credentials: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
        /** @description Filter by credential type ID */
        credential_type_id?: string | null
        /** @description Filter by enabled status */
        enabled?: boolean | null
        /** @description Filter by permission action. When 'use', returns only credentials with credential:use permission. */
        for_action?: 'use' | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  create_credential: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CredentialCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_credential: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_credential: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  update_credential: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CredentialUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_credential_workflows: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialWorkflowListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_credential_types: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialTypeListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_credential_type: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_type_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CredentialTypeRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
