/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/executions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List executions
     * @description Retrieve executions with filtering, sorting, and cursor-based pagination.
     */
    get: operations['list_executions']
    put?: never
    /**
     * Create execution
     * @description Start a new workflow execution.
     */
    post: operations['create_execution']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{execution_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get execution
     * @description Retrieve details of a specific execution with optional includes.
     */
    get: operations['get_execution']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{execution_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel execution
     * @description Request cancellation of a running workflow execution. The status update to CANCELLED happens asynchronously.
     */
    post: operations['cancel_execution']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{execution_id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retry execution
     * @description Retry a completed workflow execution. Creates a new execution using the same workflow version, inputs, and trigger as the original.
     */
    post: operations['retry_execution']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{execution_id}/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List activity executions
     * @description Retrieve activity executions for a workflow execution.
     */
    get: operations['list_execution_activities']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{execution_id}/activities/{activity_id}/signal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Send signal to activity in workflow
     * @description Send a signal to a specific activity within a running workflow execution.
     */
    post: operations['signal_activity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ExecutionRead
     * @description Schema for execution response (GET /executions/{id}).
     *
     *     Includes database table fields plus computed fields (workflow_version,
     *     workflow_version_name, workflow_version_created_at) populated
     *     by ExecutionsConvertResourceMixin from the related WorkflowVersion.
     */
    ExecutionRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Workflow Id
       * Format: uuid
       */
      workflow_id: string
      /**
       * Workflow Version Id
       * Format: uuid
       */
      workflow_version_id: string
      /**
       * Workflow Name
       * @description Name of the workflow
       */
      workflow_name?: string | null
      /**
       * Workflow Version
       * @description Version number of the workflow version that was executed
       */
      workflow_version?: number | null
      /**
       * Workflow Version Name
       * @description Name of the executed version, if one was set
       */
      workflow_version_name?: string | null
      /**
       * Workflow Version Created At
       * @description Timestamp when the executed version was created
       */
      workflow_version_created_at?: string | null
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string
      /** Temporal Workflow Id */
      temporal_workflow_id: string
      status: components['schemas']['ExecutionStatus']
      /**
       * Created By
       * Format: uuid
       */
      created_by: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Completed At */
      completed_at: string | null
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /** Updated By */
      updated_by: string | null
      /** Input Data */
      input_data: {
        [key: string]: unknown
      }
      /** Trigger Node Id */
      trigger_node_id?: string | null
      /** Error Details */
      error_details: string | null
      /** @default standard */
      mode?: components['schemas']['ExecutionMode']
      /** Execution Metadata */
      execution_metadata?: {
        [key: string]: unknown
      } | null
      /** Retried From Execution Id */
      retried_from_execution_id?: string | null
      /**
       * Trigger Type
       * @description Trigger node type (manual_trigger, scheduled_trigger, webhook_trigger, eda_trigger)
       */
      trigger_type?: string | null
      /**
       * Interface
       * @description Originating interface (ui or api)
       */
      interface?: string | null
      /** Labels */
      labels?: {
        [key: string]: unknown
      }
      /**
       * Approval Pending
       * @default false
       */
      approval_pending?: boolean
      /**
       * Current Activities
       * @description Currently executing activities
       */
      current_activities?: components['schemas']['CurrentActivity'][]
      /** Deleted At */
      deleted_at?: string | null
      /** Deleted By */
      deleted_by?: string | null
      /** @description Workflow definition from the executed version. Only included when requested via ?include=workflow_definition query parameter. */
      workflow_definition?: components['schemas']['WorkflowDefinition'] | null
      /**
       * Activities
       * @description List of activities with their current status. Only included when requested via ?include=activities query parameter.
       */
      activities?: components['schemas']['ActivityData'][] | null
    }
    ActivityExecution: components['schemas']['BaseResource'] & {
      /**
       * Execution Id
       * Format: uuid
       * @description Parent execution ID
       */
      execution_id: string
      /**
       * Activity Name
       * @description Activity ID from workflow definition
       */
      activity_name: string
      /** @description Node type from workflow definition */
      node_type: components['schemas']['NodeType']
      /**
       * Temporal Activity Id
       * @description Temporal activity execution ID
       */
      temporal_activity_id: string
      /** @description Current activity status */
      status: components['schemas']['ActivityStatus']
      /**
       * Started At
       * @description When activity started execution
       */
      started_at?: string | null
      /**
       * Completed At
       * @description When activity completed/failed
       */
      completed_at?: string | null
      /**
       * Input Data
       * @description Runtime input parameters
       */
      input_data?: {
        [key: string]: unknown
      }
      /**
       * Output Data
       * @description Activity results (if completed)
       */
      output_data?: {
        [key: string]: unknown
      } | null
      /**
       * Error Details
       * @description Error information if failed
       */
      error_details?: string | null
      /**
       * Retry Count
       * @description Number of retry attempts
       * @default 0
       */
      retry_count?: number
      /**
       * Iteration
       * @description Iteration number if activity is within a loop (0-indexed)
       */
      iteration?: number | null
    }
    /**
     * ActivityData
     * @description Activity data for execution response.
     */
    ActivityData: {
      /** Activity Id */
      activity_id: string
      /** Status */
      status: string
      /** Error Details */
      error_details?: string | null
      /** Iteration */
      iteration?: number | null
      /** Output Data */
      output_data?: {
        [key: string]: unknown
      } | null
      /** Started At */
      started_at?: string | null
      /** Completed At */
      completed_at?: string | null
    }
    /**
     * ActivityStatus
     * @description Activity execution status enumeration.
     * @enum {string}
     */
    ActivityStatus: 'pending' | 'running' | 'waiting' | 'completed' | 'failed' | 'retrying' | 'skipped' | 'cancelled'
    /**
     * NodeType
     * @description Node types for V2 workflows (used by telemetry).
     * @enum {string}
     */
    NodeType:
      | 'manual_trigger'
      | 'scheduled_trigger'
      | 'webhook_trigger'
      | 'eda_trigger'
      | 'condition'
      | 'converge'
      | 'loop'
      | 'switch'
      | 'wait'
      | 'aap_job_template'
      | 'aap_workflow_job_template'
      | 'agentic'
      | 'approval'
      | 'http_request'
      | 'internal_activity'
      | 'script'
    /**
     * CurrentActivity
     * @description Currently executing activity information.
     */
    CurrentActivity: {
      /**
       * Activity Name
       * @description Name of the activity
       */
      activity_name: string
      /**
       * Temporal Activity Id
       * @description Temporal activity ID
       */
      temporal_activity_id: string
      /**
       * Iteration
       * @description Iteration number for loops
       */
      iteration?: number | null
    }
    /**
     * ExecutionListResponse
     * @description Paginated list response for executions.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ExecutionListResponse: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['ExecutionRead'][]
    }
    /**
     * ActivityExecutionListResponse
     * @description Paginated list response for activity executions.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ActivityExecutionListResponse: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['ActivityExecution'][]
    }
    /**
     * ExecutionStatus
     * @description Current state of a workflow execution lifecycle.
     * @enum {string}
     */
    ExecutionStatus: 'pending' | 'running' | 'paused' | 'completed' | 'completed_with_errors' | 'failed' | 'cancelled'
    /**
     * ExecutionCreate
     * @description Schema for creating a new execution (POST /executions).
     *
     *     Excludes auto-generated fields: id, created_at, created_by (set by backend).
     */
    ExecutionCreate: {
      /**
       * Workflow Id
       * Format: uuid
       * @description Workflow ID to execute
       */
      workflow_id: string
      /**
       * Input Data
       * @description Input data for workflow execution
       */
      input_data?: {
        [key: string]: unknown
      }
      /**
       * Trigger Node Id
       * @description Trigger node ID to start from
       */
      trigger_node_id: string
      /**
       * Use Published
       * @description If true, run the published version instead of the current version
       * @default false
       */
      use_published?: boolean
    }
    /**
     * TestExecutionCreate
     * @description Request body for POST /workflows/{workflow_id}/test.
     */
    TestExecutionCreate: {
      /**
       * Target Node Id
       * @description The node to execute for real
       */
      target_node_id: string
      /**
       * Pre Resolved Nodes
       * @description Mock outputs for predecessor nodes. Keys are node IDs.
       */
      pre_resolved_nodes?: {
        [key: string]: components['schemas']['PreResolvedNodeOutput']
      }
      /**
       * Trigger Inputs
       * @description Input data for the trigger node
       */
      trigger_inputs?: {
        [key: string]: unknown
      }
      /**
       * Execute Target
       * @description When False, run predecessors up to (but not including) the target node. Useful for populating upstream data without executing the target. When True (default), target_node_id must not appear in pre_resolved_nodes.
       * @default true
       */
      execute_target?: boolean
      /**
       * Trigger Node Id
       * @description Trigger node ID to start from
       */
      trigger_node_id: string
    }
    /**
     * ExecutionMode
     * @description Execution mode for workflow runs.
     * @enum {string}
     */
    ExecutionMode: 'standard' | 'test' | 'debug'
    /**
     * Signal Response
     * @description Response confirming a signal was sent to a workflow
     */
    SignalResponse: {
      /**
       * Status
       * @description Confirmation that the signal was successfully sent
       */
      status: string
      /**
       * Message
       * @description Human-readable confirmation message
       */
      message?: string | null
    }
    /**
     * Activity Signal Payload
     * @description Generic signal payload for sending arbitrary data to a specific activity within a running workflow execution.
     */
    ActivitySignalPayload: {
      /**
       * Signal Data
       * @description Arbitrary JSON data to send to the activity. The structure depends on what the activity expects to receive.
       * @example {
       *       "action": "resume",
       *       "result": {
       *         "value": 42
       *       },
       *       "status": "completed"
       *     }
       */
      signal_data: {
        [key: string]: unknown
      }
    }
    /**
     * NodePosition
     * @description UI position hint for a workflow node.
     */
    NodePosition: {
      /** X */
      x: number
      /** Y */
      y: number
    }
    /**
     * AAPVerbosity
     * @description Ansible Automation Platform job verbosity levels (0-5).
     * @enum {integer}
     */
    AAPVerbosity: 0 | 1 | 2 | 3 | 4 | 5
    /**
     * AAPJobType
     * @description Ansible Automation Platform job type values.
     * @enum {string}
     */
    AAPJobType: 'run' | 'check'
    /**
     * AAPJobTemplateExecutorParameters
     * @description Parameters for Ansible Automation Platform Job Template executor.
     *
     *     Inherits common Ansible Automation Platform fields from AAPResourceReferenceMixin (credential_id, organization,
     *     inventory, extra_vars, limit, tags, skip_tags, labels, timeout).
     */
    AAPJobTemplateExecutorParameters: {
      /**
       * Credential Id
       * @description Orchestrator credential UUID for Ansible Automation Platform API authentication. Separate from legacy credentials list.
       */
      credential_id?: string | null
      /**
       * Integration Id
       * @description UUID of the Ansible Automation Platform Gateway integration for connection URL resolution.
       */
      integration_id?: string | null
      /**
       * Organizationid
       * @description Ansible Automation Platform organization ID (takes precedence over organization_name)
       */
      organizationId?: number | null
      /**
       * Organization Name
       * @description Ansible Automation Platform organization name (used with template_name or inventory_name)
       */
      organization_name?: string | null
      /**
       * Inventory Id
       * @description Override default inventory by ID (mutually exclusive with inventory_name)
       */
      inventory_id?: number | null
      /**
       * Inventory Name
       * @description Override default inventory by name (requires organization_name)
       */
      inventory_name?: string | null
      /**
       * Extra Vars
       * @description Extra variables to pass to job/workflow job
       */
      extra_vars?: {
        [key: string]: unknown
      }
      /**
       * Limit
       * @description Limit job execution to specific hosts
       */
      limit?: string | null
      /**
       * Tags
       * @description Ansible tags to run (comma-separated)
       */
      tags?: string | null
      /**
       * Skip Tags
       * @description Ansible tags to skip (comma-separated)
       */
      skip_tags?: string | null
      /**
       * Labels
       * @description Ansible Automation Platform label names to append to template's default labels. Names are resolved to IDs at launch time. New labels that don't exist in Ansible Automation Platform will be created automatically. Note: Labels are APPENDED to template defaults, not replaced.
       */
      labels?: string[] | null
      /**
       * Job Template Id
       * @description Ansible Automation Platform job template ID to launch
       */
      job_template_id?: number | null
      /**
       * Job Template Name
       * @description Ansible Automation Platform job template name (used with organization_name)
       */
      job_template_name?: string | null
      /**
       * Job Credentials
       * @description List of Ansible Automation Platform credential IDs to use (takes precedence over credential_names)
       */
      job_credentials?: number[] | null
      /**
       * Credentialnames
       * @description List of Ansible Automation Platform credential names to use (requires organization_name, resolved at launch time)
       */
      credentialNames?: string[] | null
      /**
       * @description Job verbosity level (0-5)
       * @default 0
       */
      verbosity?: components['schemas']['AAPVerbosity']
      /** @description Job type override: 'run' or 'check' (dry run) */
      job_type?: components['schemas']['AAPJobType'] | null
      /**
       * Forks
       * @description Number of parallel forks for job execution
       */
      forks?: number | null
      /**
       * Job Slicing
       * @description Number of job slices
       */
      job_slicing?: number | null
      /**
       * Diff Mode
       * @description Enable diff mode for playbook runs
       */
      diff_mode?: boolean | null
      /**
       * Execution Environment
       * @description Execution environment override (deferred — requires ID resolution)
       */
      execution_environment?: string | null
      /**
       * Instance Group Id
       * @description Override instance group by ID (takes precedence over instance_group_name)
       */
      instance_group_id?: number | null
      /**
       * Instance Group Name
       * @description Override instance group by name (requires organization_name for lookup)
       */
      instance_group_name?: string | null
    }
    /**
     * RetryPolicyParameters
     * @description Retry policy parameters for a node.
     *
     *     Only applies to nodes whose settings class is NodeSettingsFull
     *     (http_request, aap_job_template, aap_workflow_job_template).
     *
     *     All fields default to None — the engine merges with global catalog values
     *     (workflow_engine.retry_*) for any unset field. Set max_retries=0 to
     *     explicitly disable retry, overriding global defaults.
     */
    RetryPolicyParameters: {
      /**
       * Max Retries
       * @description Retries after initial attempt. 0 = no retry.
       */
      max_retries?: number | null
      /**
       * Initial Interval
       * @description Initial retry interval in seconds.
       */
      initial_interval?: number | null
      /**
       * Max Interval
       * @description Maximum retry interval in seconds.
       */
      max_interval?: number | null
      /**
       * Backoff Coefficient
       * @description Multiplier per retry. 1.0 = fixed, >1.0 = exponential.
       */
      backoff_coefficient?: number | null
    }
    /**
     * NodeSettingsFull
     * @description Full settings with retry_policy (http_request, aap_job_template, aap_workflow_job_template).
     */
    NodeSettingsFull: {
      /** Continue On Failure */
      continue_on_failure?: boolean | null
      /** Disabled */
      disabled?: boolean | null
      /** Timeout */
      timeout?: number | null
      retry_policy?: components['schemas']['RetryPolicyParameters'] | null
    }
    /**
     * AAPJobTemplateNode
     * @description Ansible Automation Platform job template executor node.
     */
    AAPJobTemplateNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'aap_job_template'
      parameters: components['schemas']['AAPJobTemplateExecutorParameters']
      settings?: components['schemas']['NodeSettingsFull'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * AAPWorkflowJobTemplateExecutorParameters
     * @description Parameters for Ansible Automation Platform Workflow Job Template executor.
     *
     *     Inherits common Ansible Automation Platform fields from AAPResourceReferenceMixin (credential_id, organization,
     *     inventory, extra_vars, limit, tags, skip_tags, labels, timeout).
     */
    AAPWorkflowJobTemplateExecutorParameters: {
      /**
       * Credential Id
       * @description Orchestrator credential UUID for Ansible Automation Platform API authentication. Separate from legacy credentials list.
       */
      credential_id?: string | null
      /**
       * Integration Id
       * @description UUID of the Ansible Automation Platform Gateway integration for connection URL resolution.
       */
      integration_id?: string | null
      /**
       * Organizationid
       * @description Ansible Automation Platform organization ID (takes precedence over organization_name)
       */
      organizationId?: number | null
      /**
       * Organization Name
       * @description Ansible Automation Platform organization name (used with template_name or inventory_name)
       */
      organization_name?: string | null
      /**
       * Inventory Id
       * @description Override default inventory by ID (mutually exclusive with inventory_name)
       */
      inventory_id?: number | null
      /**
       * Inventory Name
       * @description Override default inventory by name (requires organization_name)
       */
      inventory_name?: string | null
      /**
       * Extra Vars
       * @description Extra variables to pass to job/workflow job
       */
      extra_vars?: {
        [key: string]: unknown
      }
      /**
       * Limit
       * @description Limit job execution to specific hosts
       */
      limit?: string | null
      /**
       * Tags
       * @description Ansible tags to run (comma-separated)
       */
      tags?: string | null
      /**
       * Skip Tags
       * @description Ansible tags to skip (comma-separated)
       */
      skip_tags?: string | null
      /**
       * Labels
       * @description Ansible Automation Platform label names to append to template's default labels. Names are resolved to IDs at launch time. New labels that don't exist in Ansible Automation Platform will be created automatically. Note: Labels are APPENDED to template defaults, not replaced.
       */
      labels?: string[] | null
      /**
       * Workflow Job Template Id
       * @description Ansible Automation Platform workflow job template ID to launch
       */
      workflow_job_template_id?: number | null
      /**
       * Workflow Job Template Name
       * @description Ansible Automation Platform workflow job template name (used with organization_name)
       */
      workflow_job_template_name?: string | null
      /**
       * Scm Branch
       * @description SCM branch override for projects in workflow
       */
      scm_branch?: string | null
    }
    /**
     * AAPWorkflowJobTemplateNode
     * @description Ansible Automation Platform workflow job template executor node.
     */
    AAPWorkflowJobTemplateNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'aap_workflow_job_template'
      parameters: components['schemas']['AAPWorkflowJobTemplateExecutorParameters']
      settings?: components['schemas']['NodeSettingsFull'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * IntegrationConnectionConfig
     * @description Execution credential override for one integration.
     *
     *
     *     When included in AgenticExecutorParameters.integration_connections, this credential
     *
     *     is used for calls against that integration instead of the integration's
     *
     *     management credential.
     */
    IntegrationConnectionConfig: {
      /**
       * Integration Id
       * @description UUID of the integration
       */
      integration_id: string
      /**
       * Credential Id
       * @description Orchestrator credential UUID for execution calls (distinct from management credential)
       */
      credential_id: string
    }
    /**
     * AgenticExecutorParameters
     * @description Parameters for agentic executor.
     */
    AgenticExecutorParameters: {
      /**
       * Prompt
       * @description Prompt template for the agent
       */
      prompt: string
      /** Agent */
      agent?: string | null
      /**
       * Llm Model Id
       * @description UUID of the LLMModel record identifying the provider integration and model.
       */
      llm_model_id?: string | null
      /**
       * Credential Id
       * @description Orchestrator credential UUID for LLM provider authentication
       */
      credential_id?: string | null
      /**
       * File Ids
       * @description File IDs for agent context
       */
      file_ids?: string[]
      /**
       * Responseschema
       * @description JSON Schema for structured output. When defined, agent output conforms to this schema.
       */
      responseSchema?:
        | {
            [key: string]: unknown
          }
        | string
        | null
      /**
       * Integration Connections
       * @description Per-integration execution credentials. Each entry overrides the management credential for that integration. Integrations not listed fall back to their management credential.
       */
      integration_connections?: components['schemas']['IntegrationConnectionConfig'][] | null
      /**
       * Tool Selection Strategy
       * @description ALL (all enabled tools), NONE (no tools), or SELECTED (specific tools from tool_selections)
       */
      tool_selection_strategy?: ('ALL' | 'NONE' | 'SELECTED') | null
      /**
       * Tool Selections
       * @description Tool UUIDs to make available when tool_selection_strategy is SELECTED
       */
      tool_selections?: string[]
    }
    /**
     * NodeSettingsNoRetry
     * @description Settings with disabled, continue_on_failure, and timeout (script, agentic, approval).
     */
    NodeSettingsNoRetry: {
      /** Continue On Failure */
      continue_on_failure?: boolean | null
      /** Disabled */
      disabled?: boolean | null
      /** Timeout */
      timeout?: number | null
    }
    /**
     * AgenticNode
     * @description Agentic executor node.
     */
    AgenticNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'agentic'
      parameters: components['schemas']['AgenticExecutorParameters']
      settings?: components['schemas']['NodeSettingsNoRetry'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * ApprovalNodeParameters
     * @description Parameters for approval gate nodes.
     */
    ApprovalNodeParameters: {
      /**
       * Credential Id
       * @description Orchestrator credential UUID
       */
      credential_id?: string | null
      /**
       * Approver Users
       * @description Usernames who can approve
       */
      approver_users?: string[] | null
      /**
       * Approver Groups
       * @description Group names whose members can approve
       */
      approver_groups?: string[] | null
      /**
       * Prompt
       * @description Message to display to approvers
       */
      prompt?: string | null
      /**
       * Fallback Decision
       * @description Decision when approval times out with continue_on_failure
       */
      fallback_decision?: ('approve' | 'reject') | null
      /**
       * Decision Window
       * @description Response timeout in seconds
       */
      decision_window?: number | null
    }
    /**
     * ApprovalNode
     * @description Approval gate node.
     */
    ApprovalNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'approval'
      parameters: components['schemas']['ApprovalNodeParameters']
      settings?: components['schemas']['NodeSettingsNoRetry'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * ConditionNodeParameters
     * @description Parameters for condition (if/then/else) control nodes.
     */
    ConditionNodeParameters: {
      /**
       * Condition
       * @description Expression that evaluates to boolean
       */
      condition: string
    }
    /**
     * NodeSettingsBase
     * @description Base node settings — no user-configurable fields.
     */
    NodeSettingsBase: Record<string, never>
    /**
     * ConditionNode
     * @description Binary conditional branching node.
     */
    ConditionNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'condition'
      parameters: components['schemas']['ConditionNodeParameters']
      settings?: components['schemas']['NodeSettingsBase'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * ConvergeStrategy
     * @description Convergence strategies for converge nodes.
     * @enum {string}
     */
    ConvergeStrategy: 'all' | 'any'
    /**
     * ConvergeNodeParameters
     * @description Parameters for converge (synchronization) control nodes.
     */
    ConvergeNodeParameters: {
      /** @description Convergence strategy */
      strategy?: components['schemas']['ConvergeStrategy'] | null
      /**
       * N Required
       * @description Branches required when strategy is 'any'
       */
      n_required?: number | null
      /**
       * Wait Duration
       * @description Wait timeout in seconds
       */
      wait_duration?: number | null
    }
    /**
     * NodeSettingsCof
     * @description Settings with continue_on_failure only (converge, loop).
     */
    NodeSettingsCof: {
      /** Continue On Failure */
      continue_on_failure?: boolean | null
    }
    /**
     * ConvergeNode
     * @description Convergence/synchronization control node.
     */
    ConvergeNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'converge'
      parameters: components['schemas']['ConvergeNodeParameters']
      settings?: components['schemas']['NodeSettingsCof'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * HTTPMethod
     * @description Supported HTTP methods for API requests.
     * @enum {string}
     */
    HTTPMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE'
    /**
     * APIExecutorParameters
     * @description Parameters for API executor (http_request activity).
     */
    APIExecutorParameters: {
      /** @description HTTP method */
      method: components['schemas']['HTTPMethod']
      /**
       * Url
       * @description Request URL (optional when a Secret URL credential provides it)
       */
      url?: string | null
      /** Headers */
      headers?: {
        [key: string]: unknown
      }
      /** Body */
      body?:
        | {
            [key: string]: unknown
          }
        | string
        | null
      /** Query Params */
      query_params?: {
        [key: string]: unknown
      }
      /**
       * Credential Id
       * @description Orchestrator credential UUID for authentication or Secret URL.
       */
      credential_id?: string | null
    }
    /**
     * HTTPRequestNode
     * @description HTTP request executor node.
     */
    HTTPRequestNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'http_request'
      parameters: components['schemas']['APIExecutorParameters']
      settings?: components['schemas']['NodeSettingsFull'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * DoWhileLoopParameters
     * @description Parameters for do_while loop nodes.
     */
    DoWhileLoopParameters: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'do_while'
      /**
       * Condition
       * @description Boolean expression evaluated after each iteration
       */
      condition: string
      /**
       * Max Iterations
       * @description Maximum iterations
       */
      max_iterations?: number | null
    }
    /**
     * ForEachLoopParameters
     * @description Parameters for for_each loop nodes.
     */
    ForEachLoopParameters: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'for_each'
      /**
       * Items
       * @description Array expression to iterate over
       */
      items: string
      /**
       * Max Iterations
       * @description Maximum items to process
       */
      max_iterations?: number | null
    }
    /**
     * LoopNode
     * @description Loop (for_each/do_while) control node.
     */
    LoopNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'loop'
      /** Parameters */
      parameters: components['schemas']['ForEachLoopParameters'] | components['schemas']['DoWhileLoopParameters']
      settings?: components['schemas']['NodeSettingsCof'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * ScriptLanguage
     * @description Supported script languages for script executor.
     * @enum {string}
     */
    ScriptLanguage: 'bash' | 'python'
    /**
     * ScriptExecutorParameters
     * @description Parameters for script executor.
     */
    ScriptExecutorParameters: {
      language: components['schemas']['ScriptLanguage']
      /**
       * Code
       * @description Script code to execute
       */
      code: string
      /**
       * Environment
       * @description Environment variables
       */
      environment?: {
        [key: string]: string
      }
      /**
       * Credential Id
       * @description Orchestrator credential UUID for credential scrubbing
       */
      credential_id?: string | null
    }
    /**
     * ScriptNode
     * @description Script executor node.
     */
    ScriptNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'script'
      parameters: components['schemas']['ScriptExecutorParameters']
      settings?: components['schemas']['NodeSettingsNoRetry'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * SwitchCase
     * @description A single case in a switch node.
     */
    SwitchCase: {
      /**
       * Port
       * @description Port identifier for this case
       */
      port: string
      /**
       * Label
       * @description Display label for this case
       */
      label: string
      /**
       * Condition
       * @description Boolean expression to evaluate
       */
      condition: string
    }
    /**
     * SwitchNodeParameters
     * @description Parameters for switch (multi-branch) control nodes.
     */
    SwitchNodeParameters: {
      /**
       * Cases
       * @description Ordered list of cases
       */
      cases: components['schemas']['SwitchCase'][]
      /**
       * Default Port
       * @description Port to route to when no case matches
       */
      default_port?: string | null
    }
    /**
     * SwitchNode
     * @description Multi-case branching control node.
     */
    SwitchNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'switch'
      parameters: components['schemas']['SwitchNodeParameters']
      settings?: components['schemas']['NodeSettingsBase'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * WaitNodeParameters
     * @description Parameters for wait (delay) control nodes.
     */
    WaitNodeParameters: {
      /**
       * Duration
       * @description Wait duration in seconds
       */
      duration: number
    }
    /**
     * NodeSettingsCofDisabled
     * @description Settings with disabled and continue_on_failure (wait).
     */
    NodeSettingsCofDisabled: {
      /** Continue On Failure */
      continue_on_failure?: boolean | null
      /** Disabled */
      disabled?: boolean | null
    }
    /**
     * WaitNode
     * @description Wait (delay) control node.
     */
    WaitNode: {
      /**
       * Id
       * @description Unique identifier for the node within the workflow
       */
      id: string
      /**
       * Name
       * @description Human-readable name for the node
       */
      name?: string | null
      /**
       * Description
       * @description Human-readable description of the node purpose
       */
      description?: string | null
      /**
       * Outputs
       * @description Output extraction mapping
       */
      outputs?: {
        [key: string]: string
      } | null
      /** @description Optional UI position hint */
      position?: components['schemas']['NodePosition'] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wait'
      parameters: components['schemas']['WaitNodeParameters']
      settings?: components['schemas']['NodeSettingsCofDisabled'] | null
    } & {
      [key: string]: unknown
    }
    /**
     * WorkflowDefinition
     * @description JSON Schema for graph-based workflow definitions in the Orchestrator Workflow Engine v2.
     *
     *     Attributes:
     *         schema_version: Schema version that this workflow definition conforms to
     *         name: Workflow name
     *         description: Human-readable description of the workflow's purpose
     *         triggers: Trigger nodes that define how the workflow is initiated
     *         nodes: Execution and control nodes in the workflow graph
     *         edges: Directed edges connecting triggers and nodes in the workflow graph
     */
    WorkflowDefinition: {
      /**
       * Schema Version
       * @description Schema version that this workflow definition conforms to
       * @constant
       */
      schema_version: '2.0.0'
      /**
       * Name
       * @description Workflow name
       */
      name: string
      /**
       * Description
       * @description Human-readable description of the workflow's purpose
       */
      description?: string | null
      /**
       * Triggers
       * @description Trigger nodes that define how the workflow is initiated. Must contain at least one trigger. Trigger nodes must be graph entry points (no incoming edges) — enforced by application-level validation.
       */
      triggers: {
        [key: string]: unknown
      }[]
      /**
       * Nodes
       * @description Execution and control nodes in the workflow graph
       */
      nodes: (
        | components['schemas']['AAPJobTemplateNode']
        | components['schemas']['AAPWorkflowJobTemplateNode']
        | components['schemas']['HTTPRequestNode']
        | components['schemas']['AgenticNode']
        | components['schemas']['ScriptNode']
        | components['schemas']['ApprovalNode']
        | components['schemas']['ConditionNode']
        | components['schemas']['SwitchNode']
        | components['schemas']['LoopNode']
        | components['schemas']['ConvergeNode']
        | components['schemas']['WaitNode']
      )[]
      /**
       * Edges
       * @description List of directed edges connecting triggers and nodes in the workflow graph
       */
      edges: {
        [key: string]: unknown
      }[]
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    /**
     * PreResolvedNodeOutput
     * @description Typed structure for a single pre-resolved node's mock output.
     */
    PreResolvedNodeOutput: {
      /**
       * Output
       * @description Mock output data for the node
       */
      output?: {
        [key: string]: unknown
      }
      /**
       * Control
       * @description Control data for condition/loop routing (e.g., next_port)
       */
      control?: {
        [key: string]: unknown
      } | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_executions: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  create_execution: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExecutionCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_execution: {
    parameters: {
      query?: {
        include?: string | null
      }
      header?: never
      path: {
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  cancel_execution: {
    parameters: {
      query?: never
      header?: never
      path: {
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cancellation request accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  retry_execution: {
    parameters: {
      query?: never
      header?: never
      path: {
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description New execution created from retry */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_execution_activities: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path: {
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityExecutionListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  signal_activity: {
    parameters: {
      query?: never
      header?: never
      path: {
        execution_id: string
        activity_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivitySignalPayload']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SignalResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
