/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/execution_plane/v1/execution_targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List execution targets
     * @description Retrieve registered execution targets.
     */
    get: operations['list_execution_targets']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/execution_plane/v1/work_items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List work items
     * @description Retrieve work items.
     */
    get: operations['list_work_items']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/execution_plane/v1/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit a cold-start execution-plane work item
     * @description Queue a JSONL task for execution on a matching registered target.
     */
    post: operations['submit_execution_plane_work_item']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * BackendType
     * @description Supported execution target backends.
     * @enum {string}
     */
    BackendType: 'vanilla_k8s' | 'openshell'
    /**
     * ExecutionTarget
     * @description A registered compute environment where worker pods run.
     */
    ExecutionTarget: {
      /**
       * Id
       * Format: uuid
       */
      id?: string
      /** Name */
      name: string
      backend_type: components['schemas']['BackendType']
      /** Endpoint */
      endpoint: string
      /** Namespace */
      namespace: string
      /**
       * Credential Ref
       * @default {}
       */
      credential_ref?: {
        [key: string]: unknown
      }
      /** @default registering */
      status?: components['schemas']['TargetStatus']
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean
      /**
       * Labels
       * @default {}
       */
      labels?: {
        [key: string]: unknown
      }
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Last Ran At */
      last_ran_at?: string | null
    }
    /**
     * ExecutionTargetListResponse
     * @description Paginated list response for ExecutionTarget.
     */
    ExecutionTargetListResponse: {
      /** Resources */
      resources: components['schemas']['ExecutionTarget'][]
      /** Next */
      next?: string | null
      /** Prev */
      prev?: string | null
      /** Total */
      total?: number | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * TargetStatus
     * @description Lifecycle states of an execution target.
     * @enum {string}
     */
    TargetStatus: 'registering' | 'validating' | 'bootstrapping' | 'active' | 'degraded' | 'failed'
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * WorkItemListResponse
     * @description Paginated list response for WorkItem.
     */
    WorkItemListResponse: {
      /** Resources */
      resources: components['schemas']['WorkItemRead'][]
      /** Next */
      next?: string | null
      /** Prev */
      prev?: string | null
      /** Total */
      total?: number | null
    }
    /**
     * WorkItemRead
     * @description Public work-item representation that excludes execution inputs and task tokens.
     */
    WorkItemRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Work Correlation Id
       * Format: uuid
       */
      work_correlation_id: string
      status: components['schemas']['WorkItemStatus']
      /** Execution Target Id */
      execution_target_id?: string | null
      /** Payload */
      payload: {
        [key: string]: unknown
      }
      /** Result */
      result?: {
        [key: string]: unknown
      } | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Claimed At */
      claimed_at?: string | null
      /** Completed At */
      completed_at?: string | null
      /** Signaled At */
      signaled_at?: string | null
    }
    /**
     * WorkItemStatus
     * @description Lifecycle states of a dispatched work item.
     * @enum {string}
     */
    WorkItemStatus: 'pending' | 'claimed' | 'dispatched' | 'completed' | 'failed' | 'cancelled'
    /**
     * WorkItemSubmit
     * @description Direct Task Executor submission request.
     */
    WorkItemSubmit: {
      /**
       * Work Correlation Id
       * Format: uuid
       */
      work_correlation_id?: string
      /** Activity Handle */
      activity_handle?: string | null
      /** Target Selector */
      target_selector?: {
        [key: string]: unknown
      }
      task_definition: components['schemas']['WorkerTaskDefinition']
    }
    /**
     * WorkerTaskDefinition
     * @description OCI image and JSONL invocation used for a cold-start worker.
     */
    WorkerTaskDefinition: {
      /** Image */
      image: string
      /** Pod Command */
      pod_command?: string[] | null
      /** Command */
      command: string[]
      /** Input */
      input: {
        [key: string]: unknown
      }
      /**
       * Timeout Seconds
       * @default 120
       */
      timeout_seconds?: number
      /**
       * Image Pull Policy
       * @default IfNotPresent
       */
      image_pull_policy?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_execution_targets: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionTargetListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_work_items: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkItemListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_execution_plane_work_item: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkItemSubmit']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkItemRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
