/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/execution_plane/v1/execution_targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List execution targets
     * @description Retrieve registered execution targets.
     */
    get: operations['list_execution_targets']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/execution_plane/v1/work_items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List work items
     * @description Retrieve work items.
     */
    get: operations['list_work_items']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * BackendType
     * @description Supported execution target backends.
     * @enum {string}
     */
    BackendType: 'vanilla_k8s' | 'openshell'
    /**
     * ExecutionTarget
     * @description A registered compute environment where worker pods run.
     */
    ExecutionTarget: {
      /**
       * Id
       * Format: uuid
       */
      id?: string
      /**
       * Cluster Id
       * Format: uuid
       */
      cluster_id: string
      /** Name */
      name: string
      backend_type: components['schemas']['BackendType']
      /** Endpoint */
      endpoint: string
      /** @default registering */
      status?: components['schemas']['TargetStatus']
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean
      /**
       * Is Default
       * @default false
       */
      is_default?: boolean
      /** Status Message */
      status_message?: string | null
      /**
       * Labels
       * @default {}
       */
      labels?: {
        [key: string]: unknown
      }
      /**
       * Created By
       * Format: uuid
       */
      created_by: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated By
       * Format: uuid
       */
      updated_by: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /** Last Ran At */
      last_ran_at?: string | null
    }
    /**
     * ExecutionTargetListResponse
     * @description Paginated list response for ExecutionTarget.
     */
    ExecutionTargetListResponse: {
      /** Resources */
      resources: components['schemas']['ExecutionTarget'][]
      /** Next */
      next?: string | null
      /** Prev */
      prev?: string | null
      /** Total */
      total?: number | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * TargetStatus
     * @description Lifecycle states of an execution target.
     * @enum {string}
     */
    TargetStatus: 'registering' | 'validating' | 'bootstrapping' | 'active' | 'degraded' | 'draining' | 'failed'
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * WorkItem
     * @description A unit of work written by the Temporal Worker and consumed by the Task Executor.
     */
    WorkItem: {
      /**
       * Id
       * Format: uuid
       */
      id?: string
      /**
       * Work Correlation Id
       * Format: uuid
       */
      work_correlation_id: string
      /** Activity Handle */
      activity_handle: string
      /** @default pending */
      status?: components['schemas']['WorkItemStatus']
      /** Execution Target Id */
      execution_target_id?: string | null
      /**
       * Payload
       * @default {}
       */
      payload?: {
        [key: string]: unknown
      }
      /** Result */
      result?: {
        [key: string]: unknown
      } | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Claimed At */
      claimed_at?: string | null
      /** Completed At */
      completed_at?: string | null
      /** Signaled At */
      signaled_at?: string | null
    }
    /**
     * WorkItemListResponse
     * @description Paginated list response for WorkItem.
     */
    WorkItemListResponse: {
      /** Resources */
      resources: components['schemas']['WorkItem'][]
      /** Next */
      next?: string | null
      /** Prev */
      prev?: string | null
      /** Total */
      total?: number | null
    }
    /**
     * WorkItemStatus
     * @description Lifecycle states of a dispatched work item.
     * @enum {string}
     */
    WorkItemStatus: 'pending' | 'claimed' | 'dispatched' | 'completed' | 'failed' | 'cancelled'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_execution_targets: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionTargetListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_work_items: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkItemListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
