/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/execution_plane/v1/execution_targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List execution targets
     * @description Retrieve registered execution targets.
     */
    get: operations['list_execution_targets']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/execution_plane/v1/work_items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List work items
     * @description Retrieve work items.
     */
    get: operations['list_work_items']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/execution_plane/v1/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Accept an Execution Plane completion event
     * @description Complete the AO async activity named by an EP completion callback; EP retries until 2xx.
     */
    post: operations['accept_execution_plane_event']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * EPCompletionEvent
     * @description Authenticated result event delivered by the independent EP service.
     */
    EPCompletionEvent: {
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string
      /**
       * Event Schema Version
       * @constant
       */
      event_schema_version: 1
      /** Client Id */
      client_id: string
      /**
       * Work Id
       * Format: uuid
       */
      work_id: string
      /** State Revision */
      state_revision: number
      /**
       * Status
       * @enum {string}
       */
      status: 'completed' | 'failed' | 'cancelled' | 'reconciliation_required'
      /** Result */
      result: {
        [key: string]: unknown
      }
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string
    }
    /**
     * ExecutionTargetFacadeRead
     * @description Safe target fields available to AO's authorized management API.
     */
    ExecutionTargetFacadeRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Cluster Id
       * Format: uuid
       */
      cluster_id: string
      /** Name */
      name: string
      /** Backend Type */
      backend_type: string
      /** Endpoint */
      endpoint: string
      /** Placement */
      placement: components['schemas']['KubernetesPlacement'] | components['schemas']['RHELPlacement']
      /** Status */
      status: string
      /** Enabled */
      enabled: boolean
      /** Is Default */
      is_default: boolean
      /** Status Message */
      status_message?: string | null
      /** Labels */
      labels: {
        [key: string]: string
      }
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Last Ran At */
      last_ran_at?: string | null
    }
    /**
     * ExecutionTargetListResponse
     * @description Paginated list response for ExecutionTarget.
     */
    ExecutionTargetListResponse: {
      /** Resources */
      resources: components['schemas']['ExecutionTargetFacadeRead'][]
      /** Next */
      next?: string | null
      /** Prev */
      prev?: string | null
      /** Total */
      total?: number | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * KubernetesPlacement
     * @description Kubernetes scheduling metadata returned by the Execution Plane.
     */
    KubernetesPlacement: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'kubernetes'
      /** Namespace */
      namespace: string
      /** Node Selectors */
      node_selectors?: string[]
      /** Tolerations */
      tolerations?: string[]
    }
    /**
     * RHELPlacement
     * @description RHEL placement marker returned by the Execution Plane.
     */
    RHELPlacement: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'rhel'
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * WorkItemFacadeRead
     * @description Safe work state; internal tokens and storage metadata stay private.
     */
    WorkItemFacadeRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Status */
      status: string
      /** Result */
      result?: {
        [key: string]: unknown
      } | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Claimed At */
      claimed_at?: string | null
      /** Completed At */
      completed_at?: string | null
    }
    /**
     * WorkItemListResponse
     * @description Paginated list response for WorkItem.
     */
    WorkItemListResponse: {
      /** Resources */
      resources: components['schemas']['WorkItemFacadeRead'][]
      /** Next */
      next?: string | null
      /** Prev */
      prev?: string | null
      /** Total */
      total?: number | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_execution_targets: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionTargetListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_work_items: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkItemListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  accept_execution_plane_event: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EPCompletionEvent']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
