/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload files (design time)
     * @description Upload files independently of invocations for later use in agent execution. Returns file_ids that can be stored in workflow configuration and passed to invocations. Files are validated, stored, and queued for document conversion.
     */
    post: operations['upload_files']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/storage_status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get File Storage Status
     * @description Report whether the S3-compatible object storage backend is configured and reachable. Clients use this to disable file upload controls when uploads cannot succeed. Object storage is not a hard dependency of the API, so this is reported here rather than on the readiness probe.
     */
    get: operations['get_file_storage_status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/metadata': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get files metadata (batch)
     * @description Retrieve metadata for one or more files by their IDs. Returns file information (filename, size, MIME type, status) without file content.
     */
    get: operations['get_files_metadata']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/{file_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get File Details
     * @description Retrieve metadata and conversion status for a single file by its ID. Use this endpoint to poll for conversion status after upload.
     */
    get: operations['get_file_details']
    put?: never
    post?: never
    /**
     * Delete file
     * @description Permanently delete a file and its stored content. After a project is soft-deleted, project-scoped files:delete cannot authorize orphan cleanup (the project no longer resolves). Only system-scope files:delete can remove an orphan, and only when the caller already knows the file UUID.
     */
    delete: operations['delete_file']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/{file_id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download file
     * @description Download a file by its ID. Serves the file from whichever storage backend it was uploaded to.
     */
    get: operations['download_file']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * FileStorageStatus
     * @description Availability of the S3-compatible object storage backend.
     * @enum {string}
     */
    FileStorageStatus: 'ok' | 'degraded' | 'unconfigured' | 'error'
    /**
     * FileStorageStatusResponse
     * @description Response model for GET /files/storage_status endpoint.
     */
    FileStorageStatusResponse: {
      /**
       * @description Availability of the object storage backend. Anything other than 'ok' means file uploads are unavailable.
       * @example ok
       */
      status: components['schemas']['FileStorageStatus']
    }
    /**
     * UploadFilesBody
     * @description Request body for POST /files endpoint.
     */
    UploadFilesBody: {
      /**
       * Files
       * @description Files to upload (1-10 files, max 10MB each)
       */
      files: string[]
      /**
       * Project Id
       * Format: uuid
       * @description Project to associate files with
       */
      project_id: string
    }
    /**
     * FileUploadResponse
     * @description Response model for POST /api/v1/files endpoint.
     */
    FileUploadResponse: {
      /**
       * File IDs
       * @description List of file IDs for later reference in invocations
       * @example [
       *       "550e8400-e29b-41d4-a716-446655440000"
       *     ]
       */
      file_ids: string[]
      /**
       * Files
       * @description Metadata for each uploaded file
       */
      files: components['schemas']['FileUploadInfo'][]
    }
    /**
     * FileUploadInfo
     * @description Response model for individual file upload information.
     *
     *     Security Note:
     *         file_path is intentionally excluded from this model to prevent
     *         exposing internal filesystem paths in API responses.
     */
    FileUploadInfo: {
      /**
       * File ID
       * Format: uuid
       * @description Unique file identifier (UUID)
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      file_id: string
      /**
       * Filename
       * @description Original filename from upload
       * @example document.pdf
       */
      filename: string
      /**
       * Size Bytes
       * @description File size in bytes
       * @example 524288
       */
      size_bytes: number
      /**
       * MIME Type
       * @description Detected MIME type of the file
       * @example application/pdf
       */
      mime_type: string
      /** @description Processing status (pending_conversion) */
      status: components['schemas']['FileStatus']
      /**
       * Is Project Deleted
       * @description True when the owning project has been soft-deleted; the file is retained as an orphan. Null when not computed (e.g. upload response).
       */
      is_project_deleted?: boolean | null
    }
    /**
     * FileDetailResponse
     * @description Response model for GET /api/v1/files/{file_id} endpoint.
     */
    FileDetailResponse: {
      /**
       * File ID
       * Format: uuid
       * @description Unique file identifier (UUID)
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      file_id: string
      /**
       * Filename
       * @description Original filename from upload
       * @example document.pdf
       */
      filename: string
      /**
       * Size Bytes
       * @description File size in bytes
       * @example 524288
       */
      size_bytes: number
      /**
       * MIME Type
       * @description Detected MIME type of the file
       * @example application/pdf
       */
      mime_type: string
      /** @description Current processing status */
      status: components['schemas']['FileStatus']
      /**
       * Conversion Error
       * @description Error message if conversion failed
       * @example null
       */
      conversion_error?: string | null
      /**
       * Is Project Deleted
       * @description True when the owning project has been soft-deleted; the file is retained as an orphan. Project-scoped files:delete cannot remove orphans after soft-delete; only system-scope files:delete with a known file UUID can.
       */
      is_project_deleted: boolean
    }
    /**
     * FilesMetadataResponse
     * @description Response model for GET /files/metadata endpoint.
     */
    FilesMetadataResponse: {
      /**
       * Files
       * @description Metadata for each found file (missing IDs are silently omitted)
       */
      files: components['schemas']['FileUploadInfo'][]
    }
    /**
     * FileStatus
     * @description Status enum for file conversion lifecycle.
     *
     *     States:
     *         PENDING_CONVERSION: File uploaded, waiting for conversion
     *         CONVERTING: Conversion in progress
     *         CONVERTED: Successfully converted to text/markdown
     *         CONVERSION_FAILED: Conversion failed with error
     * @enum {string}
     */
    FileStatus: 'pending_conversion' | 'converting' | 'converted' | 'conversion_failed'
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  upload_files: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['UploadFilesBody']
      }
    }
    responses: {
      /** @description Files uploaded successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileUploadResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_file_storage_status: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileStorageStatusResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_files_metadata: {
    parameters: {
      query: {
        /** @description List of file IDs to retrieve metadata for */
        file_ids: string[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FilesMetadataResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_file_details: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description UUID of the file */
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileDetailResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_file: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description UUID of the file to delete */
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description File deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  download_file: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description UUID of the file to download */
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description File content as binary stream */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/octet-stream': string
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
