/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/identity_providers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List identity providers
     * @description List identity providers with filtering, sorting, and pagination.
     */
    get: operations['list_identity_providers']
    put?: never
    /**
     * Create identity provider
     * @description Create a new identity provider.
     */
    post: operations['create_identity_provider']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/identity_providers/{provider_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get identity provider
     * @description Get identity provider details by ID.
     */
    get: operations['get_identity_provider']
    put?: never
    post?: never
    /**
     * Delete identity provider
     * @description Soft delete an identity provider.
     */
    delete: operations['delete_identity_provider']
    options?: never
    head?: never
    /**
     * Update identity provider
     * @description Update an identity provider.
     */
    patch: operations['update_identity_provider']
    trace?: never
  }
  '/identity_providers/setup_aap_oidc': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Setup Ansible Automation Platform OIDC provider
     * @description Push-button setup: connects to Ansible Automation Platform, creates an OAuth2 application, and configures the identity provider with Ansible Automation Platform defaults.
     */
    post: operations['setup_aap_oidc_provider']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/identity_providers/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Test identity provider
     * @description Test identity provider connection without saving. Requires authentication.
     */
    post: operations['test_identity_provider']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * OIDCClaimMapping
     * @description Maps Nexus user fields to IdP-specific OIDC claim names.
     */
    OIDCClaimMapping: {
      /**
       * Subject
       * @default sub
       */
      subject?: string
      /**
       * Email
       * @default email
       */
      email?: string
      /**
       * Username
       * @default preferred_username
       */
      username?: string
      /**
       * First Name
       * @default given_name
       */
      first_name?: string
      /**
       * Last Name
       * @default family_name
       */
      last_name?: string
    }
    /**
     * OIDCGroupMappingEntry
     * @description API-facing schema for a single IdP-to-Nexus group mapping entry.
     *
     *     Used in API requests/responses. Actual storage is in the
     *     ``idp_group_mapping_entries`` table.
     */
    OIDCGroupMappingEntry: {
      /**
       * Idp Group Value
       * @description Group value from the IdP token (e.g. GUID or role name)
       */
      idp_group_value: string
      /**
       * Mapped Group Id
       * Format: uuid
       * @description ID of the group to map to
       */
      mapped_group_id: string
    }
    /**
     * OIDCConfiguration
     * @description Configuration for OIDC (OpenID Connect) providers.
     */
    OIDCConfiguration: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      provider_type: 'oidc'
      /**
       * Idp Type
       * @description Identity provider type hint. Known values: aap, custom
       */
      idp_type?: string | null
      /**
       * Auto Discovery
       * @description Use OIDC auto-discovery via .well-known endpoint
       * @default true
       */
      auto_discovery?: boolean
      /**
       * Issuer Url
       * Format: uri
       * @description OIDC issuer URL (e.g. https://accounts.google.com)
       */
      issuer_url: string
      /**
       * Client Id
       * @description OAuth 2.0 client ID
       */
      client_id: string
      /**
       * Client Secret
       * @description OAuth 2.0 client secret
       */
      client_secret?: string | null
      /**
       * Redirect Uri
       * Format: uri
       * @description OAuth 2.0 redirect URI
       */
      redirect_uri: string
      /**
       * Scopes
       * @description Space-separated list of OAuth 2.0 scopes
       * @default openid profile email
       */
      scopes?: string
      /**
       * Authorization Endpoint
       * @description Authorization endpoint URL
       */
      authorization_endpoint?: string | null
      /**
       * Token Endpoint
       * @description Token endpoint URL
       */
      token_endpoint?: string | null
      /**
       * Jwks Uri
       * @description JWKS URI for token verification
       */
      jwks_uri?: string | null
      /**
       * Userinfo Endpoint
       * @description Userinfo endpoint URL (optional)
       */
      userinfo_endpoint?: string | null
      /**
       * End Session Endpoint
       * @description OIDC end session endpoint URL for RP-initiated logout
       */
      end_session_endpoint?: string | null
      /**
       * Enable Rp Initiated Logout
       * @description Enable RP-initiated logout redirect to IdP when user logs out
       * @default false
       */
      enable_rp_initiated_logout?: boolean
      claim_mapping?: components['schemas']['OIDCClaimMapping']
      /**
       * Group Jmespath Expression
       * @description JMESPath expression to extract group values from token claims
       */
      group_jmespath_expression?: string | null
      /**
       * Group Mapping Entries
       * @description IdP-to-Nexus group mapping entries
       */
      group_mapping_entries?: components['schemas']['OIDCGroupMappingEntry'][]
      /**
       * Allow All Authenticated
       * @description Allow all users from this IdP to log in regardless of group mapping results
       * @default false
       */
      allow_all_authenticated?: boolean
      /**
       * Aap Role Mapping Enabled
       * @description Map Ansible Automation Platform aap_system_role claim to built-in groups
       * @default false
       */
      aap_role_mapping_enabled?: boolean
      /**
       * Disable Tls Verify
       * @description Disable TLS certificate verification for requests to this identity provider (insecure)
       * @default false
       */
      disable_tls_verify?: boolean
    }
    /**
     * OIDCConfigurationResponse
     * @description Response schema for OIDC configuration (excludes client_secret).
     */
    OIDCConfigurationResponse: {
      /**
       * Provider Type
       * @default oidc
       * @constant
       */
      provider_type?: 'oidc'
      /**
       * Idp Type
       * @description Identity provider type hint
       */
      idp_type?: string | null
      /**
       * Auto Discovery
       * @description Use OIDC auto-discovery via .well-known endpoint
       * @default true
       */
      auto_discovery?: boolean
      /**
       * Issuer Url
       * Format: uri
       * @description OIDC issuer URL (e.g. https://accounts.google.com)
       */
      issuer_url: string
      /**
       * Client Id
       * @description OAuth 2.0 client ID
       */
      client_id: string
      /**
       * Redirect Uri
       * Format: uri
       * @description OAuth 2.0 redirect URI
       */
      redirect_uri: string
      /**
       * Scopes
       * @description Space-separated list of OAuth 2.0 scopes
       * @default openid profile email
       */
      scopes?: string
      /**
       * Authorization Endpoint
       * @description Authorization endpoint URL
       */
      authorization_endpoint?: string | null
      /**
       * Token Endpoint
       * @description Token endpoint URL
       */
      token_endpoint?: string | null
      /**
       * Jwks Uri
       * @description JWKS URI for token verification
       */
      jwks_uri?: string | null
      /**
       * Userinfo Endpoint
       * @description Userinfo endpoint URL (optional)
       */
      userinfo_endpoint?: string | null
      /**
       * End Session Endpoint
       * @description OIDC end session endpoint URL for RP-initiated logout
       */
      end_session_endpoint?: string | null
      /**
       * Enable Rp Initiated Logout
       * @description Enable RP-initiated logout redirect to IdP when user logs out
       * @default false
       */
      enable_rp_initiated_logout?: boolean
      claim_mapping?: components['schemas']['OIDCClaimMapping']
      /**
       * Group Jmespath Expression
       * @description JMESPath expression for group extraction
       */
      group_jmespath_expression?: string | null
      /**
       * Group Mapping Entries
       * @description IdP-to-Nexus group mapping entries
       */
      group_mapping_entries?: components['schemas']['OIDCGroupMappingEntry'][]
      /**
       * Allow All Authenticated
       * @description Allow all users from this IdP to log in regardless of group mapping results
       * @default false
       */
      allow_all_authenticated?: boolean
      /**
       * Aap Role Mapping Enabled
       * @description Map Ansible Automation Platform aap_system_role claim to built-in groups
       * @default false
       */
      aap_role_mapping_enabled?: boolean
      /**
       * Disable Tls Verify
       * @description Disable TLS certificate verification for requests to this identity provider (insecure)
       * @default false
       */
      disable_tls_verify?: boolean
    }
    /**
     * OIDCConfigurationUpdate
     * @description Update schema for OIDC configuration (client_secret optional — preserves existing if omitted).
     */
    OIDCConfigurationUpdate: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      provider_type: 'oidc'
      /**
       * Idp Type
       * @description Identity provider type hint. Known values: aap, custom
       */
      idp_type?: string | null
      /**
       * Auto Discovery
       * @description Use OIDC auto-discovery via .well-known endpoint
       * @default true
       */
      auto_discovery?: boolean
      /**
       * Issuer Url
       * Format: uri
       * @description OIDC issuer URL (e.g. https://accounts.google.com)
       */
      issuer_url: string
      /**
       * Client Id
       * @description OAuth 2.0 client ID
       */
      client_id: string
      /**
       * Client Secret
       * @description OAuth 2.0 client secret (omit to keep existing)
       */
      client_secret?: string | null
      /**
       * Redirect Uri
       * Format: uri
       * @description OAuth 2.0 redirect URI
       */
      redirect_uri: string
      /**
       * Scopes
       * @description Space-separated list of OAuth 2.0 scopes
       * @default openid profile email
       */
      scopes?: string
      /**
       * Authorization Endpoint
       * @description Authorization endpoint URL
       */
      authorization_endpoint?: string | null
      /**
       * Token Endpoint
       * @description Token endpoint URL
       */
      token_endpoint?: string | null
      /**
       * Jwks Uri
       * @description JWKS URI for token verification
       */
      jwks_uri?: string | null
      /**
       * Userinfo Endpoint
       * @description Userinfo endpoint URL (optional)
       */
      userinfo_endpoint?: string | null
      /**
       * End Session Endpoint
       * @description OIDC end session endpoint URL for RP-initiated logout (omit to keep existing)
       */
      end_session_endpoint?: string | null
      /**
       * Enable Rp Initiated Logout
       * @description Enable RP-initiated logout redirect to IdP when user logs out (omit to keep existing)
       */
      enable_rp_initiated_logout?: boolean | null
      /** @description OIDC claim mapping (omit to keep existing) */
      claim_mapping?: components['schemas']['OIDCClaimMapping'] | null
      /**
       * Group Jmespath Expression
       * @description JMESPath expression for group extraction (omit to keep existing)
       */
      group_jmespath_expression?: string | null
      /**
       * Group Mapping Entries
       * @description IdP-to-Nexus group mapping entries (omit to keep existing)
       */
      group_mapping_entries?: components['schemas']['OIDCGroupMappingEntry'][] | null
      /**
       * Allow All Authenticated
       * @description Allow all users from this IdP to log in regardless of group mapping results (omit to keep existing)
       */
      allow_all_authenticated?: boolean | null
      /**
       * Aap Role Mapping Enabled
       * @description Map Ansible Automation Platform aap_system_role claim to built-in groups (omit to keep existing)
       */
      aap_role_mapping_enabled?: boolean | null
      /**
       * Disable Tls Verify
       * @description Disable TLS certificate verification for this identity provider (omit to keep existing)
       */
      disable_tls_verify?: boolean | null
    }
    /**
     * IdentityProviderCreate
     * @description Schema for creating a new identity provider.
     */
    IdentityProviderCreate: {
      /**
       * Name
       * @description Human-readable name for the provider
       */
      name: string
      /**
       * Description
       * @description Detailed description of the provider
       */
      description?: string | null
      /**
       * Configuration
       * @description Provider configuration
       */
      configuration: components['schemas']['OIDCConfiguration']
    }
    /**
     * IdentityProviderUpdate
     * @description Schema for partially updating an identity provider.
     */
    IdentityProviderUpdate: {
      /**
       * Name
       * @description Human-readable name for the provider
       */
      name?: string | null
      /**
       * Description
       * @description Detailed description of the provider
       */
      description?: string | null
      /**
       * Configuration
       * @description Provider-specific configuration (client_secret optional — preserves existing if omitted)
       */
      configuration?: components['schemas']['OIDCConfigurationUpdate'] | null
      /**
       * Enabled
       * @description Enable/disable the provider
       */
      enabled?: boolean | null
    }
    /**
     * IdentityProviderRead
     * @description Schema for IdentityProvider response with configuration details (excludes secrets).
     */
    IdentityProviderRead: components['schemas']['UserOwnedResource'] &
      components['schemas']['NamedResource'] & {
        /** @description Human-readable provider name */
        name?: unknown
        /**
         * Enabled
         * @description Enable/disable the identity provider
         * @default true
         */
        enabled?: boolean
        /** @description Identity provider configuration */
        configuration: components['schemas']['OIDCConfigurationResponse']
      }
    /**
     * IdentityProviderListResponse
     * @description Paginated list response for identity providers.
     */
    IdentityProviderListResponse: components['schemas']['ResourcesResponseBase'] & {
      resources: components['schemas']['IdentityProviderRead'][]
    }
    /**
     * OIDCTestRequest
     * @description Request body for testing an OIDC connection.
     */
    OIDCTestRequest: {
      /**
       * Name
       * @description Human-readable name for the provider
       */
      name: string
      /**
       * Description
       * @description Detailed description of the provider
       */
      description?: string | null
      /**
       * Configuration
       * @description Provider configuration
       */
      configuration: components['schemas']['OIDCConfiguration']
    }
    /**
     * OIDCTestResult
     * @description Result of an OIDC connection test.
     */
    OIDCTestResult: {
      /** Success */
      success: boolean
      /** Message */
      message: string
      /** Metadata */
      metadata?: {
        [key: string]: string
      } | null
      /** Claims Supported */
      claims_supported?: string[] | null
      /** Claim Aliases */
      claim_aliases?: {
        [key: string]: string[]
      } | null
      /**
       * End Session Endpoint Supported
       * @default false
       */
      end_session_endpoint_supported?: boolean
    }
    /**
     * AAPOIDCSetupRequest
     * @description Request body for push-button Ansible Automation Platform OIDC identity provider setup.
     */
    AAPOIDCSetupRequest: {
      /**
       * Ansible Automation Platform URL
       * @description Ansible Automation Platform base URL (e.g., https://aap.example.com)
       */
      aap_url: string
      /**
       * Organization
       * @description Ansible Automation Platform organization name to create the OAuth2 application in
       * @default Default
       */
      organization?: string
      /**
       * Platform Admin Username
       * @description Ansible Automation Platform platform admin username (required when using basic auth)
       */
      admin_username?: string | null
      /**
       * Platform Admin Password
       * Format: password
       * @description Ansible Automation Platform platform admin password (used only for setup, never stored)
       */
      admin_password?: string | null
      /**
       * Personal Access Token
       * Format: password
       * @description Ansible Automation Platform personal access token (alternative to username/password, never stored)
       */
      personal_access_token?: string | null
      /**
       * Insecure Skip TLS Verify
       * @description Skip TLS certificate verification for the Ansible Automation Platform connection
       * @default false
       */
      insecure_skip_tls_verify?: boolean
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponseBase: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources?: unknown[]
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    UserOwnedResource: components['schemas']['BaseResource'] & {
      /**
       * Created By
       * Format: uuid
       * @description User (or automation) that created the resource
       * @example 770e8400-e29b-41d4-a716-446655440000
       */
      readonly created_by: string
      /**
       * Updated By
       * @description User (or automation) that last updated the resource
       * @example 880e8400-e29b-41d4-a716-446655440000
       */
      readonly updated_by?: string | null
    }
    NamedResource: components['schemas']['BaseResource'] & {
      /**
       * Name
       * @description Human-readable name for the resource
       * @example Authentication Service
       */
      name: string
      /**
       * Description
       * @description Detailed description of the resource
       * @example Handles user authentication and authorization workflows
       */
      description?: string | null
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_identity_providers: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of identity providers */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityProviderListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  create_identity_provider: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IdentityProviderCreate']
      }
    }
    responses: {
      /** @description Identity provider created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityProviderRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_identity_provider: {
    parameters: {
      query?: never
      header?: never
      path: {
        provider_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Identity provider details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityProviderRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_identity_provider: {
    parameters: {
      query?: never
      header?: never
      path: {
        provider_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Identity provider deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  update_identity_provider: {
    parameters: {
      query?: never
      header?: never
      path: {
        provider_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IdentityProviderUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityProviderRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  setup_aap_oidc_provider: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AAPOIDCSetupRequest']
      }
    }
    responses: {
      /** @description Ansible Automation Platform OIDC provider created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityProviderRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  test_identity_provider: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OIDCTestRequest']
      }
    }
    responses: {
      /** @description Test results */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OIDCTestResult']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
