/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/integrations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List integrations
     * @description List integrations with filtering and pagination.
     */
    get: operations['list_integrations']
    put?: never
    /**
     * Create integration
     * @description Create a new integration.
     */
    post: operations['create_integration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get integration
     * @description Get an integration by ID.
     */
    get: operations['get_integration']
    put?: never
    post?: never
    /**
     * Delete integration
     * @description Delete an integration.
     */
    delete: operations['delete_integration']
    options?: never
    head?: never
    /**
     * Update integration
     * @description Update an integration.
     */
    patch: operations['update_integration']
    trace?: never
  }
  '/integrations/discover': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Discover integration connection
     * @description Test a connection and discover resources without saving an integration.
     *
     *     Accepts integration configuration and a credential ID, resolves the
     *     credential, runs the adapter's discover() method, and returns the result
     *     including discovered tools (with parameters) or models. No integration
     *     is persisted.
     */
    post: operations['discover_integration_connection']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/validate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Validate integration
     * @description Validate a saved integration with a lightweight connectivity ping.
     *
     *     Resolves the management credential, dispatches to the type-specific
     *     adapter's validate() method, updates the integration's status fields,
     *     and returns the result. No tool sync is performed.
     */
    post: operations['validate_integration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh resources
     * @description Sync resources (tools) for a saved integration from the external service.
     *
     *     Connects to the MCP server, fetches the current tool list, and upserts
     *     Tool records in the database. Updates refresh_status and last_refreshed_at
     *     on the integration. Only supported for mcp_server integration types.
     */
    post: operations['refresh_resources']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List integration projects
     * @description List project assignments for an integration.
     */
    get: operations['list_integration_projects']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/projects/{project_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Assign integration project
     * @description Assign a project to a project-scoped integration.
     */
    post: operations['assign_integration_project']
    /**
     * Unassign integration project
     * @description Remove a project assignment from an integration.
     */
    delete: operations['unassign_integration_project']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List integration models
     * @description List LLM models for an integration with filtering, sorting, and pagination.
     */
    get: operations['list_integration_models']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/models/{model_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get integration model
     * @description Get an LLM model by ID.
     */
    get: operations['get_integration_model']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update integration model
     * @description Update an LLM model (enable/disable).
     */
    patch: operations['update_integration_model']
    trace?: never
  }
  '/integrations/{integration_id}/models/bulk_update': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Bulk update integration models
     * @description Bulk enable/disable LLM models.
     */
    patch: operations['bulk_update_integration_models']
    trace?: never
  }
  '/integrations/{integration_id}/tools': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Integration Tools
     * @description List tools for an integration with filtering, sorting, and pagination.
     */
    get: operations['list_integration_tools']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/integrations/{integration_id}/tools/{tool_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Integration Tool
     * @description Get a tool by ID, scoped to an integration.
     */
    get: operations['get_integration_tool']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update Integration Tool
     * @description Update a tool (enable/disable), scoped to an integration.
     */
    patch: operations['update_integration_tool']
    trace?: never
  }
  '/integrations/{integration_id}/tools/bulk_update': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Bulk Update Integration Tools
     * @description Bulk enable/disable tools for an integration.
     */
    patch: operations['bulk_update_integration_tools']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * IntegrationType
     * @description Type of external integration.
     * @enum {string}
     */
    IntegrationType: 'mcp_server' | 'llm_provider' | 'ansible_automation_platform'
    /**
     * IntegrationStatus
     * @description Validation status of an integration.
     * @enum {string}
     */
    IntegrationStatus: 'unknown' | 'validating' | 'available' | 'error'
    /**
     * IntegrationScope
     * @description Visibility scope of an integration.
     * @enum {string}
     */
    IntegrationScope: 'global' | 'project'
    /**
     * IntegrationProjectAssignmentRead
     * @description Read schema for a single project assignment.
     */
    IntegrationProjectAssignmentRead: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string
      /** Project Name */
      project_name: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    IntegrationProjectAssignmentListResponse: components['schemas']['ResourcesResponseBase'] & {
      /** Resources */
      resources: components['schemas']['IntegrationProjectAssignmentRead'][]
    }
    /**
     * IntegrationListResponse
     * @description Paginated list response for integrations.
     */
    IntegrationListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['IntegrationRead'][]
    }
    /**
     * IntegrationCreate
     * @description Schema for creating a new integration.
     */
    IntegrationCreate: {
      /**
       * Name
       * @description Human-readable name for the integration
       */
      name: string
      /**
       * Description
       * @description Detailed description of the integration
       */
      description?: string | null
      /** @description Type of external integration */
      integration_type: components['schemas']['IntegrationType']
      /**
       * Configuration
       * @description Integration-specific configuration
       */
      configuration:
        | components['schemas']['MCPServerConfigurationInput']
        | components['schemas']['LLMProviderConfiguration']
        | components['schemas']['AAPConfiguration']
      /**
       * Management Credential Id
       * @description Optional credential for admin operations
       */
      management_credential_id?: string | null
      /**
       * Enabled
       * @description Whether the integration is active
       * @default true
       */
      enabled?: boolean
      /**
       * @description Visibility scope: global or project
       * @default global
       */
      scope?: components['schemas']['IntegrationScope']
      /**
       * Labels
       * @description Key-value labels
       */
      labels?: {
        [key: string]: string
      }
      /**
       * Discovered Tools
       * @description Tools discovered during setup with enabled/disabled selections
       */
      discovered_tools?: components['schemas']['InitialToolSelection'][] | null
      /**
       * Discovered Models
       * @description Models discovered during setup with enabled/disabled selections
       */
      discovered_models?: components['schemas']['InitialModelSelection'][] | null
    }
    /**
     * InitialToolSelection
     * @description A tool from the discover step with the user's enabled/disabled choice.
     */
    InitialToolSelection: {
      /**
       * Name
       * @description Tool name as returned by the discover endpoint
       */
      name: string
      /**
       * Description
       * @description Tool description
       */
      description?: string | null
      /**
       * Enabled
       * @description Whether the user enabled this tool
       * @default true
       */
      enabled?: boolean
      /**
       * Parameters
       * @description Tool parameters from discovery
       */
      parameters?:
        | {
            [key: string]: unknown
          }[]
        | null
    }
    /**
     * InitialModelSelection
     * @description A model from the discover step with the user's enabled/disabled choice.
     */
    InitialModelSelection: {
      /**
       * Model Id
       * @description Provider model identifier from discover
       */
      model_id: string
      /**
       * Name
       * @description Human-readable display name
       */
      name: string
      /**
       * Description
       * @description Model description
       */
      description?: string | null
      /**
       * Enabled
       * @description Whether the user enabled this model
       * @default true
       */
      enabled?: boolean
      /**
       * Is Default
       * @description Whether this is the default model
       * @default false
       */
      is_default?: boolean
    }
    /**
     * IntegrationUpdate
     * @description Schema for partially updating an integration (user-facing).
     */
    IntegrationUpdate: {
      /**
       * Name
       * @description Human-readable name for the integration
       */
      name?: string | null
      /**
       * Description
       * @description Detailed description of the integration
       */
      description?: string | null
      /**
       * Configuration
       * @description Integration-specific configuration
       */
      configuration?:
        | (
            | components['schemas']['MCPServerConfigurationInput']
            | components['schemas']['LLMProviderConfiguration']
            | components['schemas']['AAPConfiguration']
          )
        | null
      /**
       * Management Credential Id
       * @description Optional credential for admin operations
       */
      management_credential_id?: string | null
      /**
       * Enabled
       * @description Whether the integration is active
       */
      enabled?: boolean | null
      /** @description Visibility scope: global or project */
      scope?: components['schemas']['IntegrationScope'] | null
      /**
       * Labels
       * @description Key-value labels
       */
      labels?: {
        [key: string]: string
      } | null
    }
    /**
     * IntegrationTestConnection
     * @description Schema for testing a connection without saving an integration.
     */
    IntegrationTestConnection: {
      /** @description Type of external integration */
      integration_type: components['schemas']['IntegrationType']
      /**
       * Configuration
       * @description Integration-specific configuration
       */
      configuration:
        | components['schemas']['MCPServerConfigurationInput']
        | components['schemas']['LLMProviderConfiguration']
        | components['schemas']['AAPConfiguration']
      /**
       * Credential Id
       * @description Credential to use for the connection test
       */
      credential_id?: string | null
    }
    /** @description Schema for integration API responses. */
    IntegrationRead: components['schemas']['UserOwnedResource'] &
      components['schemas']['NamedResource'] & {
        /**
         * Created By
         * @description Username or UUID of the creator
         */
        created_by?: string | null
        /**
         * Updated By
         * @description Username or UUID of the last modifier
         */
        updated_by?: string | null
        integration_type: components['schemas']['IntegrationType']
        /**
         * Enabled
         * @default true
         */
        enabled?: boolean
        /** @default unknown */
        validation_status?: components['schemas']['IntegrationStatus']
        /** @default global */
        scope?: components['schemas']['IntegrationScope']
        /**
         * Configuration
         * @description Integration-specific configuration
         */
        configuration:
          | components['schemas']['MCPServerConfigurationInput']
          | components['schemas']['LLMProviderConfiguration']
          | components['schemas']['AAPConfiguration']
        /** Last Validated At */
        last_validated_at?: string | null
        /** Management Credential Id */
        management_credential_id?: string | null
        /** Validation Error */
        validation_error?: string | null
        refresh_status?: components['schemas']['IntegrationRefreshStatus'] | null
        /** Last Refreshed At */
        last_refreshed_at?: string | null
        /** Last Successful Refresh At */
        last_successful_refresh_at?: string | null
        /** Refresh Error */
        refresh_error?: string | null
        /**
         * Project Ids
         * @description IDs of projects this integration is assigned to (empty for global scope)
         */
        project_ids?: string[]
        /**
         * Total Tool Count
         * @description Total number of tools linked to this integration
         * @default 0
         */
        total_tool_count?: number
        /**
         * Enabled Tool Count
         * @description Number of enabled tools linked to this integration
         * @default 0
         */
        enabled_tool_count?: number
        /**
         * Total Model Count
         * @description Total number of models linked to this integration
         * @default 0
         */
        total_model_count?: number
        /**
         * Enabled Model Count
         * @description Number of enabled models linked to this integration
         * @default 0
         */
        enabled_model_count?: number
      }
    /**
     * MCPServerConfigurationInput
     * @description Admin-provided fields for MCP server integrations (used by create/patch).
     */
    MCPServerConfigurationInput: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      integration_type: 'mcp_server'
      /**
       * Base Url
       * Format: uri
       * @description Base URL for the MCP server
       */
      base_url: string
      /**
       * Allow Http
       * @description Allow HTTP (unencrypted) connections. Loopback addresses are always permitted over HTTP.
       * @default false
       */
      allow_http?: boolean
      /**
       * Insecure Skip Tls Verify
       * @description Disable TLS certificate verification for connections to this integration.
       * @default false
       */
      insecure_skip_tls_verify?: boolean
      /**
       * Ca Certificate
       * @description PEM-encoded CA certificate to trust for this integration's TLS connections.
       */
      ca_certificate?: string | null
    }
    /**
     * LLMProviderHint
     * @description LLM provider backend type.
     * @enum {string}
     */
    LLMProviderHint: 'red_hat_ai' | 'openai' | 'anthropic' | 'gemini' | 'custom'
    /**
     * LLMProviderConfiguration
     * @description Configuration for LLM provider integrations.
     */
    LLMProviderConfiguration: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      integration_type: 'llm_provider'
      /** @description LLM provider backend type */
      provider_hint: components['schemas']['LLMProviderHint']
      /**
       * Base Url
       * Format: uri
       * @description Base URL for the LLM provider API. Required for red_hat_ai and custom providers.
       */
      base_url?: string | null
      /**
       * Allow Http
       * @description Allow HTTP (unencrypted) connections. Loopback addresses are always permitted over HTTP.
       * @default false
       */
      allow_http?: boolean
      /**
       * Insecure Skip Tls Verify
       * @description Disable TLS certificate verification for connections to this integration.
       * @default false
       */
      insecure_skip_tls_verify?: boolean
      /**
       * Ca Certificate
       * @description PEM-encoded CA certificate to trust for this integration's TLS connections.
       */
      ca_certificate?: string | null
    }
    /**
     * AAPConfiguration
     * @description Configuration for Ansible Automation Platform integrations.
     */
    AAPConfiguration: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      integration_type: 'ansible_automation_platform'
      /**
       * AAP URL
       * Format: uri
       * @description URL of the Ansible Automation Platform
       */
      base_url: string
      /**
       * Allow Http
       * @description Allow HTTP (unencrypted) connections. Loopback addresses are always permitted over HTTP.
       * @default false
       */
      allow_http?: boolean
      /**
       * Insecure Skip Tls Verify
       * @description Disable TLS certificate verification for connections to this integration.
       * @default false
       */
      insecure_skip_tls_verify?: boolean
      /**
       * Ca Certificate
       * @description PEM-encoded CA certificate to trust for this integration's TLS connections.
       */
      ca_certificate?: string | null
    }
    /**
     * DiscoveredLLMModel
     * @description A model discovered from an LLM provider.
     */
    DiscoveredLLMModel: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * DiscoveredToolParameter
     * @description A parameter belonging to a discovered tool.
     */
    DiscoveredToolParameter: {
      /** Name */
      name: string
      /**
       * Type
       * @default string
       */
      type?: string
      /**
       * Description
       * @default
       */
      description?: string
      /**
       * Required
       * @default false
       */
      required?: boolean
    }
    /**
     * DiscoveredTool
     * @description A tool discovered from an MCP server.
     *
     *     Carries parameter information so that _sync_mcp_tools() can do a full
     *     upsert without re-fetching from MCP.
     */
    DiscoveredTool: {
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /** Parameters */
      parameters?: components['schemas']['DiscoveredToolParameter'][] | null
    }
    /**
     * HealthCheckErrorType
     * @description Classification of health check failures.
     * @enum {string}
     */
    HealthCheckErrorType: 'auth_failure' | 'connection_error' | 'rate_limit' | 'ssl_error' | 'timeout'
    /**
     * ValidateResult
     * @description Result of a lightweight connectivity ping (validate endpoint).
     *
     *     Contains only connection-health fields. No resource discovery fields.
     */
    ValidateResult: {
      /** Success */
      success: boolean
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string
      /** Error */
      error?: string | null
      error_type?: components['schemas']['HealthCheckErrorType'] | null
    }
    /**
     * DiscoverResult
     * @description Result of a resource-discovery operation (discover endpoint).
     *
     *     Returned by the unsaved-connection test (POST /integrations/discover)
     *     and used internally by refresh_resources() to drive tool sync.
     */
    DiscoverResult: {
      /** Success */
      success: boolean
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string
      /** Error */
      error?: string | null
      error_type?: components['schemas']['HealthCheckErrorType'] | null
      /** Discovered Tools */
      discovered_tools?: components['schemas']['DiscoveredTool'][] | null
      /** Discovered Models */
      discovered_models?: components['schemas']['DiscoveredLLMModel'][] | null
    }
    /**
     * IntegrationRefreshStatus
     * @description Status of the last resource-refresh operation for an integration.
     * @enum {string}
     */
    IntegrationRefreshStatus: 'refreshing' | 'available' | 'warning' | 'error'
    /**
     * RefreshResult
     * @description Result returned by POST /integrations/{id}/refresh.
     *
     *     Covers both MCP tool and LLM model refreshes. ``missing_count``
     *     reflects resources no longer offered by the provider: MCP tools are
     *     marked MISSING and LLM models are counted as missing. Rows are
     *     preserved and ``enabled`` is never changed by discovery (it is
     *     admin-controlled).
     */
    RefreshResult: {
      /**
       * Synced Count
       * @description Number of new resource records created
       */
      synced_count: number
      /**
       * Updated Count
       * @description Number of existing resource records updated
       */
      updated_count: number
      /**
       * Missing Count
       * @description Number of resources no longer offered by the provider
       */
      missing_count: number
      /**
       * Refreshed At
       * @description Timestamp when the refresh completed
       */
      refreshed_at?: string | null
    }
    /**
     * LLMModelListResponse
     * @description Paginated response for LLM models.
     */
    LLMModelListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['LLMModelRead'][]
    }
    /**
     * LLMModelRead
     * @description Schema for LLM model API responses.
     */
    LLMModelRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Integration Id
       * Format: uuid
       */
      integration_id: string
      /** Model Id */
      model_id: string
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean
      /**
       * Is Default
       * @default false
       */
      is_default?: boolean
      /** Last Refreshed At */
      last_refreshed_at?: string | null
      /** @description Model capability profile */
      profile?: components['schemas']['ModelCapabilityProfile'] | null
      /** Created At */
      created_at?: string | null
      /** Updated At */
      updated_at?: string | null
    }
    /**
     * ModelCapabilityProfile
     * @description Typed view of an LLM model's capability profile.
     */
    ModelCapabilityProfile: {
      /** Name */
      name?: string | null
      /** Status */
      status?: string | null
      /** Release Date */
      release_date?: string | null
      /** Last Updated */
      last_updated?: string | null
      /** Open Weights */
      open_weights?: boolean | null
      /** Max Input Tokens */
      max_input_tokens?: number | null
      /** Text Inputs */
      text_inputs?: boolean | null
      /** Image Inputs */
      image_inputs?: boolean | null
      /** Image Url Inputs */
      image_url_inputs?: boolean | null
      /** Pdf Inputs */
      pdf_inputs?: boolean | null
      /** Audio Inputs */
      audio_inputs?: boolean | null
      /** Video Inputs */
      video_inputs?: boolean | null
      /** Image Tool Message */
      image_tool_message?: boolean | null
      /** Pdf Tool Message */
      pdf_tool_message?: boolean | null
      /** Max Output Tokens */
      max_output_tokens?: number | null
      /** Reasoning Output */
      reasoning_output?: boolean | null
      /** Text Outputs */
      text_outputs?: boolean | null
      /** Image Outputs */
      image_outputs?: boolean | null
      /** Audio Outputs */
      audio_outputs?: boolean | null
      /** Video Outputs */
      video_outputs?: boolean | null
      /** Tool Calling */
      tool_calling?: boolean | null
      /** Tool Choice */
      tool_choice?: boolean | null
      /** Tool Call Streaming */
      tool_call_streaming?: boolean | null
      /** Structured Output */
      structured_output?: boolean | null
      /** Attachment */
      attachment?: boolean | null
      /** Temperature */
      temperature?: boolean | null
    }
    /**
     * LLMModelUpdate
     * @description Schema for updating an LLM model (enable/disable, set as default).
     */
    LLMModelUpdate: {
      /** Enabled */
      enabled?: boolean | null
      /** Is Default */
      is_default?: boolean | null
    }
    /**
     * LLMModelBulkUpdate
     * @description Schema for bulk-updating LLM models.
     */
    LLMModelBulkUpdate: {
      /**
       * Model Ids
       * @description Model IDs to update
       */
      model_ids: string[]
      /**
       * Enabled
       * @description New enabled state
       */
      enabled: boolean
    }
    /**
     * LLMModelBulkUpdateResponse
     * @description Response for bulk LLM model update.
     */
    LLMModelBulkUpdateResponse: {
      /**
       * Updated Count
       * @description Number of models updated
       */
      updated_count: number
      /**
       * Skipped Count
       * @description Number of model IDs not found in integration
       */
      skipped_count: number
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp of the update
       */
      updated_at: string
    }
    /**
     * ToolListResponse
     * @description Paginated list response for tools.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ToolListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['ToolWithParameters'][]
    }
    ToolWithParameters: components['schemas']['UserOwnedResource'] &
      components['schemas']['NamedResource'] & {
        /**
         * Integration Id
         * Format: uuid
         * @description UUID of the owning Integration (mcp_server)
         */
        integration_id: string
        /**
         * Namespaced Name
         * @description Unique namespaced name for the tool
         */
        namespaced_name: string
        /**
         * Enabled
         * @description Whether the tool is enabled
         * @default true
         */
        enabled?: boolean
        /**
         * @description Current status of the tool
         * @default available
         */
        status?: components['schemas']['ToolStatus']
        /**
         * Last Executed At
         * @description Timestamp of last execution
         */
        last_executed_at?: string | null
        /**
         * Last Refreshed At
         * @description Timestamp of last refresh from provider
         */
        last_refreshed_at?: string | null
        /**
         * Refresh Error
         * @description Error message from last refresh attempt
         */
        refresh_error?: string | null
        /**
         * Parameters
         * @description Tool parameters
         */
        parameters: components['schemas']['ToolParameter'][]
      }
    /**
     * ToolUpdate
     * @description Model for updating tool configuration.
     */
    ToolUpdate: {
      /**
       * Enabled
       * @description Whether the tool is enabled
       */
      enabled?: boolean | null
      /** @description Current status of the tool */
      status?: components['schemas']['ToolStatus'] | null
      /**
       * Refresh Error
       * @description Error message from last refresh attempt
       */
      refresh_error?: string | null
    }
    /**
     * ToolBulkUpdate
     * @description Request model for bulk updating tool status.
     *
     *     Attributes:
     *         tool_ids: List of tool UUIDs to update (max 50)
     *         enabled: Enable or disable the Tool.
     */
    ToolBulkUpdate: {
      /**
       * Tool Ids
       * @description List of tool UUIDs to update (max 50)
       */
      tool_ids: string[]
      /**
       * Enabled
       * @description Enable/disable the Tool
       */
      enabled: boolean
    }
    /**
     * ToolBulkUpdateResponse
     * @description Response model for bulk tool update.
     */
    ToolBulkUpdateResponse: {
      /**
       * Updated Count
       * @description Number of tools updated
       */
      updated_count: number
      /**
       * Skipped Count
       * @description Number of tool IDs not found or not in scope
       */
      skipped_count: number
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp of the update
       */
      updated_at: string
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponseBase: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources?: unknown[]
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    UserOwnedResource: components['schemas']['BaseResource'] & {
      /**
       * Created By
       * Format: uuid
       * @description User (or automation) that created the resource
       * @example 770e8400-e29b-41d4-a716-446655440000
       */
      readonly created_by: string
      /**
       * Updated By
       * @description User (or automation) that last updated the resource
       * @example 880e8400-e29b-41d4-a716-446655440000
       */
      readonly updated_by?: string | null
    }
    NamedResource: components['schemas']['BaseResource'] & {
      /**
       * Name
       * @description Human-readable name for the resource
       * @example Authentication Service
       */
      name: string
      /**
       * Description
       * @description Detailed description of the resource
       * @example Handles user authentication and authorization workflows
       */
      description?: string | null
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
    /**
     * ToolStatus
     * @description Status of a tool.
     * @enum {string}
     */
    ToolStatus: 'available' | 'missing' | 'error'
    /**
     * ToolParameterType
     * @description Parameter types for tools.
     * @enum {string}
     */
    ToolParameterType: 'string' | 'number' | 'boolean' | 'object' | 'array'
    ToolParameter: components['schemas']['BaseResource'] & {
      /**
       * Tool Id
       * Format: uuid
       */
      tool_id: string
      /**
       * Name
       * @description Parameter name
       */
      name: string
      /** @description Parameter type */
      type: components['schemas']['ToolParameterType']
      /**
       * Description
       * @description Parameter description
       */
      description: string
      /**
       * Required
       * @description Whether this parameter is required
       */
      required: boolean
      /**
       * Default Value
       * @description Default value for the parameter
       */
      default_value?: {
        [key: string]: unknown
      } | null
      /**
       * Example Value
       * @description Example value for the parameter
       */
      example_value?: {
        [key: string]: unknown
      } | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_integrations: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
        /** @description Filter by integration type */
        integration_type?: components['schemas']['IntegrationType'] | null
        /** @description Filter by validation status */
        validation_status?: components['schemas']['IntegrationStatus'] | null
        /** @description Filter by enabled status */
        enabled?: boolean | null
        /** @description Filter by visibility scope */
        scope?: components['schemas']['IntegrationScope'] | null
        /** @description Filter by management credential ID (credential used for admin operations like validation and tool/model discovery) */
        management_credential_id?: string | null
        /** @description Filter to integrations that are global or assigned to this project. Restricted to projects the user has RBAC access to; querying inaccessible projects returns only global integrations. */
        project_id?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  create_integration: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IntegrationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_integration: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_integration: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  update_integration: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IntegrationUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  discover_integration_connection: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IntegrationTestConnection']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DiscoverResult']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  validate_integration: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ValidateResult']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  refresh_resources: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RefreshResult']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_integration_projects: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationProjectAssignmentListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  assign_integration_project: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationProjectAssignmentRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  unassign_integration_project: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_integration_models: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: string | null
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LLMModelListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_integration_model: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LLMModelRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  update_integration_model: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
        model_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LLMModelUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LLMModelRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  bulk_update_integration_models: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LLMModelBulkUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LLMModelBulkUpdateResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  list_integration_tools: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_integration_tool: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
        tool_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolWithParameters']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  update_integration_tool: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
        tool_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ToolUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolWithParameters']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  bulk_update_integration_tools: {
    parameters: {
      query?: never
      header?: never
      path: {
        integration_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ToolBulkUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolBulkUpdateResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
