/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tools': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Tools
     * @description List tools with filtering, sorting, and pagination.
     *
     *     Tools are filtered by the caller's integration visibility — only tools
     *     belonging to visible integrations are returned.
     */
    get: operations['list_tools']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tools/{tool_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Tool
     * @description Get tool details by ID.
     */
    get: operations['get_tool']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update Tool
     * @description Update tool status (enable/disable).
     */
    patch: operations['update_tool']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ToolListResponse
     * @description Paginated list response for tools.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ToolListResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['ToolWithParameters'][]
    }
    /**
     * ToolStatus
     * @description Status of a tool.
     * @enum {string}
     */
    ToolStatus: 'available' | 'missing' | 'error'
    /**
     * ToolParameterType
     * @description Parameter types for tools.
     * @enum {string}
     */
    ToolParameterType: 'string' | 'number' | 'boolean' | 'object' | 'array'
    ToolWithParameters: components['schemas']['UserOwnedResource'] &
      components['schemas']['NamedResource'] & {
        /**
         * Integration Id
         * Format: uuid
         * @description UUID of the owning Integration (mcp_server)
         */
        integration_id: string
        /**
         * Namespaced Name
         * @description Unique namespaced name for the tool
         */
        namespaced_name: string
        /**
         * Enabled
         * @description Whether the tool is enabled
         * @default true
         */
        enabled?: boolean
        /**
         * @description Current status of the tool
         * @default available
         */
        status?: components['schemas']['ToolStatus']
        /**
         * Last Executed At
         * @description Timestamp of last execution
         */
        last_executed_at?: string | null
        /**
         * Last Refreshed At
         * @description Timestamp of last refresh from provider
         */
        last_refreshed_at?: string | null
        /**
         * Refresh Error
         * @description Error message from last refresh attempt
         */
        refresh_error?: string | null
        /**
         * Parameters
         * @description Tool parameters
         */
        parameters: components['schemas']['ToolParameter'][]
      }
    ToolParameter: components['schemas']['BaseResource'] & {
      /**
       * Tool Id
       * Format: uuid
       */
      tool_id: string
      /**
       * Name
       * @description Parameter name
       */
      name: string
      /** @description Parameter type */
      type: components['schemas']['ToolParameterType']
      /**
       * Description
       * @description Parameter description
       */
      description: string
      /**
       * Required
       * @description Whether this parameter is required
       */
      required: boolean
      /**
       * Default Value
       * @description Default value for the parameter
       */
      default_value?: {
        [key: string]: unknown
      } | null
      /**
       * Example Value
       * @description Example value for the parameter
       */
      example_value?: {
        [key: string]: unknown
      } | null
    }
    /**
     * ToolUpdate
     * @description Model for updating tool configuration.
     */
    ToolUpdate: {
      /**
       * Enabled
       * @description Whether the tool is enabled
       */
      enabled?: boolean | null
      /** @description Current status of the tool */
      status?: components['schemas']['ToolStatus'] | null
      /**
       * Refresh Error
       * @description Error message from last refresh attempt
       */
      refresh_error?: string | null
    }
    /**
     * ToolBulkUpdate
     * @description Request model for bulk updating tool status.
     *
     *     Attributes:
     *         tool_ids: List of tool UUIDs to update (max 50)
     *         enabled: Enable or disable the Tool.
     */
    ToolBulkUpdate: {
      /**
       * Tool Ids
       * @description List of tool UUIDs to update (max 50)
       */
      tool_ids: string[]
      /**
       * Enabled
       * @description Enable/disable the Tool
       */
      enabled: boolean
    }
    /**
     * ToolBulkUpdateResponse
     * @description Response model for bulk tool update.
     */
    ToolBulkUpdateResponse: {
      /**
       * Updated Count
       * @description Number of tools updated
       */
      updated_count: number
      /**
       * Skipped Count
       * @description Number of tool IDs not found or not in scope
       */
      skipped_count: number
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp of the update
       */
      updated_at: string
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponseBase: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources?: unknown[]
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    UserOwnedResource: components['schemas']['BaseResource'] & {
      /**
       * Created By
       * Format: uuid
       * @description User (or automation) that created the resource
       * @example 770e8400-e29b-41d4-a716-446655440000
       */
      readonly created_by: string
      /**
       * Updated By
       * @description User (or automation) that last updated the resource
       * @example 880e8400-e29b-41d4-a716-446655440000
       */
      readonly updated_by?: string | null
    }
    NamedResource: components['schemas']['BaseResource'] & {
      /**
       * Name
       * @description Human-readable name for the resource
       * @example Authentication Service
       */
      name: string
      /**
       * Description
       * @description Detailed description of the resource
       * @example Handles user authentication and authorization workflows
       */
      description?: string | null
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.example.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.example.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.example.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.example.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_tools: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_tool: {
    parameters: {
      query?: never
      header?: never
      path: {
        tool_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolWithParameters']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  update_tool: {
    parameters: {
      query?: never
      header?: never
      path: {
        tool_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ToolUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolWithParameters']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
