from enum import Enum


class MetricType(str, Enum):
    ACTIVE_WORKFLOWS = "active_workflows"
    ACTIVITY_DURATION_MS = "activity_duration_ms"
    ACTIVITY_EXECUTION_SUCCESS_RATE = "activity_execution_success_rate"
    AGENT_INVOCATION_MS = "agent_invocation_ms"
    AGENT_ROUTING_MS = "agent_routing_ms"
    AGENT_STATUS = "agent_status"
    API_ERROR_RATE = "api_error_rate"
    API_RESPONSE_TIME_MS = "api_response_time_ms"
    API_THROUGHPUT_RPS = "api_throughput_rps"
    AUTHZ_DURATION_MS = "authz_duration_ms"
    AUTH_FAILURE = "auth_failure"
    CACHE_HIT = "cache_hit"
    CACHE_LOOKUP_MS = "cache_lookup_ms"
    CACHE_MISS = "cache_miss"
    CACHE_POOL_RETRY_BACKOFF_DURATION_MS = "cache_pool_retry_backoff_duration_ms"
    CACHE_POOL_RETRY_TOTAL = "cache_pool_retry_total"
    CACHE_UTILIZATION_RATIO = "cache_utilization_ratio"
    CONTEXT_DURATION_MS = "context_duration_ms"
    DATABASE_CONNECTION_POOL_UTILIZATION_RATIO = "database_connection_pool_utilization_ratio"
    DATABASE_QUERY_RESPONSE_TIME_MS = "database_query_response_time_ms"
    DATABASE_TRANSACTION_RATE_TPS = "database_transaction_rate_tps"
    ERROR = "error"
    LLM_DURATION_MS = "llm_duration_ms"
    LLM_STATUS = "llm_status"
    LLM_TOKENS_INPUT = "llm_tokens_input"
    LLM_TOKENS_OUTPUT = "llm_tokens_output"
    LLM_TTFT_MS = "llm_ttft_ms"
    OPA_REQUEST_DURATION_MS = "opa_request_duration_ms"
    REQUEST_DURATION_MS = "request_duration_ms"
    SCHEDULED_TRIGGER_FIRES_TOTAL = "scheduled_trigger_fires_total"
    SCHEDULED_TRIGGER_LATENCY_MS = "scheduled_trigger_latency_ms"
    SYSTEM_E2E_LATENCY_MS = "system_e2e_latency_ms"
    SYSTEM_ERROR_RATE = "system_error_rate"
    SYSTEM_UPTIME_SECONDS = "system_uptime_seconds"
    TEMPORAL_EXECUTION_SERVICE_DURATION_MS = "temporal_execution_service_duration_ms"
    TEMPORAL_QUEUE_DEPTH = "temporal_queue_depth"
    TOOL_EXECUTION_DURATION_MS = "tool_execution_duration_ms"
    TOOL_EXECUTION_STATUS = "tool_execution_status"
    WORKFLOW_COMPLETION_RATE = "workflow_completion_rate"
    WORKFLOW_CREATION_SUCCESS_RATE = "workflow_creation_success_rate"
    WORKFLOW_DURATION_MS = "workflow_duration_ms"
    WORKFLOW_SERIALIZATION_DURATION_MS = "workflow_serialization_duration_ms"
    WORKFLOW_START_LATENCY_MS = "workflow_start_latency_ms"
    WORKFLOW_STATUS = "workflow_status"
    WORKFLOW_VALIDATION_DURATION_MS = "workflow_validation_duration_ms"

    def __str__(self) -> str:
        return str(self.value)
